### ISSUE TITLE
MAME can't load a lua script through libTAS

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#101]
Example script saved as `/home/feos/Desktop/test.lua`:
`print(emu.app_name() .. " " .. emu.app_version())`

I run
`mame btoads -autoboot_script /home/feos/Desktop/test.lua`
normally, and the script prints to the terminal.

If I run through libTAS, it says
`[LUA ERROR] 7 loading Lua script`

Since libTAS doesn't have scripting, and I've heard complaints about its ram search speed, I wanted to use [mame itself for that](https://docs.mamedev.org/techspecs/luaengine.html), and I can't. This would be very helpful to have working.

**Comment by clementgallet** [comment]
This lua script is working for me. At first I used the relative path to the script and I got the same error as you. After changing to the full absolute path, it worked.

**Comment by vadosnaprimer** [comment]
Sorry it does indeed work.
![2018-10-31-193820_1024x768_scrot](https://user-images.githubusercontent.com/7092625/47803944-acb72b00-dd44-11e8-8aae-42db9ce4ff49.png)
