### ISSUE TITLE
The project could use an icon to identify itself

### ISSUE THREAD

**Issue by chungy** [clementgallet/libTAS#105]
I've built an Arch Linux PKGBUILD and included a *.desktop file to launch the program via your DE's GUI: https://aur.archlinux.org/cgit/aur.git/tree/linTAS.desktop?h=libtas

Only issue is that I cannot find any sort of icon in the project to represent itself, nor have a non-generic icon show up in the app drawer. Would be nice to rectify this.

**Comment by vadosnaprimer** [comment]
Related https://github.com/clementgallet/libTAS/issues/81

**Comment by ShayBox** [comment]
Any progress on this? even a generic tas icon would be great
![image](https://user-images.githubusercontent.com/9505196/57355194-75826600-713b-11e9-9eb5-3c23d03464bc.png)

**Comment by clementgallet** [comment]
The icon was added in 8ddabeddb30b4d71e1bfea18c8b7586fc90d6ff8
