### ISSUE TITLE
Desyncs when mouse recalibration is used

### ISSUE THREAD

**Issue by chungy** [clementgallet/libTAS#107]
Note: this might be me misunderstanding the feature. I am using the current HEAD as of today.

Trying to record Strife (a first-person shooter), I found myself using mouse recalibration often so that I don't manipulate the view when playing frame-by-frame, seemed to work while recording. However, as soon as I go to playback, it seems to have recorded the mouse changes anyway and it gets played back as such, making the playthrough pretty much unworkable since the direction I headed in the game is no longer going where I wanted it.

**Comment by clementgallet** [comment]
Sorry about that. It should be fixed in 9351ce3ae62197345e697aa6d996b49e3cadf461

**Comment by chungy** [comment]
Yes it seems to be. Thanks!
