### ISSUE TITLE
Compiling with disabled HUD gives error in Checkpoint.cpp

### ISSUE THREAD

**Issue by Masterjun3** [clementgallet/libTAS#108]
Trying to compile by doing
`cmake -DENABLE_HUD=OFF ..`
`make`
gives an error:
<pre><b>/home/masterjun/Desktop/libTAS/src/libTAS/checkpoint/Checkpoint.cpp:</b> In function ‘<b>bool libtas::Checkpoint::checkCheckpoint()</b>’:
<b>/home/masterjun/Desktop/libTAS/src/libTAS/checkpoint/Checkpoint.cpp:174:13:</b> <font color="#EF2929"><b>error: </b></font>‘<b>RenderHUD</b>’ has not been declared
             <font color="#EF2929"><b>RenderHUD</b></font>::insertMessage(&quot;Not enough available space to store the savestate&quot;);
             <font color="#EF2929"><b>^~~~~~~~~</b></font>
</pre>

**Comment by clementgallet** [comment]
Sorry about that, I fixed it in a2f5055a58618de392e6de33f7dcf6ba9ca210c5
