### ISSUE TITLE
Non-incremental crash savestate in some cases.

### ISSUE THREAD

**Issue by alex34567** [clementgallet/libTAS#110]
On commit 8ffeb0 in some cases when restoring a save state without incremental save states on, it will crash.

For example,
on lubuntu 18.10 i386 running undertale 1.01 with this [movie](https://github.com/clementgallet/libTAS/files/2567121/runner.zip) at frame 4100, saving than loading a state will crash.

**Comment by Noahkiq** [comment]
mari0 has been consistently crashing with save states with recent commits, probably related
