### ISSUE TITLE
Rewind-to-frame via save->restart->fast forward

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#115]
Sometimes, I make a mistake but my last save state is a few hundred frames ago. The easiest way for me to fix this is to stop the game, save the TAS, restart the game in fast forward mode with the movie set to pause on the frame I messed up, and then set libTAS back into recording mode and continue.

If this was a built-in operation I could perform in a single step, there would be a lot less of a chance for me to accidentally click "no" on the "do you want to save the TAS" prompt or mess up some other part of the process and be forced to redo it.

It'd also be nice to be able to use either restarting the entire game process or going back to a nearby save state depending on whether there's a loadable save state before the place being rewinded to, since in very long TASes playing through the entire game to go back one frame will take a very long time compared to loading a save state a few hundred frames ago and fast forwarding just through those few hundred frames.

**Comment by clementgallet** [comment]
If you make a mistake, the normal approach is to switch movie status to "playback", then load your savestate. It will keep all your inputs. You can then frame advance until the point where you want to modify the movie, then switch back to "recording".

The feature you are describing (which I called pseudo-savestates) existed before savestates actually worked, but now it makes less sense to keep it. However, as it was suggested elsewhere, when a game is restarted, loading a savestate from the previous execution could act as loading the savestate movie and fast-forward to the savestate frame.

**Comment by vadosnaprimer** [comment]
IIRC Hourglass does it that way upon game restart: you can load a state in terms of loading the movie in it, and it suggests you you FF to the target frame in that movie. I don't know whether it keeps the entire savestate+input object on the disk all the time, but the input in it persists between sessions for sure, and it's a great backup feature.

**Comment by clementgallet** [comment]
It is implemented in d39b16a8214974909ee579464f4cb04808bfebdf. Probably need some more testing.

**Comment by vadosnaprimer** [comment]
There's maybe another option too: always preserving state made at the very first frame. No need to restart then, unless that's explicitly needed.

**Comment by BenLubar** [comment]
In order for the first-frame-save-state thing to work, libTAS would need to pre-spawn a pool of threads at startup so that there wouldn't be any complete invalidations of all save states when threads are run.

**Comment by clementgallet** [comment]
I tried to pre-spawn a lot of threads at the beginning of the game execution, and it crashed when Mesa llvm driver tries to reuse a thread.
