### ISSUE TITLE
[bug] --read truncates ltm file to 0 bytes.

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#116]
Relevant code:
https://github.com/clementgallet/libTAS/blob/6f7f4e5ccf69240538638fc32cd0a6518ea3cfff/src/program/main.cpp#L66-L77

**Comment by clementgallet** [comment]
Sorry for that, I didn't use commandline since the GUI was implemented. Fixed it in 69b84a40ebff2e53063b17a500ac6607c62c2d78
