### ISSUE TITLE
Loading a save state does not restore Deltarune combat to the correct state.

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#117]
Repro instructions (shouldn't need to be very accurate or even in frame advance mode to get this to work):

1. Enter a fight in Deltarune.
2. Save state
3. Go to the ACT menu and move the cursor to a different option.
4. Load state
5. Go back to the ACT menu. Notice the cursor is still over the different option despite never having sent the input to cause that to the game.

This also affects RNG. For example, Hathy's heart outline attack will move in a different direction even if all of the inputs are identical.

**Comment by Noahkiq** [comment]
0. [Install Deltarune natively](https://www.reddit.com/r/Deltarune/comments/9wizh3/deltarune_running_on_linux_natively/)

**Comment by InfamousKnight** [comment]
Wait, he was using wine to run that? I didn’t know that worked at all.

**Comment by Noahkiq** [comment]
no

**Comment by clementgallet** [comment]
Should be fixed by a68e0211b304b9f4863733da2fdb9da9d1876904 , memset-ing  when incremental savestate is disabled.

**Comment by BenLubar** [comment]
Whoops, thought I already closed this. The linked commit does indeed fix the problem.
