### ISSUE TITLE
Virtual screen size does not affect games that use X11 directly instead of SDL.

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#123]
The game is still seeing my 1080p monitor despite having the virtual screen size set to 720p.

**Comment by clementgallet** [comment]
There are many ways to get the screen resolution from X11 :/ I hooked the standard Xlib functions, extensions XF86VidMode and XRandR (d4db0baa287c670ddac96f3577700672d6d92401). The later was the one used by GM:S games.
