### ISSUE TITLE
Controllers don't work in Citra

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#127]
They get detected but fail to initialize:
`[   0.016666] Input <Error> input_common/sdl/sdl_impl.cpp:InitJoystick:198: failed to open joystick 0`

**Comment by clementgallet** [comment]
I fixed the error in deb7222335148799de3a97786f82e9c8ccde9b0f, but I didn't manage to get my controller to work natively in Citra, so I couldn't test if it is actually working now.

**Comment by Noahkiq** [comment]
Yeah, error code is gone but I can't work out this config system...

**Comment by clementgallet** [comment]
I couldn't make my controller to work even when following https://community.citra-emu.org/t/temporary-controller-configurations-for-citra/1061 :/

**Comment by Noahkiq** [comment]
could probably close this, doesn't exactly sound like a libTAS issue anymore

(still haven't worked out the config system though to get a controller working lol.)

**Comment by clementgallet** [comment]
Closing until we figure out how controllers work in Citra.
