### ISSUE TITLE
Loading savestate while recording with input editor open crashes

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#129]
(sometimes)

**Comment by clementgallet** [comment]
This happens specifically when the input editor is opened ? And does libTAS program crash ?

**Comment by Noahkiq** [comment]
A more accurate description would be that the GUI hangs as the game can still run but yes

**Comment by clementgallet** [comment]
I may have fixed that in ad2cc262354874d95cb933da6beaeb417dfa2cb0. libTAS was freezing by infinitely calling a function that resizes the input editor columns based their content. I changed this setting to a fixed size, and I mostly only compute the size once for each column now.

**Comment by Noahkiq** [comment]
i'll close for now and reopen if i experience issues
