### ISSUE TITLE
The input file goes sometimes offsync

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#13]
This tends to happen after changing resolutions in meatboy. Worth noting that resolution itself changes the behavior of meatboy and this input files made for different resolutions might not be compatible. Restarting the input file has fixed this problem every time so far.

**Comment by Matte27** [comment]
Also happened without changing resolution, a couple restarts were required to get the whole movie to stay in sync

**Comment by Matte27** [comment]
Seems to be happening most commonly during level transitions

**Comment by Matte27** [comment]
Sometimes the loading text in meatboy lingers for longer than usual

**Comment by clementgallet** [comment]
This seems to have been fixed by always initializing allocated memory (57b6be40ef32a66752d4300d283fe91cfc9f2dfa). In meatboy, however, the intro sequence was showed to be longer on certain resolutions than on others when running through a VM
