### ISSUE TITLE
Ppsspp doesn’t play back if save states were used

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#130]
If save states are not used, it will work fine.

Steps to reproduce crash on both game and program:
Start ppsspp with the aforementioned configuration
Make a save state at whatever point in the game once loaded
Load the save state(notice re-record count is not incremented if done twice)
Go back to libtas to stop the movie, and you can’t do anything besides force quit both the game and the program. 

Also, would it be possible to get around speed toggle so we can play it at regular speed? Maybe some temporary option for second thread?

**Comment by Noahkiq** [comment]
does disabling Incremental Savestates fix this?

**Comment by clementgallet** [comment]
Well, I'm reopening the issue because incremental savestates shouldn't create any issue.

**Comment by clementgallet** [comment]
If I understand correctly, you cannot close the emulator cleanly if you have loaded a savestate during the execution ? I'm confused with the title of the issue. Doesn't libTAS show you a "Kill" button after you pressed "Stop" ?

**Comment by InfamousKnight** [comment]
Libtas does not show a kill button after stop under these conditions. It will just hang. That and the game. I did not stop it while loading a save state either.

**Comment by clementgallet** [comment]
This may be related to issue #129, which may have been fixed (yes, that's a lot of "may")
