### ISSUE TITLE
Games fail to load

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#131]
Was a new dependency added? Games crash with "Got unknown message!!!" before even creating a window. Citra additionally prints "[libTAS f:0] Thread 8917 (main) ERROR: Could not import symbol XRRGetCrtcInfo" before crashing but this may be unrelated.

**Comment by Noahkiq** [comment]
Seems to be an issue with the fixes for #123 as x11 games run fine

**Comment by clementgallet** [comment]
Sorry about that. Fixed in (1887d1546ee8e94f5ef0c86d40621d00d478a24f)
