### ISSUE TITLE
uninitializedThreadCount seems to stop at 1 rather than 0

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#132]
This may be related to the recent thread init changes. This is pretty much 100% reproducible with my current Deltarune TAS. (Try playing through and then saving a state; it gets stuck after "Saving state" without ever reaching "Saved state")

Going in with GDB and setting the field to 0 manually seems to fix the issue without any bad side effects.

**Comment by clementgallet** [comment]
Yeah, I'm stupid. Fixed in ad11be1b5dc3e65333f0c2b6f5933adc9bcbd3c6
