### ISSUE TITLE
Input Editor - Autorestore playback position

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#134]
This idea originates from FCEUX, but there it fully depends on savestates being done very frequently and automatically. This it what it does:

If you are at frame 100 and you change input at frame 90 (for instance), the emulator would load the nearest savestate above frame 90 (for instance, state at frame 89), and replay your movie up to the frame 100 again, pausing there.

When there's automatic functionality for this, it speeds up tedious TASing routine tremendously. Without it you have to switch modes, edit input, switch modes, watch, or just record all the macro you need on that segment all over again, with a single button changing, and then you also have to stop at the same frame you were at originally, to make the comparison faithful. You would probably keep the best attempt in a savestate, comparing to it by loading repeatedly.

What aspects of libTAS are in the way of autorestore? The only issue I'm seeing is unpredictable gap between savestates. What if this is resolved by a max autorestore interval?

You set this interval to 20 frames. You are at frame 100. You edit input at frame 90. If the nearest state is farther back than frame 70 (90-20), nothing happens. If you happen to have a state at frame 80, the tool would load it and replay from there up to frame 100 again, and pause there.

With this functionality, all you have to do to find the first frame to press a button is just clicking a single input roll cell repeatedly.

**Comment by clementgallet** [comment]
Implemented in eb311141d95a00a34ff60da7b0a27226e25aed49
