### ISSUE TITLE
Citra crashes at startup

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#135]
Attempting to run Asphalt 3d in citra with libTAS(I turned off mute) using interim build(at least I think it was running interim) gives the following message:
sean@sean-X541UAK:~/libTAS$ ./libTAS
bash: ./libTAS: No such file or directory
sean@sean-X541UAK:~/libTAS$ libTAS

(libTAS:14050): dbind-WARNING **: 11:55:47.330: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
QApplication: invalid style override passed, ignoring it.
Gtk-Message: 11:56:16.778: GtkDialog mapped without a transient parent. This is discouraged.
[libTAS f:0] Thread 14074 (main) ERROR: Unknown socket message -136394806
Attempt 1: Couldn't connect to socket.
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Couldn't connect to socket.
Attempt 5: Couldn't connect to socket.
Attempt 6: Couldn't connect to socket.
Attempt 7: Couldn't connect to socket.
Attempt 8: Couldn't connect to socket.
Attempt 9: Couldn't connect to socket.
Attempt 10: Couldn't connect to socket.
Got unknown message!!!

I did everything you said config wise(sdl2 only configs) and I'm running lubuntu 18.04 native install.

**Comment by clementgallet** [comment]
To launch the interim version after building it, you should execute the libTAS binary inside the `build` directory. If you simply type `libTAS` in the terminal, it will launch the one install from the package.

**Comment by InfamousKnight** [comment]
Yeah, I figured that out this morning.

Thanks
