### ISSUE TITLE
How do I tas a flash game using sdl-gnash?

### ISSUE THREAD

**Issue by Thestickman391** [clementgallet/libTAS#137]
I've been trying to use libTAS + sdl-gnash to tas a flash game, however, I get the error `Could not determine arch of file /home/thestickman391/Desktop/gnash.desktop based on the 'file' command output. Full output: UTF-8 Unicode text`. Am I supposed to be launching gnash.desktop? Any help would be very much appreciated. 
![image](https://user-images.githubusercontent.com/4157860/50552585-35c5f080-0cfb-11e9-883c-86d488c5590a.png)

**Comment by vadosnaprimer** [comment]
Tried this guide?
http://tasvideos.org/forum/viewtopic.php?t=20547

**Comment by clementgallet** [comment]
`gnash.desktop` is the desktop entry to gnash (like a shortcut), not the actual binary. You need to set the actual path to gnash (which should be `/usr/bin/gnash` or `/usr/local/bin/gnash`)

**Comment by Thestickman391** [comment]
I get this error when trying to launch gnash through `/usr/bin/gnash`
![image](https://user-images.githubusercontent.com/4157860/50552942-69f0df80-0d02-11e9-861a-c24a48754927.png)

**Comment by clementgallet** [comment]
Oh yes, `gnash` is actually a script which selects one version to launch. You specifically need to use `sdl-gnash`, which is the only version supported by libTAS. If you don't have it installed, then please refer to the link posted above.
