### ISSUE TITLE
thread error spam when making save state running citra

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#138]
Running asphalt 3d with latest interim(the one before auto restart was stored in meta data) gives an endless message of:

[libTAS f:2210] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2211] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2212] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2213] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2214] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2215] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2216] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2217] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2218] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2219] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2220] Thread 1638 (main) ERROR: Unknown message received
[libTAS f:2221] Thread 1638 (main) ERROR: Unknown message received
it will continue running, but thats in the console. Loading the save state doesn't work either.

This seems like a new problem. Has threading become flawed?

**Comment by clementgallet** [comment]
I don't have any problem with the current interim version, and I tested this game. Does it happen after you are make a savestate? And every single time?

**Comment by InfamousKnight** [comment]
To reproduce, don't touch any configs in libTAS like you said, when ubisoft logo shows up, make a save state, just create one. And the error message above will show. I'm also using latest interim with libtas. Haven't updated citra yet.
