### ISSUE TITLE
Can't enable osd..

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#145]
I followed the build guide trying to enable OSD with -DENABLE HUD=ON/OFF and it gives me an error:

-- Checking for modules 'freetype2;fontconfig'
--   No package 'freetype2' found
--   No package 'fontconfig' found
CMake Warning at CMakeLists.txt:260 (message):
  HUD is disabled

Running ubuntu 18.04.1 latest interim on 64-bit native

**Comment by clementgallet** [comment]
Did you install the packages using `apt-get install libfreetype6-dev libfontconfig1-dev`?

**Comment by InfamousKnight** [comment]
I didn't install those.. Now it works! Thanks
