### ISSUE TITLE
Update wiki page for ppsspp

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#147]
Psp tasing is now viable with the updated settings:
Libtas
Runtime - backup save files in memory off
Runtime - time tracking - main thread - 
getclocktime
Encode configuration H.264
Disable tab key for fast forward

ppsspp
Set speed toggle to tab
Set save state to 1(or any number)
Set load state to anything besides what save state is

Start recording, click on game, advance frame, press tab, advance some more frames, press load state and continue

You can copy and paste that if you want.

**Comment by clementgallet** [comment]
The thing about emulator savestating at the first frame needs more investigation. It shouldn't be needed.

**Comment by InfamousKnight** [comment]
The save state workaround doesn’t work very well btw. At later times, desyncs are likely to occur. This must be because of the real system time issue. When loading a save state, system time must still be advancing and making quite a mess in the time line.

**Comment by clementgallet** [comment]
PPSSPP stores the emulated system time inside savestates, so this is not the cause. I don't know where it comes from.

**Comment by InfamousKnight** [comment]
A couple of findings: if you have time tracking - main thread - gettimeofday enabled, it will always spawn different things. Even with the save state load.

If you have clockgettime enabled, it will likely sync. If no save state is loaded but you have clockgettime enabled, it will always desync because of non-determistic rng.

That is weird.

**Comment by clementgallet** [comment]
Deterministic issues are still being worked on in #151
