### ISSUE TITLE
Latest interim of citra no longer works

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#149]
Also using latest interim of libtas, citra doesn't seem to work anymore. I did follow the citra thread like before, but now an error message pops up:

Attempt 1: Connected.
[   0.000000] Input <Info> input_common/udp/client.cpp:StartCommunication:199: Starting communication with UDP input server on 127.0.0.1:26760
[libTAS f:0] Thread 11367 (main) OpenGL vendor: VMware, Inc.
[libTAS f:0] Thread 11367 (main) OpenGL renderer: llvmpipe (LLVM 6.0, 256 bits)
[   0.000000] Frontend <Info> citra/emu_window/emu_window_sdl2.cpp:EmuWindow_SDL2:168: Citra Version:  | master-4f23d5d6
[   0.000000] Config <Info> core/settings.cpp:LogSettings:67: Citra Configuration:
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Core_UseCpuJit: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseHwRenderer: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseHwShader: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_ShadersAccurateGs: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_ShadersAccurateMul: false
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseShaderJit: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseResolutionFactor: 1
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseVsync: false
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_UseFrameLimit: true
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Renderer_FrameLimit: 100
[   0.000000] Config <Info> core/settings.cpp:LogSetting:63: Layout_Toggle3d: false
Got unknown message!!!

which is a shame because kingdom hearts dream drop distance now works perfectly on some hardware.

**Comment by Noahkiq** [comment]
cannot reproduce

**Comment by clementgallet** [comment]
Also can't reproduce. Could you run with "Start and attach gdb", and when it is hitting the crash, go to the terminal, you should see an error message and a command prompt `(gdb)`. Copy here the error, and enter `bt` in the prompt and copy the result here. Thanks!

**Comment by InfamousKnight** [comment]
I’ll do this tomorrow. I’m at work now for the whole day..

**Comment by InfamousKnight** [comment]
Sorry about that.. I’m at work for the whole day and will get the results tomorrow.

**Comment by InfamousKnight** [comment]
Issue resolved: what happened was a long file path was dragged into the command-line field and libtas didn’t like that. Rename it to something shorter and you should be good.
