### ISSUE TITLE
INK occasionally crashes several frames after loading a savestate

### ISSUE THREAD

**Issue by lexikiq** [clementgallet/libTAS#153]
Not sure what causes it but it's only occurring when actually going frame by frame

**Comment by Noahkiq** [comment]
This is sometimes printed in the logs: `QXcbConnection: XCB error: 3 (BadWindow), sequence: 43673, resource id: 44040599, major code: 40 (TranslateCoords), minor code: 0`

**Comment by Noahkiq** [comment]
Possibly related: running the game in fastforward results in some elements disappearing
![image](https://user-images.githubusercontent.com/13265322/51416765-ef6cf000-1b48-11e9-8a45-d64b2c487a49.png)

**Comment by Noahkiq** [comment]
any chance you could look into this @clementgallet?

**Comment by clementgallet** [comment]
I'm getting the crashes too. A reliable way to trigger a crash is too save a state, perform a double jump, load the state, then perform a double jump again.

Crashes occur in one of the threads that feed the audio driver with sfx. It is possible that there is a bug in the recent file handling, because those threads are opening and closing OGG files a lot.

The fast-forward behavior is normal. Fast-forwarding skips some rendering functions, and sometimes those are used to permanently store some objects.

**Comment by clementgallet** [comment]
When a thread crash, here is what is always happening before:

    [libTAS f:264] Thread 13749        fopen call with filename assets/sfxsplat4.ogg and mode rb
    [libTAS f:264] Thread 13749        alSourcei called with source 13
    [libTAS f:264] Thread 13749          Unbind buffer
    [libTAS f:264] Thread 13749        alGetError call, returning 0
    [libTAS f:264] Thread 13749        alSourcei called with source 13
    [libTAS f:264] Thread 13749          Set looping of 0
    [libTAS f:264] Thread 13749        alGetError call, returning 0

**Comment by Noahkiq** [comment]
Turns out the game doesn't care if you delete all the .ogg files which stops the crashing!

**Comment by clementgallet** [comment]
Same problem on Minit, the game crash if you save a state, continue until the game opens an .ogg file, load the state and continue until the game opens the file again. The file handle code seems to do its job, the file is closed when loading the state.

Backtrace is:
```
Thread 10 "runner" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffce56e700 (LWP 13788)]
0x00000000006f74b5 in ?? ()
(gdb) bt
#0  0x00000000006f74b5 in ?? ()
#1  0x00000000006f45f7 in ?? ()
#2  0x00000000006fb3ca in ?? ()
#3  0x00000000006fb21b in ?? ()
#4  0x00000000005a5c90 in ?? ()
#5  0x000000000074c347 in ?? ()
#6  0x00007ffff7f11f99 in libtas::pthread_start (arg=0x2c14f40) at /home/clement/libtas-1.3.3/src/library/threadwrappers.cpp:130
#7  0x00007ffff74b2fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007ffff653188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I think GM:S is using vorbisfile to handle .ogg files, so we may get some clues by looking at the [source code](https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c) ?

**Comment by clementgallet** [comment]
This was fixed somehow!
