### ISSUE TITLE
Hotline Miami Framework?

### ISSUE THREAD

**Issue by buffet-time** [clementgallet/libTAS#154]
So in [the list of unsupported games](http://tasvideos.org/EmulatorResources/libTAS/GameCompatibility.html) It lists Hotline Miami with the framework as QT5 but was this tested against the Updated version of Hotline Miami or the Original version? They are quite different.

Original is a Game Maker 7 game that was compiled with GM7, but the Updated is using proprietary software Abstraction Games called Game Baker which has it's own compiler. I assume QT5 refers to Updated as that's what most people select. Either way has anyone tried the original version? I'd really like to eventually TAS Hotline Miami preferably Updated but Original would suffice.

**Comment by clementgallet** [comment]
Yes, qt5 version is the updated version. If the original version was indeed made with GM7, then there won't be any Linux version, because GM7 was not available on Linux.

**Comment by InfamousKnight** [comment]
Gm7 could be ported to studio though. As long as the source is available.

**Comment by buffet-time** [comment]
There's a decompiler so ya the source code is out there for the Original Version

**Comment by buffet-time** [comment]
Well actually, someone did port HM1 Original to GM:S so in that case would that be possible to work with it?

**Comment by Noahkiq** [comment]
is qt support planned btw? would be nice for some of the unity games that use it for pre-game configuration (ie clustertruck)

@buffet-time GM:S games run just fine when configured correctly

**Comment by buffet-time** [comment]
@Noahkiq What exactly do you mean by configured correctly? What does that entail exactly?

**Comment by clementgallet** [comment]
I don't think Qt will be supported in a while, like other graphical toolkits (GTK, Java AWT). They use a completely different paradigm for rendering on screen.

**Comment by Noahkiq** [comment]
@buffet-time 
![image](https://user-images.githubusercontent.com/13265322/52475351-3f980a80-2b69-11e9-949d-3c75b9a26e7a.png)
