### ISSUE TITLE
Freej2me support?

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#156]
Freej2me opens with a file dialog box and to my knowledge that hasn’t been hooked yet correct? It also has a Freej2me-sdl in the same folder you’d extract. But that opens with a dialog box as well.

**Comment by clementgallet** [comment]
You can set the game path to launch in argument, but it has to be in URI format, ie:
    java -jar freej2me.jar file:/home/clement/Games/freej2me/build/PrinceOfPersia-TheTwoThrones_s40v3a-N6280.jar

The SDL frontend works by launching a second program coded in C, which acts as a simple SDL program that receives window pixels and sends inputs. libTAS does not support multiple processes. The default frontend (awt) does not currently work, but I will see what I can do.

It should be possible to rewrite a SDL frontend that does not rely on a second program, using java sdl bindings, but it is a bit of work.

**Comment by vadosnaprimer** [comment]
Can a program like libTAS even serialize the state of Java classes? Sounds bizarre, especially considering how even Java itself has [hard time](https://stackoverflow.com/questions/424341/are-there-any-java-vms-which-can-save-their-state-to-a-file-and-then-reload-that) [serializing itself](https://github.com/vsilaev/tascalate-javaflow).

**Comment by InfamousKnight** [comment]
Thanks for looking into this guys!

Saints row and driv3r is what comes to my mind with j2me tasing!

**Comment by vadosnaprimer** [comment]
I was curious and official JVM is written in C++:
http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509

Can this info be useful for hooking into memory management that JVM is doing, serializing it from the outside?

**Comment by clementgallet** [comment]
I think the problem in on the graphical toolkit used (awt), which does a lot of nasty things that libTAS does not handle (like creating multiple windows on top of each other).

**Comment by vadosnaprimer** [comment]
What if libTAS gives up on things it fundamentally can't handle, maybe some things that it can handle could work? For instance, java apps don't necessarily spawn several windows.

**Comment by clementgallet** [comment]
For this specific example, libTAS needs a window id to listen to events (inputs mainly), and it currently takes the wrong one and inputs don't work. Also, I'm talking about a java app that displays a single window, but which is composed of different Xlib windows without borders, acting as frames or widgets. It is likely that every java app using awt will behave as such.

**Comment by vadosnaprimer** [comment]
![j2me](https://user-images.githubusercontent.com/7092625/63220783-2ebef600-c197-11e9-8bce-a178e643f9ad.png)
```

[10:26:35] <Dacicus> FreeJ2ME running via openjdk-8-jre in Tiny Core
[10:27:47] <Dacicus> Basically that FP setup but with some additional files.
```

The sound doesn't quite work yet so it's a WIP.

**Comment by InfamousKnight** [comment]
Nice. Ill have to try compiling pcem again pretty soon.

**Comment by vadosnaprimer** [comment]
I wasn't able to launch the SDL build of freej2me, but I managed to run the normal build of it in libTAS.

I tried this with ubuntu's openjdk-N-jre, with N from 8 to 17, and they all run. 22 freezes at frame 16. I also tried original java 8 x64 updates [25](http://javadl.sun.com/webapps/download/AutoDL?BundleId=97360) and [31](http://javadl.sun.com/webapps/download/AutoDL?BundleId=101400), the rest don't work.

To make it run in libTAS I needed to enable `clock_gettime() monotonic`, `No waits`, and async `SDL events` on either frame start or end.

"Game" path is _/bin/java_, argument is `-jar /path/to/freej2me.jar file:///path/to/BounceTales_1z8j0.jar`

[freej2me.zip](https://github.com/user-attachments/files/17117884/freej2me.zip)
[BounceTales_1z8j0.zip](https://github.com/user-attachments/files/17117885/BounceTales_1z8j0.zip)

It prints `ERROR (sdl/SDLEventQueue.cpp:319): SDL events sync took too long, were asynchronous events incorrectly enabled?` every frame, inputs don't work, audio is not muted, it's also slow. But at least it runs and pauses.

Can this issue be reopened?

**Comment by TwoSpacesSG** [comment]
A commit leading up to 1.4.8 improved compatibility with JRE/AWT. FreeJ2ME-Plus running in openjdk-25-jre is now successfully hooked and savestated. The downsides are the extremely poor speed of JRE in libTAS highlighted by this kind of thing getting printed into the terminal at a constant basis:
```
[f:8 t:9124] WARN: We detected some softlocks, we fake advancing time for thread 9124 by 0.007000000 seconds
[f:8 t:9126] WARN: We detected some softlocks, we fake advancing time for thread 9126 by 0.007000000 seconds
[f:8 t:9130] WARN: We detected some softlocks, we fake advancing time for thread 9130 by 0.007000000 seconds
[f:8 t:9128] WARN: We detected some softlocks, we fake advancing time for thread 9128 by 0.007000000 seconds
[f:8 t:9111] WARN: We detected some softlocks, we fake advancing time for thread 9111 by 1.000000000 seconds
[f:8 t:9114] WARN: We detected some softlocks, we fake advancing time for thread 9114 by 5.000000000 seconds
[f:8 t:9113] WARN: We detected some softlocks, we fake advancing time for thread 9113 by 5.000000000 seconds
[f:8 t:9112] WARN: We detected some softlocks, we fake advancing time for thread 9112 by 0.250000000 seconds
[f:8 t:9134] WARN: We detected some softlocks, we fake advancing time for thread 9134 by 0.236000000 seconds
```
In addition, ffmpeg captures every frame of freej2me-plus as its own individual video.

Could there way to be a way to improve it, on libTAS's side or on freej2me-plus's side or by refining further the setup? My launch options are as follows:
Game executable: `/usr/lib/jvm/java-25-openjdk-amd64/bin/java`
Command line options: `-XX:ActiveProcessorCount=1 -Dfile.encoding=ISO_8859_1 -jar /home/two/freej2me/freej2me-v1.52/freej2me.jar /home/two/freej2me/glu_d_sony_w200i_en_fr_it_de_es_sonicthehedgehogpartone_v1_0_3.jar 0 128 160 4 0 30`
Working directory: `/home/two/freej2me/freej2me-v1.52`
Prevent writing to disk: On
Other things at default

Edit 1: I tried some settings, the only thing that seems to affect this is that "Always advance time" speeds up the emulator, but at the expense of sync breaking - the timer in libTAS then counts the real time, but the frame counter in the input editor seems to count frames at a slower rate like before. The sync seems to be correct with that setting at default.

Edit 2: I don't know if inputs work. I tried inputting Enter on the language select screen in Sonic 1 Demo but it did not get me past the screen.

**Comment by TwoSpacesSG** [comment]
I repeated this setup with the following software - the latest builds of freej2me-plus, libTAS and Java 26 on the Fedora Workstation distribution inside of a VMware Workstation Pro virtual machine. This time the test subject happened to also be Sonic 1, but it was Sonic 1 Part 1 in the Nokia 240x320 version. I added an `-Xmx128M` argument limiting the heap to 128mb. The fps limit this time was 25, but maybe it should still be 30, idk.

What is vastly improved:
- Speed: the emulator now runs with relatively little "fake advancing" and this leads it to running games at a good speed (not sure if there is a lot of gain on fast forward but whatever).

What stayed the same:
- Keyboard input still doesn't work. I couldn't test controller input which got recently introduced to freej2me-plus, it might work in theory but it sure shouldn't be the play because not everyone has a controller.
- ffmpeg still seems to capture every frame of freej2me-plus as an individual video. I couldn't get the ffmpeg from the libTAS appimage to work though, maybe i'm doing something wrong.

This is promising however because there seems to be some kind of determinism at the default "advance time on the main thread" setting although i can't check it for certain because of no inputs. Would it be possible to see at least if there would be a way to hook up keyboard inputs?

**Comment by vadosnaprimer** [comment]
Biggest question is savestates. Also I recommend trying different Java versions, there's some variety in which of them work better.

**Comment by TwoSpacesSG** [comment]
Savestating still works fine. I saved on the Sega intro, let the game play to the language select screen, loaded the state, the screen didn't immediately refresh, but it did when going to the next frame, i was on the Sega intro again. It's worth mentioning that there is now a warning that wasn't there before that says: `WARN: Skip saving incomplete pipe (fd=3,-1)` but i don't know what exactly it affects. Sorry that i forgot to test savestating yesterday.

**Comment by TwoSpacesSG** [comment]
I tested some more JRE versions in conjunction with freej2me-plus. Latest Java 6 and earlier are not hooked by libTAS and proceed as if nothing happened. First Java 7 is the first version in which the inputs don't work. There don't seem to be any lucky versions. Also almost the entire line of the Linux JRE 7 (specifically Linux) and some early 8 don't display graphics in freej2me-plus, i don't know what kind of long-lasting regression that is lol.
