### ISSUE TITLE
Add an option to hide the message when loading a non-existing savestate

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#16]

**Comment by clementgallet** [comment]
The improvement that I'm thinking about is to print those kind of messages directly on the game screen, so we don't have the annoying dialog boxes.

**Comment by clementgallet** [comment]
Implementing the display of messages on the game screen, so that the alert window does not show anymore (04d1a690dd05565b4a28d5d6b7c5f2119a07e63b)
