### ISSUE TITLE
Data are placed under $HOME in the hidden dir .libtas

### ISSUE THREAD

**Issue by YoshiRulz** [clementgallet/libTAS#165]
Please keep `$HOME` clean by calculating paths from env vars as per the [*XDG Base Directory* spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by clementgallet** [comment]
Changed in 8515a001339c9fa327e9500a71ff1d9f1993e5cd, thanks for the advice.
