### ISSUE TITLE
Segmentation fault(core dumped) on opening

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#168]
With the new release, if I run the program, a segmentation fault occurs.

I DID delete .libtas before installing, so that might have made a difference. Installing latest interim gives same result.

Running ubuntu 18.04.1 64-bit

**Comment by Noahkiq** [comment]
can reproduce

**Comment by Noahkiq** [comment]
quick bisect shows seg fault is being caused by 8515a00

**Comment by clementgallet** [comment]
Yes, `getenv` can return null and building a std::string from null is not allowed. Fixed in 5ca20a59239bc1852df5d410ca043ca6a5ea8283

**Comment by Noahkiq** [comment]
should probably rerelease 1.3.3 with this fix ;p

**Comment by clementgallet** [comment]
Yes, I updated the compiled files

**Comment by vadosnaprimer** [comment]
Might be also worth an extra forum post telling to redownload.

**Comment by clementgallet** [comment]
Done.
