### ISSUE TITLE
mame doesn't save full config?

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#169]
So with mame, 1 issue was fixed: you can have opengl renderer with osd fixed, one problem not fixed, is that you can't seem to save ALL settings.. Like if I enable windowed mode, it will save that fine. Then if I disable all fn keys, those won't save. What also is a little weird, is osd is broken until you reset.

I also disabled backup save files in memory, as it looks like I have to do it in libtas for some reason. Idk

**Comment by InfamousKnight** [comment]
Is anyone else having this problem?

**Comment by clementgallet** [comment]
I'm getting the correct behavior:
* If I disable "backup save files in memory", I change an input mapping in mame and save the config, it will effectively be saved
* If I enable "backup save files in memory", I change an input mapping in mame and save the config, it won't be saved

About the windowed mode, because libTAS enforces a windowed mode, I'm not sure it's the right setting to test.

**Comment by InfamousKnight** [comment]
Do you config it through libtas or natively? Natively the settings are there, but when I run it through libtas, the settings are reset.. and I did disable backup saves files in memory.

I agree. The name should be changed. Maybe allow reading and writing files?

**Comment by clementgallet** [comment]
I'm doing everything in libtas, yes.

**Comment by vadosnaprimer** [comment]
"Allow writing to disk"?

**Comment by InfamousKnight** [comment]
I'm currently running into another problem. Doing all the configs in libtas with aforementioned settings worked, but I can't seem to load roms.. What I did was create a folder called mame on the home directory and put a folder called roms and put my rom there tgoldeye and it works natively with mame but not with libtas. It will crash with got unknown message claiming the file doesn't exist..  I didn't touch any of the configs regarding file directory, so I don't know. I did have to go into root to run mame through libtas though. Running ubuntu 18.04.1 64-bit.

**Comment by clementgallet** [comment]
Can I have more details on how do you launch the rom? Are you using `mame rom_name` command (with just the rom name or the path to the rom?) or are you running `mame` and choosing the rom in the list using mame's GUI? Same question when launching through libTAS. libTAS changes the current directory by default to the directory of the executable, so it might be the reason.

Also, I'm not sure about your last sentence. Are you running mame from root directory `/` or are you running through with root user `sudo mame`?

**Comment by InfamousKnight** [comment]
I’m running mame rom_name. I didn’t know you could open roms through GUI. For root I just su - then root password and run libtas interim.

So in executable file I have mame in usr/games and tgoldeye in command line options

**Comment by clementgallet** [comment]
I advise not to run libTAS through root. It is unnecessary and potentially dangerous.
When you run mame natively, are you running it from inside the rom directory? Or does it work from any directory? I suggest you configure the rom directory in mame.

**Comment by InfamousKnight** [comment]
Well, I can’t seem to write anything to usr/games because I don’t have permission it says. That’s why I ran it through root. 

Anyway around that?

**Comment by clementgallet** [comment]
You shouldn't need to write to `/usr/games/`. If you want to record a movie (or encode a video), just change the path.

**Comment by InfamousKnight** [comment]
Alright thanks. Works now

**Comment by vadosnaprimer** [comment]
So what are your steps to make it work now, from scratch?

**Comment by InfamousKnight** [comment]
Install mame
Install libtas
Make a folder called mame in your home directory. Make another folder in mame called roms and put your roms there
Run mame through libtas
In libtas runtime - allow writing to disk is disabled
While running mame, go under configure machine and inputs and delete all fn keys using the esc key. Press enter on the fn key and press esc

You can also set windowed mode too. The osd will become garbled at first but once you restart the program it will fix up

When making a movie, set the movie path somewhere else. Same thing with the encode. You don’t have permission to write to usr/games

**Comment by vadosnaprimer** [comment]
They just use this dir as default, and apparently it doesn't exist, this is why my guide told to create it. If we're changing the ROMs path, of course it could be anything else.
