### ISSUE TITLE
[Feature] Input editor should show an extra frame at the end of the movie in playback mode

### ISSUE THREAD

**Issue by BenLubar** [clementgallet/libTAS#170]
This would allow two things:

1. Inserting a frame at the end that requires an input that cannot be entered on actual hardware (for example, due to keyboard ghosting)
2. Pasting inputs at the end of a movie.

**Comment by clementgallet** [comment]
This was easier than I thought (446fdb2cdc44fcb6b7a28007f2dbaba7846cf5c7).
