### ISSUE TITLE
Deltarune hangs on startup

### ISSUE THREAD

**Issue by LucasWills** [clementgallet/libTAS#172]
Deltarune starts, and runs fine for 180 frames, then freezes on frame 181. This is the same frame that "SURVEY_PROGRAM" changes to "DELTARUNE". Deltarune runs fine outside of libTAS. I am using the port of Deltarune from here: https://www.reddit.com/r/Deltarune/comments/9wizh3/deltarune_running_on_linux_natively/

**Comment by Noahkiq** [comment]
are you using the required settings to make GM:S work?

![image](https://user-images.githubusercontent.com/13265322/52475351-3f980a80-2b69-11e9-949d-3c75b9a26e7a.png)

**Comment by LucasWills** [comment]
That fixed it. Thanks.
