### ISSUE TITLE
Unable to capture encode with dosbox-x

### ISSUE THREAD

**Issue by micro500** [clementgallet/libTAS#177]
I am unable to create an encode with dosbox-x. In the console I get these errors several times:
```
[nut @ 0x5555557d7a60] No main startcode found.
pipe:: Invalid data found when processing input
```
Other games (ex: Mari0) capture fine, as well as vanilla dosbox. 

For testing I am running dosbox-x with no config/autoexec, just starting the program. I built dosbox-x from [source](https://github.com/joncampbell123/dosbox-x) using SDL2. 

For encode settings I am using the settings from [here](http://tasvideos.org/EncodingGuide/VideoDumping.html#Libtas):
File extension is .avi. 
Video codec: H.264 RGB
Audio codec: PCM signed 16-bit little-endian
Video bitrate: 4000
Audio bitrate: 128
ffmpeg options: -c:v libx264rgb -qp 0 -preset ultrafast -g 1 -pix_fmt rgb24 -context 1 -c:a pcm_s16le

I am running this all on Ubuntu 18.04 in a virtualbox VM.

**Comment by clementgallet** [comment]
Can reproduce. dosbox-x with SDL2 uses the obsolete way of rendering on screen (using SDL_UpdateWindowSurface() which is a left-over from SDL1 SDL_Flip()). This way of updating the screen is not hooked by libtas.

**Comment by vadosnaprimer** [comment]
They might consider upgrading this part maybe? @micro500 seems to make sense to just ask them.

**Comment by clementgallet** [comment]
I should implement this anyway, it shouldn't be much work. For them, it is a bit of work to move to SDL2 renderers, but it has the advantage of getting hardware-accelerated surfaces/textures if available.

**Comment by clementgallet** [comment]
Implemented in 1b8e116efa7633522abe0a77a0afe2798f9989f1

**Comment by micro500** [comment]
Video encoding works now. Thanks for the quick fix!

**Comment by InfamousKnight** [comment]
I’ve had trouble just running dosbox-x.. could you explain what you did?

**Comment by micro500** [comment]
Nothing special, dosbox-x worked fine for me besides video encode recording. In the near future I am going to be writing up a guide on how I got everything set up for running Windows 95 through libtas. Maybe that guide will help you. Otherwise, what issues were you having?

**Comment by InfamousKnight** [comment]
I was having trouble just opening the program. Looked at the readme file and tried compiling and nothing but errors. I’m at work right now without my laptop so I’ll have to wait til I get back home to seen error messages. 

But a guide to run win95 will be nice.

**Comment by micro500** [comment]
I followed the building steps in the README.md, but the configure step complained about not finding SDL. I found that I had to add --enable-sdl2. So my build steps looked something like:

```
./autogen.sh
./configure --enable-sdl2
make
```

I'll finalize all the steps I followed in my guide.

**Comment by InfamousKnight** [comment]
I'm receiving an error on make:
make  all-recursive
make[1]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)'
Making all in src
make[2]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)/src'
Making all in cpu
make[3]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu'
Making all in core_full
make[4]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu/core_full'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu/core_full'
Making all in core_normal
make[4]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu/core_normal'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu/core_normal'
make[4]: Entering directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu'
depbase=`echo callback.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL2 -D_REENTRANT -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include/SDL  -g -std=gnu++11  -O2 -msse  -Wall   -Wextra   -pedantic   -Wconversion-null   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast   -Wno-extended-offsetof  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include/SDL  -MT callback.o -MD -MP -MF $depbase.Tpo -c -o callback.o callback.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL2 -D_REENTRANT -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include/SDL  -g -std=gnu++11  -O2 -msse  -Wall   -Wextra   -pedantic   -Wconversion-null   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast   -Wno-extended-offsetof  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include -I/home/seab/Downloads/dosbox-x-master (1)/vs2015/sdlnet/linux-host/include/SDL  -MT callback.o -MD -MP -MF $depbase.Tpo -c -o callback.o callback.cpp &&\'
Makefile:423: recipe for target 'callback.o' failed
make[4]: *** [callback.o] Error 1
make[4]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu'
Makefile:445: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)/src/cpu'
Makefile:522: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)/src'
Makefile:391: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/seab/Downloads/dosbox-x-master (1)'
Makefile:328: recipe for target 'all' failed
make: *** [all] Error 2

my real name is sean, its just I didnt feel like looking into changing it.

**Comment by clementgallet** [comment]
Remove the parentheses on the folder name.

**Comment by InfamousKnight** [comment]
Did that and got a new error:

sdlmain_linux.cpp:14:10: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:422: recipe for target 'sdlmain_linux.o' failed
make[3]: *** [sdlmain_linux.o] Error 1
make[3]: Leaving directory '/home/seab/Downloads/dosbox-x-master/src/gui'
Makefile:522: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/seab/Downloads/dosbox-x-master/src'
Makefile:391: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/seab/Downloads/dosbox-x-master'
Makefile:328: recipe for target 'all' failed
make: *** [all] Error 2


Should I tell dosbox-x about it?

**Comment by micro500** [comment]
You need xorg-dev. I already submitted an issue for that [here](https://github.com/joncampbell123/dosbox-x/issues/1014)

**Comment by clementgallet** [comment]
I needed to install `libxkbfile-dev` for that specific error.

**Comment by micro500** [comment]
Looks like that package was enough for me to build as well. I'll update the dosbox-x issue.

**Comment by InfamousKnight** [comment]
I guess I managed to install it.. where's the executable at?

**Comment by clementgallet** [comment]
In `src/dosbos-x`

**Comment by InfamousKnight** [comment]
And do you load roms the same way you load them in vanilla dosbox? I'm testing out destruction derby 2
