### ISSUE TITLE
Interim indication

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#178]
Please add some indication when the build one is using is an interim, ideally reporting the commit it's built against. _Ideally_, in a way that'd allow to copy the commit hash, since in git typing commits by hand isn't feasible.

**Comment by clementgallet** [comment]
Added "interim $commit" in the main libTAS window title (4ac1d490fd63cf5ceeb91939ecf3e943ad91f75e)

**Comment by vadosnaprimer** [comment]
Oh I know how to make it easy to copy: just print the release/interim/commit to the shell.

**Comment by clementgallet** [comment]
Add git commit hash for local builds, print commit on terminal and rename appveyor output file (67c3d7719dc81ea8ea94037d08e9a57a9518ebef)

**Comment by vadosnaprimer** [comment]
Will check soon. While we're here, I think it's worth it to link to the always-latest dev build in the readme now:
https://ci.appveyor.com/project/clementgallet/libtas/build/artifacts

**Comment by clementgallet** [comment]
> Also while we're here, I think it's worth it to link to the always-latest dev build in the readme now:
> https://ci.appveyor.com/project/clementgallet/libtas/build/artifacts

Oh. I thought this page was only available when logged in. We don't really need the github pre-release then, considering that there are still problems (tag doesn't update, release files are not overwritten because the name is different each time).

**Comment by clementgallet** [comment]
I added the build date for interim versions, removed the appveyor deploy on github but added the link in the readme (862ebe922975182ca4facd5f43e481c4ec077769)

**Comment by vadosnaprimer** [comment]
I just made sure the shortened commit hash gets properly resolved if you just make a github link, so I think this doesn't need to be tweaked any further. Thanks!
