### ISSUE TITLE
Disable scrolling Input Editor to the current frame

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#182]
When I'm just editing input at some frame and checking quickly if it worked the way I wanted, I'd really prefer to be able to make the view **not scroll** upon unpause. I would edit, unpause, watch until some random frame, load the state in replay mode, edit again, unpause, etc. When the view is scrolling all the time, it's constantly changing the original scroll position that's comfortable for editing. TASEditor and TAStudio call this option "Follow cursor", which means "follow the current frame with the view scroll".

Also, this option is turned on and off very frequently, and in TAStudio is conveniently shows the current frame whenever you tick it. Don't know if it's feasible via GUI, but at least a hotkey would be **really** helpful.

**Comment by clementgallet** [comment]
Not exactly what you asked for, but in 92e78a2fb42e7eb0af1c597f86cc32f2102ed14d, when the user manually scrolls the input editor, it doesn't autoscroll on frame advance anymore, until the current frame is outside the visible frames.

Also, I changed the autoscroll current frame position, from centered to a quarter of the visible frames.
