### ISSUE TITLE
Drag-Painting analog input in input editor

### ISSUE THREAD

**Issue by micro500** [clementgallet/libTAS#183]
In the input editor you can currently click and drag on any binary key input to fill that input in for other frames. It would be nice to be able to do the same thing for analog inputs.

**Comment by vadosnaprimer** [comment]
Note: for analog it'd have to use whatever value you've clicked on at the start of dragging, as a base value to draw it. Click on blank, don't release the mouse button, drag the pointer - you're drawing blank. Click on 10 and drag, you're drawing 10. Click on 400, draw 400.

**Comment by clementgallet** [comment]
Implemented in 7db559f3f47cc33328d77c0ce5cf1e9b6aa7c543
