### ISSUE TITLE
Dosbox-x desyncs

### ISSUE THREAD

**Issue by micro500** [clementgallet/libTAS#184]
I am experiencing frequent desyncs in dosbox-x if I replay my TAS from the beginning. I'm not sure if this has to do with running Windows95 in dosbox-x so I may need to test more. It seems like when working with savestates playback usually works from that savestate, but restarting from the beginning the movie does not play correctly. 

I'm not sure if it is related, but the OSD freezes at somewhat consistent points like during win95 bootup. The OSD frame counter usually freezes at 391 or 392 (@60fps), but that frozen frame number changes between those two if I restart movie playback from the beginning a few times.

Another possibly related freeze is when the autoexec command `boot -l c` is run. The OSD frame counter freezes at 37, and libTAS freezes at 60. libTAS stays frozen for around 5-10 seconds, then everything continues fine.

I realize this is a complicated setup (installing/running win95 in dosbox-x) and that it might not be the easiest thing to recreate and try to reproduce my issue. What can I do to provide more info to help solve the desync issues?

**Comment by InfamousKnight** [comment]
I would imagine its windows 95 itself causing desyncs. Are the desyncs rng related?

**Comment by micro500** [comment]
They don't seem RNG related. For example I was messing with just drawing in paint, but I started by maximizing the window. Sometimes when I played back that movie it wouldn't maximize the paint window, sometimes it would.

**Comment by iamgreaser** [comment]
Part of me is thinking it's disk access related.

Having said that... have you made sure that DOSBox-X always uses a fixed number of cycles?

**Comment by micro500** [comment]
I was also wondering if it is disk access related. The game I ultimately want to TAS in win95 uses a CD which I have mounted from an iso on ide 2 in dosbox-x. I see messages in the log from dosbox accessing the CD.

I have cycles set to fixed 15000. Other settings I changed for dosbox were:
sblaster to sb16vibra
autolock=true

For libTAS I set Runtime -> Time tracking -> Main thread -> SDL_GetTicks() as suggested [here](http://tasvideos.org/forum/viewtopic.php?p=475832#475832)

I have tried turning on the new Asynchronous Events checkbox in libTAS, and I tried turning off Increment Savestates, but I still had desyncs.

**Comment by clementgallet** [comment]
About the frozen OSD, it is (likely) because the program is not updating the screen, but is doing some sleeps. To compensate for the time passed, libTAS is triggering extra frames, but because the program did not draw, we cannot draw on screen because it would break on some setups (OpenGL mainly, swapping the buffers is not always valid). I could try to draw for the cases where it would work (software rendering mainly).

Dosbos-x is working by increments of 1 ms. Could you try recording at 1000 fps so that the framerate matches the program behavior? Also, you can disable the time tracking stuff if you don't have any freezes without it, but it shouldn't trigger desyncs anyway.

Events seem to be queried by the main thread, so Asynchronous Events is not needed.

**Comment by micro500** [comment]
Unfortunately recording at 1000 fps did not fix the desyncs. 

While trying to debug this myself I found that the windows boot screen was cleared and the OSD froze at either 6492 or 6507. This lead me to make this quick modification to libTAS:
```
index 04f9c8f..6089356 100644
--- a/src/program/GameLoop.cpp
+++ b/src/program/GameLoop.cpp
@@ -200,6 +200,7 @@ void GameLoop::start()
         }
 
         emit startFrameBoundary();
+        std::cout << "frame " << context->framecount << std::endl;
 
         /* We are at a frame boundary */
         /* If we did not yet receive the game window id, just make the game running */
```

I then ran dosbox-x through libTAS until I got a log of both instances. For this test I set libTAS to pause at 6480, then manually frame advanced to 6507 so I could watch to see when the screen was cleared.

[Screen cleared on 6492](https://github.com/clementgallet/libTAS/files/2875961/out_6492.txt)
[Screen cleared on 6507](https://github.com/clementgallet/libTAS/files/2875962/out_6507.TXT)

There were two differences that occurred on the same frame:
```
Frame 144:
6492:
LOG: X11 main window is 640 x 400 maximized=0
6507:
LOG: X11 main window is 640 x 497 maximized=0
```
```
Frame 1000:
6492:
LOG: X11 main window is 720 x 417 maximized=0
6507:
LOG: X11 main window is 640 x 497 maximized=0
```

Then starting at frame 3156 the log messages diverge and the 6507 version is behind the 6492 version. However the length of time between matching log messages seems to vary.

From the log messages I realized I am running on the dynamic core, or rather core is set to auto which defaulted to the dynamic core, but later switched to the normal core. I am going to try switching exclusively to the normal core to see if that makes a difference.

**Comment by micro500** [comment]
I tried switching to the normal core only but I didn't see a difference. 

I tested allowing writing to disk. I noticed the freezing at dosbox startup (previously at frame 60) didn't happen. Unfortunately I messed up backing up my win95 disk image, so now things run slightly differently, but I am still experiencing similar variance in the log outputs, and similar screen clearing on the same two frames.

I changed the dosbox settings to output more debug messages. Here are more logs to look at:

[Debug 6492](https://github.com/clementgallet/libTAS/files/2876252/out_debug_6492.txt)
[Debug 6507](https://github.com/clementgallet/libTAS/files/2876251/out_debug_6507.txt)

I noticed that on similar messages the dosbox cycle count (?) preceding the log message doesn't match. 

What should I try next?

**Comment by InfamousKnight** [comment]
Mame can run Windows 95. Try that out.

**Comment by vadosnaprimer** [comment]
Don't try that, it's a nightmare and it doesn't fully work.

**Comment by InfamousKnight** [comment]
Have you tried pcem?

**Comment by micro500** [comment]
I'm actually in the middle of trying that now. I got win95 installed and working. I'll report back after I've done some more testing.

**Comment by clementgallet** [comment]
Work has been done on PCem (#208), so closing here.
