### ISSUE TITLE
New fullscreen behavior isn't very good for INK

### ISSUE THREAD

**Issue by Noahkiq** [clementgallet/libTAS#189]
crappy title but screenshot should explain it
![image](https://user-images.githubusercontent.com/13265322/53295636-a22a1100-37cd-11e9-91c4-746075f78fcb.png)
(also note the frame count is missing)
(other resolutions share the same issue of having a large window but the game doesn't resize)

**Comment by clementgallet** [comment]
Sorry, I should have tested this game. I unfilter ConfigureNotify event so that games receive the resolution change notification (1b3f0af19c30b8cd98e328b5b2df4261235feecd). Now you correctly get the game in "fullscreen windowed" mode (or whatever virtual screen size you choose).
