### ISSUE TITLE
Running anbox on linux

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#191]
This should be less complex than wine is. It's a capability layer for android.

So does anyone want to look into this?

**Comment by Noahkiq** [comment]
have you tested it?

**Comment by InfamousKnight** [comment]
Not yet. I'm still at work and I won't be free until Thursday.. I'll test it then. You need an android device for this(which I have)

**Comment by InfamousKnight** [comment]
Running it natively opens 2 windows. For the app manager and the app itself. Because Libtas doesn't support multiple windows, this simply won't work.

**Comment by clementgallet** [comment]
The project is running the Android system inside the host OS, so it is unlikely libTAS will be suited for that.
