### ISSUE TITLE
Video checkmarks

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#193]
For some reason, the linux version of ppsspp doesn't support video checkmarks anymore.

To be more specific, when making a save state, video pipe to closed and a new one is made for a separate video. When loading the save state, the new video file is deleted and replaced. So for instance:
N = 0
Start encode
It makes video[N]
Make save state
It closes video[N] adds 1 to N and makes video[N] again
Load save state
Close video[N] and make video[N]

What's more, ppsspp has encoding problems and I've already tried to address that with them and they ignored. Libtas doesn't have those issues with ppsspp. So this could be a temporary fix. No movie file to verify, but good for YouTube videos. 

Simple enough?

**Comment by clementgallet** [comment]
I'm not sure people would use libTAS for casual play, given the overhead of the tool and it not being particular user-friendly. Also, given how many opened issues there are on PPSSPP repository, I wouldn't say they ignored you. They may have higher priority issues to deal with, or maybe this is a complex problem to fix.

**Comment by InfamousKnight** [comment]
First of all, this is not for casual play. It's a workaround for the sync issues with ppsspp. Somehow libtas has better encoding than ppsspp does. Do you remember when bisquit(sorry if that's spelled wrong), used ld preload to make the chrono cross tas? Like before ps1 tasing was available? That's what I'm referring to.

**Comment by clementgallet** [comment]
Oh, you mean you suggest that libTAS implements video checkmarks? Well, no that not a simple task, because savestates would alter the communication with ffmpeg. Also, I don't really want to work on workarounds for a situation that needs a proper fix.

**Comment by InfamousKnight** [comment]
Yeah, thanks for looking into it again. I'm surprised I'm the only one expressing disappointment. The issue seems very similar to the amiga problem. I'm sure theres hope.
