### ISSUE TITLE
Renamed label resets upon state load

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#195]
If I start movie recording, open input editor, change a column label, and then load a state, the label name will be restored to what it was before renaming, and the column width will remain what it was after renaming. I think the proper way would be saving new labels in the movie in some way, otherwise it'd be quite hard to make use of label renames.

**Comment by clementgallet** [comment]
Oh yeah. The actual plan was to save renamed labels in the game specific configuration file, but I got distracted.

**Comment by vadosnaprimer** [comment]
As a default value for new movies it makes sense to store this in game-wise config, though I think the perfect solution would include saving it per-movie as well.

**Comment by clementgallet** [comment]
Ok, I stored them in movies then (0cc61b5de539766ea04f71ed5923c0388723dc3e)

**Comment by vadosnaprimer** [comment]
If I rename a mouse coord column to a single letter, upon state load the width becomes too narrow and doesn't show more than 2 digit coord values. It shows 1 or 2 digits, but when the value is 3 digits, it just shows "...".

**Comment by clementgallet** [comment]
I added a minimum column size for analog inputs, it should now be able to display 6 characters. Also, I added column resizing when loading states (97324836b9b86cc79a9ff16b90acf2d34acf281b)

**Comment by vadosnaprimer** [comment]
Sorry I didn't have time to test it. If it happens again I'll call back.

**Comment by vadosnaprimer** [comment]
Okay yes, seems to be fixed, thanks!
