### ISSUE TITLE
Input editor hotkeys

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#196]
Input editor has internal editing functions that are only accessible from the context menu. Please add global libTAS hotkeys for them. Other input editors have accelerators for those, but this means they can't be changed, so configurable hotkeys would be better.

**Comment by clementgallet** [comment]
I will start with default hotkeys. Eventually, the input editor will have its own interface (menus are/or side options). Did I already say I hate working on the GUI?

**Comment by clementgallet** [comment]
Added shortcuts to most input editor options (8253850fc0d6c131e06ee0f196037d68ea75e328)

**Comment by vadosnaprimer** [comment]
Finally tested.` Ctrl+` doesn't insert anything if it's pressed right after `Ctrl-`, you have to click somewhere with the mouse (even if on the same row where selection already is) for it to insert a frame.

**Comment by clementgallet** [comment]
Fixed in 911ebd00be2279d7709b85e483cfe971a246a839

**Comment by vadosnaprimer** [comment]
Tested. Now Ctrl++ hotkey doesn't work at all, only the menu command does.

**Comment by clementgallet** [comment]
Really? That is odd, I didn't change anything. It is working fine for me.

**Comment by vadosnaprimer** [comment]
Maybe xubuntu is to blame. I'll test on another distro.

**Comment by clementgallet** [comment]
Nobody else reported that kind of problem. Also, while I added the menu bar, I fixed an issue where if you would select a frame before current frame, and move down the selection with arrow key to a frame after current frame, it would not update the actions and would prevent you from adding frames (1ad9949efce45040c124e0e628603c5b38611677). So maybe it's doing fine for you?

**Comment by vadosnaprimer** [comment]
Dunno when I test it, so I'll close it for now. Thanks!
