### ISSUE TITLE
Grand theft audio crashes after splash screen

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#198]
As far as I know, this wasn't a problem before. What happens is it crashes after it says author name thats mimicking rockstar games. This seemed like an interesting game to tas given its physics engine.

**Comment by clementgallet** [comment]
Could you check with "Recycle threads" unchecked?

**Comment by InfamousKnight** [comment]
Thank you. That fixed it.

**Comment by InfamousKnight** [comment]
Also, the game runs super slow in libtas, is there anything that can be done about that? It runs fine natively.

**Comment by Noahkiq** [comment]
libtas uses software rendering which is very slow compared to native hardware rendering. try some of the performance flags, they may help
![image](https://user-images.githubusercontent.com/13265322/55279212-70382d00-52ec-11e9-9ce3-13efc7e87a44.png)

**Comment by clementgallet** [comment]
If you are using a VM, increase the number of threads allocated to the VM to the highest value, because the OpenGL software driver is highly multi-threaded . Also, you can try to lower the game resolution.

**Comment by InfamousKnight** [comment]
I'm using a native machine.

**Comment by Noahkiq** [comment]
libTAS can't do anything besides give you the option to enable performance options, as the software rendering is done via another program (llvmpipe, iirc?)
