### ISSUE TITLE
The tool asks whether to reload a previous game iteration even when though it isn't possible

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#201]
This is when trying to load a previous save state

**Comment by clementgallet** [comment]
It asks to load the movie associated with a previous savestate. This is useful if someone had a crash and didn't save, they can still load the savestate movies. I modified a bit this option so that it only offers the choice if loading the movie is possible (1464f8111aa259c1157c3609b34fbd13bf2c2f42)

**Comment by Noahkiq** [comment]
yeah he just meant libTAS would ask to load the state even if you had differing inputs

**Comment by clementgallet** [comment]
Oh, ok, I didn't read it correctly, sorry. So I just fixed the issue then!
