### ISSUE TITLE
PCem freezes on startup

### ISSUE THREAD

**Issue by slamotas** [clementgallet/libTAS#202]
Using PCem v14: https://pcem-emulator.co.uk/
I'm using "--config /path/to/config.cfg" to skip the config selection screen.

The game windows pops up and doesn't advance past frame 0. I'm using uncontrolled time until I can figure out for sure which time tracking options to check. There aren't any error messages so I'm not sure what the problem is. I've tried all sorts of runtime options as well. Here is the output from gdb, if it helps:

`Starting program: /home/mark/pcem14/pcem --config \"/home/mark/.pcem/configs/DOS.cfg\"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Attempt 1: Couldn't connect to socket.
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Connected.
[New Thread 0x7fffe6cba700 (LWP 6552)]
Set fullspeed - 0 0 0
[New Thread 0x7fffdddbe700 (LWP 6553)]
[New Thread 0x7fffdd5bd700 (LWP 6554)]
[New Thread 0x7fffd2bff700 (LWP 6555)]
[New Thread 0x7fffd23fe700 (LWP 6556)]
Menu item not found: 1403
Menu item not found: 1404
[libTAS f:0] Thread 6547 (main) OpenGL vendor: VMware, Inc.
[libTAS f:0] Thread 6547 (main) OpenGL renderer: llvmpipe (LLVM 6.0, 128 bits)
[New Thread 0x7fffcb98b700 (LWP 6557)]
[New Thread 0x7fffcb18a700 (LWP 6558)]
Menu item not found: 1403
Menu item not found: 1404
`

The "Menu item not found" lines are fine, they are there without libTAS and PCem still works.

I know this isn't much to go off of, and PCem is a bit of a task to set up. If there's any way I can get you more information please let me know.

**Comment by InfamousKnight** [comment]
Wow, I didn't know this works with linux. I recall someone running windows Longhorn  with this.

**Comment by clementgallet** [comment]
The problem is that PCem is using multiple threads, including a rendering thread. libTAS can reconsider its identification of the main thread as the one that is doing the rendering, but in the case of PCem, it doesn't get the chance to render once.

By adding `ThreadManager::setMainThread();` inside `SDL_CreateWindow()`, the main thread is set to the correct thread, and PCem runs correctly (without any time tracking stuff). I'll probably make that an option, even if it will be another confusing GUI option. I should also add warning messages when a game/program is doing important stuff on other threads, so that it can help debugging.

**Comment by InfamousKnight** [comment]
Wow, and it was fixed that fast too. Took a look at the capability page with this and it's much better than dosbox.

Are you planning on writing a guide to set this up?

**Comment by slamotas** [comment]
I'll probably write a guide on the forums at some point.

**Comment by vadosnaprimer** [comment]
If it works, rerecords, and syncs, that's be absolutely insane!

**Comment by clementgallet** [comment]
I changed this without an option actually (66579924030cec332663915f245425e8d53852c7). Could this break other games? At least, there is now a warning when the main thread has changed, so that problematic games can be identified more quickly.

**Comment by slamotas** [comment]
Seems like it will load the default (8088) BIOS with "Recycle threads" checked but I needed to uncheck it for my DOS/Windows setup. I will have to do some testing for determinism, but it works! Thank you!
