### ISSUE TITLE
appveyor/interims failing

### ISSUE THREAD

**Issue by noellekiq** [clementgallet/libTAS#203]
looks like the lack of interim release is causing it to abort and not upload the artifacts

![image](https://user-images.githubusercontent.com/13265322/55292622-1488a500-53bb-11e9-80fb-7288b477153d.png)

![image](https://user-images.githubusercontent.com/13265322/55292626-223e2a80-53bb-11e9-90bd-96ee4e1fa998.png)

**Comment by clementgallet** [comment]
I noticed that, but I don't understand why it stopped working.

**Comment by clementgallet** [comment]
Fix by removing the tilde (d3852441cbb1a2f54740158abe5db47dbe258695). Also fix the debian package and appveyor config to include the i386 lib in amd64 build (151a212ae92f6285043f917f659fc556c3f936e9)
