### ISSUE TITLE
Provide option to allow a game to save its own data

### ISSUE THREAD

**Issue by Danfun64** [clementgallet/libTAS#207]
While this program is an impressive technical achievement, I would have liked to have used this program like I would use the average emulator: let me create save states but still allow a game to create save data of its own. Unfortunately, this program runs on the same "record from the very beginning, you can't save SRAM" logic that lsnes and JPC-RR use. While I understand that persistent save states aren't possible due to the nature of this program, I would still appreciate it if there was an option for both save states and the game creating/updating save data.

I know that in many ways this request is the opposite of #5 . I'm not asking you to completely reverse the behavior: just to add a switch between recording replays and writing save data.

**Comment by jacobly0** [comment]
This sounds exactly like the `Runtime` &rightarrow; `Prevent writing to disk` option, unless I am misunderstanding the issue.

**Comment by Danfun64** [comment]
I just shut my computer off. I'll check if you're right in the morning. If
so, I apologise in advance for the frivolous feature request report.

**Comment by Danfun64** [comment]
Yep, "Prevent writing to disk" was turned on. I should have been paying more attention to the menus.
