### ISSUE TITLE
Determinism in PCem

### ISSUE THREAD

**Issue by slamotas** [clementgallet/libTAS#208]
As I feared, there are some desyncing issues with PCem.

Here are the files for the setup I'm using (all of this is legal to distribute): 
[pcemdos.tar.gz](https://github.com/clementgallet/libTAS/files/3045198/pcemdos.tar.gz)

- floppy.img: A FreeDOS boot floppy image. This is the same one that comes with JPC-rr.
- realms.img: A small hard drive image with the shareware version of Realms of Chaos.
- dos.cfg: Config file for PCem, you will have to change the paths of floppy.img and realms.img.
- pcem.ltm: A simple unassisted movie I recorded to test determinism.

I should also note that "Recycle threads" must be unchecked to run this.

You'll need some BIOS files to run this, which obviously I can't link to, but a complete pack of them is easy enough to find. When you press DEL to enter the BIOS this is what the first two config screens look like for me (ignore the time/date):

![Screenshot from 2019-04-04 15-49-26](https://user-images.githubusercontent.com/43973120/55584220-bf69cd80-56f1-11e9-990f-82e5948bf88d.png)

![Screenshot from 2019-04-04 15-53-34](https://user-images.githubusercontent.com/43973120/55584285-de685f80-56f1-11e9-8520-4df7e85306bc.png)

I feel like this is a decent game for testing because there are some loading screens and then the gameplay is laden with random events (enemy spawn locations and item drops). The loading times seem to fluctuate by a few frames every time in my movie.

I'm not sure if the RNG is consistent yet since the gameplay starts on different frames every time. PCem seems to accept the time libTAS feeds it, but the BIOS time defaults to 1/1/97 if the system time is set too low (this is probably just a quirk of the BIOS). The BIOS actually has a minimum date of 1/1/94, and it seems to accept certain system times above this (it adjusts them to GMT -5), but if the system time is set too high, PCem boots but doesn't accept any inputs for some reason.

PCem internally increments 1 ms at a time. I've tried recording some tests at 1000 fps, but it doesn't seem to help determinism.

If there's other information you need or if I can help in any way, let me know.

**Comment by InfamousKnight** [comment]
Yeah, dont get too excited.. we fixed ppsspp and amiga so we can fix this one too I'm sure. Theres a graphical issue with ppsspp for now, but that's a different story.

**Comment by vadosnaprimer** [comment]
"We" didn't fix anything, keylie did.

**Comment by clementgallet** [comment]
Thanks for providing all the files. I could install everything and run. I will look at it.

**Comment by clementgallet** [comment]
As expected, this is a problem of the rendering thread and the emulation thread running independently. I've made a [patch](https://gist.github.com/clementgallet/bcacc3434e353dc11671336a9477bebc) to add synchronization between the two threads. To apply the patch, download it inside PCem v14 directory, then open a terminal, go inside that directory and enter `patch -p1 < pcem_sync.patch`.

PCem's emulation thread does one emulation step every 10 ms, and I've locked each emulation step to a screen draw, so you must set a framerate of 100 fps in libTAS.

From my initial testing, the game launches at the same frame every time now. But many things can still go wrong.

**Comment by slamotas** [comment]
Thank you, this is very promising now! I applied the patch, made a new movie, ran it a few times, and everything synced properly with the correct RNG happening. I will continue testing with something more rigorous and see how it goes.

**Comment by InfamousKnight** [comment]
Wow, I'm surprised a solution was found this quick! Congrats all around!

**Comment by slamotas** [comment]
The system time issue I mentioned earlier seems to just be a quirk of the BIOS. The system time shows up properly if you boot into Windows (it will adjust the year to 20xx instead of 19xx if the year is too low, also the time will be adjusted to the time zone you set during installation)

PCem runs perfectly fine with "Prevent writing to disk" checked, unlike DOSBox. It leaves the hard disk image untouched.

With lengthier loading times, like booting Windows 95 and then a game, there's still some non-deterministic behavior. I wish I could upload a hard drive image + movie showing it, but that would obviously not be ok.

**Comment by micro500** [comment]
I am also experiencing non-deterministic behavior when trying to boot Windows 95. Due to the time change in libTAS Windows 95 brings up a window to tell you that the clock changed for daylight savings, but that window comes up on different frames.

Is there anything I can do to help get this resolved? I'm wondering if it would be possible to make a libTAS movie which installs Windows 95 for you if given the correct system disks and a blank harddrive image. We could provide the hashes of the disks needed. You could then leave the "Prevent writing to disk" option unchecked and libTAS could do the install for you.

**Comment by vadosnaprimer** [comment]
Such a movie would be a nice practice in general for future too!

**Comment by slamotas** [comment]
Such a movie would have to enter a CD key at some point. I'm not so sure about the legality of distributing that.

As for the clock, automatic daylight savings adjustments can be turned off. We may also want to standardize the time zone to GMT.

**Comment by clementgallet** [comment]
In the meantime, you can update to commit 79db9715686e3da5054e5a0b6ef9adae377bbac3 and set `Runtime > Wait timeout` to `Infinite wait`. If it doesn't softlock, it will improve determinism.

**Comment by clementgallet** [comment]
I made [another patch](https://gist.github.com/clementgallet/11894a5241014222e0b5bd128dfcb4c8) (to apply to fresh PCem v14) which contains the first patch and some more modification to remove more threads. Sound is disabled. Also, it sounds like loading a savestate to a state where the window resolution was different is causing a desync, so you should avoid that.

**Comment by slamotas** [comment]
Using the best available GPU (tvga8900d), Windows 95 boots consistently on the same frame now! 

Ultimately the S3 Virge is the GPU that can get the most out of PCem, since it supports DirectX 7. Hopefully that can work at some point. The Trident VGA card only supports up to 256 colors, so it can't do anything too crazy, but it should be good to go for most DOS games and a lot of Windows 3.x stuff.

**Comment by clementgallet** [comment]
Ok, [this patch](https://gist.github.com/clementgallet/eb3b05bccd790a0f6c60a2a9d0e19636) adds s3virge becoming single-threaded.

**Comment by slamotas** [comment]
Thank you so much, I just recorded a test movie with a Diablo II demo and it synced, with the correct RNG!

Could you patch Voodoo as well please? I don't think any game requires it, but it does help out some of the 3D games that are compatible with it.

**Comment by clementgallet** [comment]
Remove multithreading in voodoo in [this patch](https://gist.github.com/clementgallet/84b890b0db3f1f7e201034637097b594), and put back cd audio. I tested voodoo using [GTA 1 3dfx demo](https://www.rockstargames.com/gta/extras/demos.html).

**Comment by vadosnaprimer** [comment]
Thanks for making our dreams reality!

**Comment by slamotas** [comment]
Thank you for being very helpful and responsive as always. This is a big deal for PC game TASing.

Can you try testing this [Dungeon Keeper 2 demo](https://archive.org/details/DungeonKeeper2Demo)? It's a fairly intense test of PCem's capabilities. It supports Voodoo 2 and works with it enabled in unpatched PCem, but won't boot in the patched version. It runs fine in the patched version if Voodoo is disabled, so it's definitely the Voodoo patch.

**Comment by clementgallet** [comment]
Oh yeah, voodoo driver can push incomplete commands into the command fifo, and make the fifo thread run the command. Then the fifo thread waits for more bytes to finish executing the command. So this needs a bit more work to make it single-threaded.

Conveniently, the size of a command can be guessed from its header only (first value), so I pull the command header from the fifo, estimate the command size, and start executing the command only if I have enough values in the fifo. Otherwise, I push back the command header in the fifo.

I updated the patch above, it fixes Dungeon Keeper 2 demo (at least the intro/menu, can't you start a single-player game in this demo?).

**Comment by slamotas** [comment]
Thanks for looking at it. I was testing with the full version so I couldn't link it, I guess I never checked if the demo had single player.

For the ultimate test I installed Windows 98 and tried out this [Deus Ex demo](https://archive.org/details/DeusExDemo), which supports 3dfx acceleration. The test movie I recorded synced perfectly, the loading times were consistent. I also did a test encode and nothing was wrong with it.

That's about all I can think of testing without making a full TAS of something. I'm not sure when to close an issue like this because something might still pop up, but it sure looks like PCem is fully TASable now!

**Comment by InfamousKnight** [comment]
Is the test encode uploaded anywhere? And in the encode, does it show
windows 98 being installed?

**Comment by slamotas** [comment]
I don't plan on uploading the encode, it was just a video/audio test. All Windows game TASes will start with Windows and the game already installed, the installation won't be part of it.

**Comment by InfamousKnight** [comment]
A new release of pcem is out! 1.5. Although it has a lot of updates that sound like gibberish to me..

Just throwing it out there.

**Comment by clementgallet** [comment]
PCem sync version is being worked on in https://github.com/TASVideos/pcem/
