### ISSUE TITLE
Cannot get Celeste to work

### ISSUE THREAD

**Issue by jonathanasdf** [clementgallet/libTAS#214]
Hi, I've been trying for about 20 minutes to use this with Celeste but running into some problems. Since people have gotten it to work, there must be something wrong with my setup, but I have no idea where I should be looking.

Game options: https://i.imgur.com/WD8vJ8L.png
I tried with both vsync on and off and got the same behavior.

1: If I don't run with uncontrolled time, the game cannot advance past the first frame

https://pastebin.com/iYPH0cJ9

It seems to be stuck in an infinite loop waiting for some condition
[libTAS f:0] Thread 2762 (main) pthread_cond_timedwait call with cond 0xa25820 and mutex 0xa25860

2: With uncontrolled time it runs fine for some frames, then freezes. This happens whether I step through frame by frame or if I start the game unpaused and let it run by itself. The last line in the log is always sigsuspend call.

https://pastebin.com/3MYkN1vg

I tried recycle threads on/off after seeing the other Celeste issue but I guess that problem was fixed since it didn't make a difference.

**Comment by noellekiq** [comment]
from the [game compatibility page](http://tasvideos.org/EmulatorResources/libTAS/GameCompatibility.html): 

`FNA / MonoGame games may need Runtime > Time tracking > Main thread > clock_gettime() to prevent softlocks. Also, some versions of mono need Runtime > Recycle threads unchecked to prevent crashes when threads exit.`

**Comment by jonathanasdf** [comment]
Thanks :3 that was it. I knew it would be something dumb.

If anyone here can edit http://tasvideos.org/6217S.html perhaps add that bit in?
