### ISSUE TITLE
Input editor show savestate created even if saving the state failed

### ISSUE THREAD

**Issue by micro500** [clementgallet/libTAS#218]
I had limited space on my harddrive and I tried to overwrite an existing savestate. libTAS put a message in terminal that the savestate failed because there was not enough space, but the input editor incorrectly moved the savestate number indicator to the current frame as if the state was successfully saved.

**Comment by clementgallet** [comment]
Fixed in fcb8b50c274cca3082ae23c88cb09efdee4704c0
