### ISSUE TITLE
Add an option to change framerate mid run

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#22]
Low priority but would be nice for meatboy all glitches

**Comment by clementgallet** [comment]
Most of the work done in 337fc9c6cd1248f9830a38d8174b48a7fb3ee613

Still a few things to take care of:
- Encoding is not supported
- If there are computations of the movie length, they are now incorrect (check movie metadata)
- I'm resetting the sub-nanosecond accumulator (used to compute the length of a frame) when framerate has changed, is that a problem? This accumulator is used when the length of a frame cannot be represented as a integer number of nanoseconds (smallest unit of time used in Linux), but the meaning of its value depends on the value of the framerate.
- Displayed values when loading a savestate are incorrect (they look correct after advancing one frame)
- Check if audio mixing is holding up

**Comment by clementgallet** [comment]
- Fix the interaction with restart/auto_restart
