### ISSUE TITLE
mgba desyncs with certain games

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#221]
First of all, the reason I'm mgba in libtas instead of bizhawk is because libtas has it's own save states. whereas bizhawk is a wrapper and uses the emu save state instead.

So the problem I'm having is with 2 games:
lego star wars the original trilogy and stuntman

With lego star wars the original trilogy: it syncs up to getting the first mini kit. upon entering the room with mini kit(first room open) a desync occurs. You can fix it by the playing it back and just resyncing if that makes any sense. And every 10 seconds or so it desyncs.. What's really strange, is that on bizhawk the exact same thing happens.

Now with stuntman, for some reason, in blood oath missions, its prone to desyncs at the beginning. the second visit here, I retried many times and didn't have much success and gave up(this happened on an old release of bizhawk, but I made driv3r on an even older version which uses the same engine and looked more likely to desync with its random nature).

So even if no solution is found, I'm still curious to know if anyone has an idea of why this happens. A similar story with turok 3 n64 movie on tasvideos.

**Comment by noellekiq** [comment]
`What's really strange, is that on bizhawk the exact same thing happens.`

then it isnt a libtas issue, no reason to mention it here.
