### ISSUE TITLE
Tried to run Sekiro in libTAS but got this error

### ISSUE THREAD

**Issue by Daravae** [clementgallet/libTAS#224]
Hey,

I was interested in trying out if Sekiro: Shadows Die Twice would work with libTAS, but unfortunately after trying to start, I ran into this error:

`Could not determine arch of file /home/daravae/.steam/steam/steamapps/common/Sekiro/sekiro.exe based on the `file` command output
Full output: PE32+ executable (GUI) x86-64, for MS Windows`

Does anyone know what this means and if I could resolve it somehow?

**Comment by clementgallet** [comment]
Sekiro is not available on Linux, so it won't work.

**Comment by Daravae** [comment]
Does it need Steam support for it in order to work with libTAS?
I run the game just fine in Linux Mint by using Proton compatibility mode through its properties in Steam

**Comment by clementgallet** [comment]
Oh, yeah, I forgot about Proton. libTAS is not compatible with Proton or wine for now. It may be the case in the future, but it might be a lot of work to perform.

**Comment by clementgallet** [comment]
Discussions about Wine/Proton will take place in #54
