### ISSUE TITLE
PPSSPP doesnt run homebrew

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#225]
In the fork provided, while it does fix the desync issue, it does require rendering 0. I understand it maybe hard to bring capability back, but homebrew doesnt give the message and a black screen comes up only. I asked the original ppsspp team about it and they said its because theres no unique id for it. Something like that.

Any way to fix that?

**Comment by clementgallet** [comment]
Try `RenderingMode = 1` and `SoftwareRenderer = True` as well. Not ideal but it fixes one test game I have.

**Comment by InfamousKnight** [comment]
Yeah, it fixed it. Pspkvm works at pretty good speed too. Gta and midnight
run extremely slow so would buying a faster computer make a difference?

**Comment by InfamousKnight** [comment]
Something odd with pspkvm: if you use frame advance, it will desync before you can even start a new game. If you dont use frame advance, you will guarantee the same result next time.

Any way to fix that?

**Comment by InfamousKnight** [comment]
Sorry for the double post, but it gets worse: you also cant use slow motion either. I tried 12% and 50% speed and both act kinda strange to begin with and seem to skip frames. Like the frame counter would stop and then quickly go up 4 or 5 frames making it very difficult to work with.

But if you run it at normal speed, it syncs fine. I wanted to tas saints row j2me as nobody has any full playthrough of it recorded.

**Comment by clementgallet** [comment]
We already have an issue on PPSSPP determinism in #151
