### ISSUE TITLE
Tasing without software renderer

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#226]
Is it possible to tas like a unity game without software renderer needed for save states? It runs extremely slow and I dont have the patience to work with something like that. But I do have the patience for this to be fixed. I recall some suggestions to disable some effects but those are hacks and dont make much difference.

**Comment by noellekiq** [comment]
no

**Comment by clementgallet** [comment]
Actually, there is [this possibility](https://arxiv.org/abs/1312.6650) used as a plugin for the [DMTCP](http://dmtcp.sourceforge.net/), i.e. hook every OpenGL calls that change the internal state, store that state in the savestate, and replay all those calls when loading.

**Comment by InfamousKnight** [comment]
Nice to see theres a solution known. I take this will be a lot of work?

**Comment by clementgallet** [comment]
Yes, it would take quite a lot of work.

**Comment by clementgallet** [comment]
Wow, I didn't know that. As noellekiq said, GPU behavior appears to be non-deterministic. For example, [the result of a sum can vary](https://github.com/tensorflow/tensorflow/issues/3103) using CUDA because floating-point addition is non-associative, and additions can be done in any order by GPU multi-threaded execution.

**Comment by InfamousKnight** [comment]
So theres nothing that can be done to upgrade this? Maybe hook the entire vulkan api? This would just motivate people to tas modern games.

**Comment by InfamousKnight** [comment]
Would buying the fastest cpu help?

**Comment by InfoTeddy** [comment]
No, that's fundamentally *not* how CPUs work.

Basically (and I am simplifying a bit), GPUs are great for doing really simple operations 1,000,000 times a second (that's all that graphics is), and CPUs are great for doing complicated logic maybe 1,000 times a second. You can't ask a CPU to do the amount of calculations needed for graphics (and expect to be fast), they're simply not built that way. And this is true even for the fastest CPU ever.

The fastest CPU that can run graphics as fast as GPUs can isn't a CPU any longer, it's a GPU.
