### ISSUE TITLE
Undertale crashes without mute

### ISSUE THREAD

**Issue by LucasWills** [clementgallet/libTAS#227]
I am tasing Undertale using LibTAS v1.3.4 32bit. Everything is working fine, however the game instantly closes when I try to turn off mute. The audio works fine when running the game outside of LibTAS.

**Comment by InfamousKnight** [comment]
Strange; If mute is on while encoding, the sound should be there regardless. Would having sound help in making the tas? The only case I can think of where this would benefit is hearing cop cars crash behind you in a gta like game and looking behind the second before it happens.

**Comment by clementgallet** [comment]
I'm not having this problem. Can you specify which distribution you are using? Also, could you launch libTAS from a terminal and copy here if you have any message when the crash happens?

**Comment by LucasWills** [comment]
I am running undertale linux v1.001 on the latest 32bit release of libtas on ubuntu 18.04. I got this error when running in terminal: Cannot open default audio device
UNDERTALE: pcm_params.c:2290: snd_pcm_hw_refine: Assertion `pcm && params' failed.

**Comment by clementgallet** [comment]
It looks the same as issue #31, could you try installing `libasound2-plugins`?
