### ISSUE TITLE
Run 64 and 32 bit games

### ISSUE THREAD

**Issue by heav-4** [clementgallet/libTAS#229]
I constantly have to switch between libTAS 32 bit and 64 bit by uninstalling one and installing the other, any way to run both types of games without reinstalling anything?

**Comment by clementgallet** [comment]
No, it's not currently possible. I wonder if it's possible to compile both 32 bit and 64 bits libraries and let the program choose the correct one (or preload both, I think Steam is doing that with their steamoverlay).

**Comment by clementgallet** [comment]
You can now have a dual-arch setup where libTAS will choose the right library based on the game arch (see Readme).
