### ISSUE TITLE
The tool sometimes unpauses when frame advancing

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#23]
Seems to happen when holding the frame advance

**Comment by Matte27** [comment]
Might not be unpaused but instead advancing a bunch of frames during when frame advance is no longer held

**Comment by clementgallet** [comment]
The frame-advance key release was skipped when releasing another key at the same time. This was fixed in 36f255e786853fc925fe25ed87c65014255f0ed3. This should fix this issue.
