### ISSUE TITLE
Save/load state slot selector

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#232]
So to be specific:

we would have a current state slot that can increase/decrease with a hot key. This benefits those with a game controller who want to use multiple save states. A feature like this exist in fceux if I recall.

Simple enough?

**Comment by clementgallet** [comment]
Is it really needed? How many people are using a controller for TASing? Controllers are not supported in libTAS, and it would be a low priority feature.

**Comment by InfamousKnight** [comment]
I wouldn't say needed, just nice to have. I actually never made a tas using a game controller before because of this issue. But yeah, low priority.

**Comment by clementgallet** [comment]
I don't think this is a needed feature, and I'm not planning on supporting controllers.
