### ISSUE TITLE
Screen resolutions broken in Baba Is You (Chowdren)

### ISSUE THREAD

**Issue by noellekiq** [clementgallet/libTAS#234]
Broke somewhere between https://github.com/clementgallet/libTAS/commit/27e07604fb37e5c9f5eae04a01678adc41ba3170 and https://github.com/clementgallet/libTAS/commit/26a71f818186b716a1761050cc68fb4557576059 ([git range](https://github.com/clementgallet/libTAS/compare/27e07604fb37e5c9f5eae04a01678adc41ba3170...26a71f818186b716a1761050cc68fb4557576059) -- the game wouldn't load at all during these commits so pinpointing the precise commit was difficult with just git bisect)

Native resolution works, all other presets don't

(Also, the timing now seems to require SDL_GetPerformanceCounter, might want to be added to wiki?)

**Comment by clementgallet** [comment]
Sorry, I fixed it but forgot to push. Because we implemented more XRR functions for wine, SDL2 broke because it was still using one unimplemented function. Fixed in bf6b209af7f823825d8411475e1e73d36608b492
