### ISSUE TITLE
Issue when loading libTAS

### ISSUE THREAD

**Issue by Azrez2** [clementgallet/libTAS#236]
I try to start libTAS through ./libTAS in its directory and it opens fine but I get 

** (libTAS:2572): WARNING **: 16:53:03.484: (../atk-adaptor/bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)

in my terminal. Is this just an issue with my setup or is it an issue with the program?

**Comment by clementgallet** [comment]
I think this is not an issue specific to libTAS but with GTK programs. Do you have any problem with the GUI?

**Comment by clementgallet** [comment]
It's not an issue specific to libTAS, and has no consequences afaik.
