### ISSUE TITLE
libTAS GUI cannot run a 64-bit executable after running a 32-bit executable

### ISSUE THREAD

**Issue by madewokherd** [clementgallet/libTAS#237]
When pointing libTAS to the Linux executable for super hexagon (superhexagon.x86_64), I get this error:

libtas.so library was compiled for a 64-bit arch but /home/libtas/superhexagon-linux/x86_64/superhexagon.x86_64 has a 32-bit arch

Output of file -b:
libtas@wiley:~/src/libTAS$ file -b '/home/libtas/superhexagon-linux/x86_64/superhexagon.x86_64'
ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=68e97f86fa8de2c9ade1522631cf5908dea0db01, with debug_info, not stripped

**Comment by madewokherd** [comment]
This may only happen if a 32-bit executable was started before the 64-bit executable.

**Comment by madewokherd** [comment]
I think that error message may be getting the enum values mixed up, I'm going to try rewriting it in a less confusing way.

**Comment by madewokherd** [comment]
Yep, libtas is 32-bit and the executable is 64-bit. I think the substitution of libtas32.so for libtas.so is permanent.

**Comment by clementgallet** [comment]
I thought I fixed it by changing `libtas.so` path in the forked process, so that the main program is unaffected, but I forgot to remove the previous path change, sorry. Fixed in 670b3d088997b12b52ef396e1849f023c9464116
