### ISSUE TITLE
Wine crashes in libasound

### ISSUE THREAD

**Issue by madewokherd** [clementgallet/libTAS#241]
When trying to run Cat Planet in libTAS, it always crashes in libasound:

```
Backtrace:
=>0 0xf7ffd059 __kernel_vsyscall+0x9() in [vdso].so (0x0187fafc)
  1 0xf7ad0832 execlp+0xffffffff() in libc.so.6 (0x0187fafc)
  2 0xf7ad1cc1 execlp+0xffffffff() in libc.so.6 (0xf7c7bce0)
  3 0xf7ac87bb execlp+0xffffffff() in libc.so.6 (0xf7c7bce0)
  4 0xf7ac8819 execlp+0xffffffff() in libc.so.6 (0x0187fe58)
  5 0xf77fd3ce snd_hctl_elem_get_name+0x1396d() in libasound.so.2 (0x0187fe58)
  6 0xf7808da7 snd_hctl_elem_get_name+0x1f346() in libasound.so.2 (0x0187fe58)
  7 0x7c9cd8ca alsa_push_buffer_data+0x1d9(user=<couldn't compute location>, timer=<couldn't compute location>) [/home/wine/source/wine/wine32/dlls/winealsa.drv/../../../dlls/winealsa.drv/mmdevdrv.c:2210] in winealsa (0x0187fe58)
```

Here's a link to the line in Wine that's crashing: https://source.winehq.org/git/wine.git/blob/48a74277f5:/dlls/winealsa.drv/mmdevdrv.c#l2210

I think the issue is that the library doesn't wrap snd_pcm_recover.

**Comment by InfamousKnight** [comment]
Hmm, does this error show up anywhere:

[sean@sean-pc ~]$ libTAS
Interim commit bf6b209 built on 2019-06-21
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 6165, resource id: 21071222, major code: 40 (TranslateCoords), minor code: 0
ERROR: ld.so: object '/usr/bin/libtas32.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/bin/libtas32.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"l3codeca.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
0009:fixme:dwmapi:DwmIsCompositionEnabled 0x58d554
0009:err:dmloader:IDirectMusicLoaderImpl_SetObject : could not attach stream to file L"C:\\windows\\system32\\drivers\\gm.dls", make sure it exists
[libTAS f:0] Thread 2786 (main) ERROR:     Unsupported stream direction 1
[libTAS f:0] Thread 2786 (main) ERROR:     Unsupported stream direction 1
0009:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
0009:fixme:dmime:IDirectMusicPerformance8Impl_CreateStandardAudioPath (0x1df130)->(8, 64, 0, 0x1df2fc): semi-stub
0009:fixme:dmime:IDirectMusicAudioPathImpl_Activate (0x1f30a0, 0): stub
Got unknown message!!!
[libTAS f:1] Thread 2786 (main) ERROR: Unknown message received
[libTAS f:2] Thread 2786 (main) ERROR: Unknown message received
wine: Unhandled page fault on read access to 0x0000000c at address 0xf7818404 (thread 002a), starting debugger...
[libTAS f:3] Thread 2786 (main) ERROR: Unknown message received
[libTAS f:4] Thread 2786 (main) ERROR: Unknown message received

**Comment by InfamousKnight** [comment]
A similar error showed up when launching nightendo nightmare. But yeah, it must be the sound issue. Seems like an arch only problem as well. 

With nintendo nightmare, it would show a loading screen, then crash about 75% in.

We are getting close.

**Comment by clementgallet** [comment]
Implemented `snd_pcm_recover()` and `snd_pcm_reset()` in 609ec0fd11cc8ba2ea66f19db66038a4a0bb6dc0

**Comment by InfamousKnight** [comment]
Well, now its even less functional:

[sean@sean-pc ~]$ libTAS
Interim commit 670b3d0 built on 2019-06-24
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
ERROR: ld.so: object '/usr/bin/libtas32.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/bin/libtas32.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Couldn't connect to socket.
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Couldn't connect to socket.
Attempt 5: Couldn't connect to socket.
Attempt 6: Couldn't connect to socket.
Attempt 7: Couldn't connect to socket.
Attempt 8: Couldn't connect to socket.
Attempt 9: Couldn't connect to socket.
Attempt 10: Couldn't connect to socket.
The connection to the game was lost. Exiting

I did double check to see if alsa was enabled in winetricks.

**Comment by InfamousKnight** [comment]
Is anyone else having that ^ problem? Or is it just me? I updated my package with yay and entered a clean build.

**Comment by madewokherd** [comment]
I suggest filing a new issue rather than posting on unrelated ones.

**Comment by InfamousKnight** [comment]
Makes sense. Ill do more testing tomorrow to see if its a wine only problem
or everything.

Btw, has the new update fixed it on your end? Im on my break at work right
now.

**Comment by madewokherd** [comment]
Well, I no longer get this particular failure, so I guess it's probably fixed.
