### ISSUE TITLE
Star wars battlefront 1 wine crashes

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#245]
The backtrace says this:
Backtrace:
=>0 0xf7f74d6f udev_hwdb_get_properties_list_entry+0x909f() in libtas32.so (0x0214e648)
  1 0x7e28afe4 X11DRV_Beep+0x803() in winex11 (0x0214e678)
  2 0x7e28de2d X11DRV_ClipCursor+0x20c() in winex11 (0x0214e6b8)
  3 0x7e2a5142 X11DRV_WindowMessage+0x81() in winex11 (0x0214e6e8)
  4 0x7ea51601 TranslateAcceleratorA+0x370() in user32 (0x0214e738)
  5 0x7ea5170d TranslateAcceleratorA+0x47c() in user32 (0x0214e798)
  6 0x7ea5400f PostMessageA+0x3ae() in user32 (0x0214ec78)
  7 0x7ea5786b PostMessageA+0x3c0a() in user32 (0x0214ed48)
  8 0x7ea57b42 PostMessageA+0x3ee1() in user32 (0x0214ed88)
  9 0x7ea57e2a PostMessageA+0x41c9() in user32 (0x0214edd8)
  10 0x7ea58103 SendMessageW+0x62() in user32 (0x0214ee28)
  11 0x7e27a0de X11DRV_create_desktop+0x75d() in winex11 (0x0214ef08)
  12 0x7e27a19f X11DRV_create_desktop+0x81e() in winex11 (0x0214ef28)
  13 0x7e29a732 X11DRV_ChangeDisplaySettingsEx+0x2b1() in winex11 (0x0214f198)
  14 0x7ea72c1b ChangeDisplaySettingsExW+0x2a() in user32 (0x0214f1d8)
  15 0x7ee865c8 wined3d_set_adapter_display_mode+0x137() in wined3d (0x0214f408)
  16 0x7eedb745 wined3d_stateblock_create+0x9624() in wined3d (0x0214f448)
  17 0x7eede539 wined3d_swapchain_set_fullscreen+0x78() in wined3d (0x0214f498)
  18 0x7ee82f47 wined3d_device_reset+0x2f6() in wined3d (0x0214f558)
  19 0x7ef92654 in d3d9 (+0x12653) (0x0214f618)
  20 0x7ef92932 in d3d9 (+0x12931) (0x0214f638)
0xf7f74d6f udev_hwdb_get_properties_list_entry+0x909f in libtas32.so: testb

I'm not really sure what do with these in case of softlocks, so does anyone know how to get a backtrace of those as well?

This version is a real good one to tas. As it has mouse inputs which are more precise than some depad.

**Comment by clementgallet** [comment]
Wine is at unsupported state, due to how difficult it is to debug, as well as to maintain through updates.
