### ISSUE TITLE
Midnight club 2 demo freezes my computer if full screen

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#246]
I've noticed some full screen hooks for wine was made today and thought I'd try out having full screen on midnight club 2. What happened as a result was my computer froze. I had to turn it off. I couldn't touch anything, so nothing could be done to copy any logs at all. I tried virtual screen resolution in libtas and the same thing happened. 

It still doesn't provide much when I run it with virtual resolution in winetricks. Just a black screen that stalls.

If I run wine mc2 in the terminal, it won't open. If I double click the icon, it will open. Wtf

**Comment by clementgallet** [comment]
The method to install dual-arch libTAS has changed. Could you make sure you installed the latest version?

**Comment by InfamousKnight** [comment]
Tried downloading libtas-master.zip, using your build guide with ./build --with-i386 and eventually an error popped up somewhere down the line of libtas32 and so I tried this command yay -S libtas-git lib32-libtas-git and it tells me at the bottom no packages were upgraded and commit transaction failed. There was a warning saying build --enable-i386 not recognized somewhere down the line though.

**Comment by clementgallet** [comment]
If you don't show the error, I cannot help you.
Because the i386 option was changed, the AUR package is outdated. I've contacted the author.

**Comment by InfamousKnight** [comment]
Ill wait for the Aur package to be updated then. It was some dependency
error that probably already exist like before. I wasnt making that up btw.
I couldnt believe it myself. I didnt bother testing it this time.

**Comment by chungy** [comment]
AUR maintainer here. It might be a day or two before I update the package, just as I work a bit with @clementgallet about the situation. Hang tight, we'll have something soon! :D

**Comment by InfamousKnight** [comment]
Sounds good. I have to work all weekend anyways.

**Comment by InfamousKnight** [comment]
Well, my computer doesn't freeze anymore when running.. but
