### ISSUE TITLE
[Wine] midnight club 2 flickers

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#253]
Testing latest commit, and the game now flickers on anything besides loading screens. I dont think this was an issue before. 
Also, a black screen occurs after loading the map with no hud for some amount of seconds. Then the main game loads with more flickering.

Any idea whats going on?

**Comment by clementgallet** [comment]
89c1fa73cea997cc6b3705db8404bbcc2c7da81c should fix flickering

**Comment by InfamousKnight** [comment]
And it did fix it. Thanks again!
