### ISSUE TITLE
[Wine] Midnight club 2 demo requires uncontrolled time to run.

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#255]
Which in turn leads to desyncs..

What I should do to provide more info to get this debugged?

Btw, this game utilizes audio sample wait thing quite a bit as well as backtrack savestates. I do have the full game of midnight club 2 which for some reason doesn't have any music that plays(tested outside of libtas) but thats fine because I could easily put my own music in there!

[Edit] runtime-timetracking-clockgettime seems to have it go up 9 frames and then softlocks with this:

[libTAS f:7] Thread 2689 (main) Audio mixing will underrun, waiting for the game to send audio samples
[libTAS f:7] Thread 2689 (main)     Timeout
Available memory: 47.444 M

Done loading movie - 0.00+0.00ms read+seek, 37ms total
Font 'navigator_large' refcount=1
0009:fixme:d3d:wined3d_swapchain_set_gamma_ramp Ignoring flags 0x1.
002a:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
[libTAS f:8] Thread 2735        Switching main thread from 4143559616 to 1903549248

So what should I do from here?

[edit 2] debug-timetracking all threads-clockgettime seems to work, but it still desyncs often. Playing it back twice yields different input results. The pediatricians seem to appear in the same place each time, so it seems like input determinism and not rng. 

Is wine4.11 on arch the latest? I've always had trouble with ubuntu. 

And another update: found out about xevent under asynchronous and it gives an error during loading a map:

[libTAS f:696] Thread 1711 (main) ERROR: xevents sync took too long, were asynchronous events incorrectly enabled?
[libTAS f:706] Thread 1711 (main) ERROR: xevents sync took too long, were asynchronous events incorrectly enabled?
[libTAS f:716] Thread 1711 (main) ERROR: xevents sync took too long, were asynchronous events incorrectly enabled?
*****Changing State: from BeforeCountdown to Countdown
countdown length: 2.00
[libTAS f:736] Thread 1711 (main) ERROR: xevents sync took too long, were asynchronous events incorrectly enabled?
[libTAS f:748] Thread 1711 (main) ERROR: xevents sync took too long, were asynchronous events incorrectly enabled?

Whats that mean?

**Comment by InfamousKnight** [comment]
And I do have wine-4.12.1 which is the stable release for wine, but I'm still getting the same results. An error message pops up on every wine window, but it can be ignored. Just close it and forget its there.

**Comment by clementgallet** [comment]
So... you just closed an issue and opened a new one with the exact same problem.

I'm really happy that you are testing a lot of games and reporting issues, but the way you are doing it makes it really hard for me to keep track. So here is a list of guidelines that I would really like you to follow:

* Don't ask the same question multiple times, especially on different issues. This won't make me work on it sooner, and will just dilute the issues tracking.
* Keep issues independent, don't suppose that someone had read your previous posts on other issues. Always put as much relevant information as possible in the issue description. I wrote a [short list ](http://tasvideos.org/EmulatorResources/libTAS/FAQ.html) of what you should include in your issues.
* Don't ask questions unrelated to libTAS
* Issue tracking is not a forum. Please don't comment on other issues with unrelated content
* Don't assume too much about what is happening when posting an issue. Describe facts about what is happening, but don't make assumptions unless you can back them up

I'm not saying this in an hostile manner, really. It's just that I want to keep the issue tracking as clean as possible, and you are not really helping :)

**Comment by InfamousKnight** [comment]
This isn't the same issue as before. Before was just getting it to load anywhere, which was solved and I closed it. This is a desync problem, so I opened it separately. I also closed the issue with flickering, because that was solved too. So maybe you're making an assumption. Its an unfortunate part of human nature.

**Comment by InfamousKnight** [comment]
Actuallly, we already have an issue about input determinism. Closing
