### ISSUE TITLE
Gunpoint black screen on launch

### ISSUE THREAD

**Issue by SeneX225** [clementgallet/libTAS#256]
Console log:
```
Attempt 1: Connected.
[libTAS f:0] Thread 24135 (main) OpenGL vendor: VMware, Inc.
[libTAS f:0] Thread 24135 (main) OpenGL renderer: llvmpipe (LLVM 7.0, 128 bits)

```

**Comment by clementgallet** [comment]
Implemented an option `Runtime > Debug > Keep main first thread`, which together with `Runtime > Time tracking > gettimeofday()` makes the game run (7c661679dafc7df509615c9fa380b974f4b30597), and fixed savestates (d45c5e3f6dd584a046ca916ad848ac5c417514d2).

Also fixed the mouse inputs by sending EnterNotify and FocusIn events (d38294f403bc9217b68342110e9bdff6320f7b6e).

**Comment by SeneX225** [comment]
Many thanks, now it works!

**Comment by SeneX225** [comment]
Many thanks, now it works!
