### ISSUE TITLE
Clone Hero has no sound in game

### ISSUE THREAD

**Issue by ItzzYaBoi** [clementgallet/libTAS#260]
Was waiting for #175 to see if that was the cause but it's not, so I'm submitting now.

Game version: Alpha v.22.5 [Download CH]

Movie I'm trying to play: [Movie DL]

Game `settings.ini`: [settings.ini]

Game `Songs` directory: [songs.png], [Soulless 4], [Through The Fire And Flames]

libTAS config (/home/user/.config/libTAS): [clonehero.ini]

Game sometimes desyncs seemingly randomly too, but that's out of scope for this issue.

Note 1: The main menus have music, in game however is silent. 

Note 2: executable hash might be wrong in the movie file, game mechanics haven't changed however.

[Download CH]: http://dl.clonehero.net/clonehero-v.22.5/clonehero-linux.tar.gz
[Movie DL]: https://anonfile.com/je5au804n0/flames_175_full_combo_ltm
[settings.ini]: https://pastebin.com/8LRVcT2q
[songs.png]: https://i.imgur.com/TZy6zCz.png
[Soulless 4]: https://anonfile.com/x34eub07n4/Soulless_4_zip
[Through The Fire And Flames]: https://anonfile.com/z94bu409nd/Dragonforce_-_Through_The_Fire_Flames_zip
[clonehero.ini]: https://pastebin.com/MvFZhq7c

**Comment by clementgallet** [comment]
The game was calling `snd_pcm_prepare()` even if there was no error in the stream. I took the opportunity to improve ALSA mmap implementation (4694ebb97cb5432a426b56754ff80b9f16598de1)

**Comment by ItzzYaBoi** [comment]
Audio issue is resolved, movie doesn't sync any more, but I was planning on remaking it anyway.
