### ISSUE TITLE
32 bit build problem

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#261]
executing yay -S lib32bit-libtas.git ends up with this:

 ==> Making package: lib32-libbluray 1.1.0-1 (Wed 24 Jul 2019 12:41:10 PM EDT)
==> Retrieving sources...
  -> Downloading libbluray-1.1.0.tar.bz2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:21 --:--:--     0^

Eventually it fails. Works fine with yay -S libtas but we need 32 bit libtas for wine

**Comment by clementgallet** [comment]
The log indicates that it tries to install the wrong package. I guess the package you are looking for is `lib32-libtas-git`.

**Comment by InfamousKnight** [comment]
yay -S lib32-libtas-git ends with the same result..
==> Making package: lib32-libbluray 1.1.0-1 (Wed 24 Jul 2019 03:24:50 PM EDT)
==> Retrieving sources...
  -> Downloading libbluray-1.1.0.tar.bz2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (7) Failed to connect to ftp.videolan.org port 21: Connection timed out
==> ERROR: Failure while downloading ftp://ftp.videolan.org/pub/videolan/libbluray/1.1.0/libbluray-1.1.0.tar.bz2
    Aborting...
Error downloading sources: lib32-libbluray
Its an arch only problem it seems.

**Comment by chungy** [comment]
There's a couple things you can do to work around it:
1. edit lib32-ffmpeg's PKGBUILD file to remove the references to libbluray. It totally isn't necessary for libTAS.
2. Download the necessary source file with HTTPS instead: https://download.videolan.org/pub/videolan/libbluray/1.1.2/

**Comment by InfamousKnight** [comment]
Fixed
