### ISSUE TITLE
[Wine] No interaction with the process

### ISSUE THREAD

**Issue by thomclx** [clementgallet/libTAS#265]
At launch,  libTAS connects with the process, but is unable to pause, frame advance, and framecount remains at zero.

Built from source  `aa9a832`.

Tested OS :
- Ubuntu 16.04 64bits : executable /opt/wine-stable/bin/wine64 (opt: mc2_demo.exe)
- Xubuntu 18.04 32bits (virtualbox) : executable mc2_demo.exe

Tested Games:
- Midnight Club 2 -Demo
- Tony hawk pro skater 4 - Demo

> 
> Attempt 1: Connected.
> [libTAS f:0] Thread 23338 (main) ERROR: Unknown socket message 32767
> 000f:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
> 000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
> Installed bink gfxLoadImage support.
> mcConfig:AutoDetectSku - product code 'SLUS-20209'
> 002c:fixme:win:EnumDisplayDevicesW ((null),0,0x33f7b4,0x00000000), stub!

![image](https://user-images.githubusercontent.com/53915111/62737384-f3525800-ba2f-11e9-9f24-c1ae9590a149.png)

You did a very good job by the way.

**Comment by InfamousKnight** [comment]
First thing I see wrong here, is that ubuntu 16.04. You need at least
18.04. Im using manjaro with the arch package, and midnight club 2 runs
fine at 30fps. Xubuntu has given others some problems as well. So you may
want to try manjaro as its pretty easy to install.

Even once you do get it work, desync problems are still underway.

**Comment by noellekiq** [comment]
ubuntu 16.04 should work fine if other programs work for them as well.

**Comment by thomclx** [comment]
I tried MC2 because i saw it worked for you InfamousKnight (and know it desync). 
Linux games are working, i successfully built on 16.04 with the right dependancies. I'll forget ubuntu/debian for the moment and give Arch a try. Thank you.

**Comment by clementgallet** [comment]
Please read my answer in #266 and tell me if it's working.

**Comment by thomclx** [comment]
Same bahaviour on Xubuntu 18.04 32bits with .exe in executable field.

> Xubuntu 18.04 32bits (virtualbox) : executable mc2_demo.exe

I finally installed Arch, i will try it today.

**Comment by thomclx** [comment]
I have not tested yet on Arch, but i tested inside a Ubuntu 18.04 64bits container (docker). Built from source with-i386, and working as you expected with .exe in executable field. My bad, I didn't follow the advice (ubuntu 64bits >= 17.10). Thank you.

**Comment by thomclx** [comment]
As the initial report is due to non-compliance with requirements, the issue is closed.

**Comment by lebel-louisjacob** [comment]
@thomclx Would it be possible for you to share your `Dockerfile`? I am on Xubuntu, and I didn't succeed to build due to outdated dependencies. With my current `apt` settings, `Qt5.5.1` is the only option, but `Qt >= 5.6` is required for the latest version. I tried to install `Qt5.14.0`, but I couldn't find a way to tell `build.sh` where the new `Qt` was... And I it is likely that there are other dependencies my system is currently not satisfying.

I might be delusional, but I think a `Dockerfile` for this project might in fact benefit many more people than only me.

**Comment by lebel-louisjacob** [comment]
Well, nevermind. I finally succeeded to make a `Dockerfile` that actually kind of works. I seem to be missing some fonts, but the rest of the app looks good otherwise.
