### ISSUE TITLE
libTAS fails to start if $HOME/.local doesn't exist

### ISSUE THREAD

**Issue by madewokherd** [clementgallet/libTAS#269]
The libTAS GUI tries to create ~/.local/share/libTAS, but somehow while working on #259 I ended up with an account that doesn't have a ~/.local. The GUI doesn't try to create parent directories, so it fails to start.

**Comment by clementgallet** [comment]
Fixed in 11b6fb98d0f8cad451ddcade22aab7fdbf0521c2
