### ISSUE TITLE
[Regression] Dosbox fails to load

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#270]
The console log says this:

sean@sean-HP-Pavilion-Laptop-15-cs0xxx:~$ libTAS
Attempt 1: Connected.
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file /home/sean/.dosbox/dosbox-0.74.conf
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  168
  Current serial number in output stream:  169

And then closes. Not what sure what else to add.

**Comment by clementgallet** [comment]
SDL 1.2 is doing some weird stuff with extra windows. Fixed in 6ec63852f7e18f778d270c059221ad56d63ebf92
