### ISSUE TITLE
Determinism in Unity

### ISSUE THREAD

**Issue by rishubil** [clementgallet/libTAS#272]
I'm testing a simple program to use libTAS in a game made with Unity.

There were some minor issues (such as library installation), but everything seemed to work fine.
However, when playing back a recoded movie, I found that RNG did not work deterministically.

Here is the download link for the Unity program I am testing:
https://github.com/rishubil/Randoms/releases/tag/test

This sample program prints a random number every time you press the 'Generate Random' button at the top of the window.
RNG seed is the default value, and uses `System.Random` and `UnityEngine.Random` to generate numbers.

This sample program doesn't seem deterministic because it generates a different number each time it runs in libTAS.

Is there a way to make it deterministic for a game made with Unity like this?

(I used dual-arch build of commit 59fde6d on Ubuntu 18.04.3 x64)

**Comment by clementgallet** [comment]
Thanks for testing this!

`UnityEngine.Random` uses `/dev/urandom` for seeding, and `System.Random` uses `/proc/uptime` for seeding. If I "disable" `/dev/urandom` (i.e. I simulate the file not existing), as well as `/dev/random`, it fallbacks to another seed which is still non-deterministic.

**Comment by clementgallet** [comment]
Fixed in 9864c60782418ab042f8a2e612da381d1a712b72
