### ISSUE TITLE
Load state across different launches

### ISSUE THREAD

**Issue by thomclx** [clementgallet/libTAS#273]
Recently, i faced some desync when using fastforwarding. So i tried to save/restore states to avoid fastforwarding between game launches.
To do so, i kept the p and pm files and i used this program to get the same ids between launches:
http://efiop-notes.blogspot.com/2014/06/how-to-set-pid-using-nslastpid.html
Unfortunately,  even if the thread list is equal, the game crashes.
Once i get the same thread list, what does prevent me from restoring the state? (i lack knowledge on this subject).

I also tried to use CRIU, i was able to save/restore glxgears inside a VNC Server.
https://criu.org/VNC
Unfortunately, it doesn't fit my use case because CRIU does not seems to support 32bit process.

**Comment by clementgallet** [comment]
The main issues when restoring savestates from a previous execution:

* file descriptors may be different
* allocated memory layout may be different, even when disabling [Address space layout randomization](https://fr.wikipedia.org/wiki/Address_space_layout_randomization)
* there is data shared with the system that may have changed, such as the connection with the X server

It would take a tremendous effort to fix everything. It is much more reasonable to work on alternative (e.g. improving fast-forward)
