### ISSUE TITLE
redirect internet download to local file

### ISSUE THREAD

**Issue by Paul-Relkin** [clementgallet/libTAS#274]
I am working on a TAS for a flash game using libTAS and sdl-gnash. The game requires a file to be downloaded from the internet. What is the best way to handle this? Should libTAS be patched to provide the file locally? Or should the URL be redirected to a local file at a DNS level?

**Comment by vadosnaprimer** [comment]
To have full control over determinism, you need the file to exist locally, so you don't depend on the web when you replay the movie.

**Comment by clementgallet** [comment]
Yeah, internet, or any kind of outside communication, will break determinism, and will obviously break savestates as well. You must find a way to bypass that requirement.
