### ISSUE TITLE
Games won't run on Ubuntu 19.04 due to outdated dependencies

### ISSUE THREAD

**Issue by ToonLucas22** [clementgallet/libTAS#276]
I just installed Linux Ubuntu 19.04 to my computer yesterday and wanted to begin testing it, however the dependency libswresample2 apparently cannot be met because 19.04 utilizes libswresample3 instead. I went to the forums for help, found this topic ([http://tasvideos.org/forum/viewtopic.php?t=21230](url)) and forced-installed the package as per told, but attempting to run games would give out the following error:

> error while loading shared libraries: libswresample.so.2: cannot open shared object file: No such file or directory

Here's one of the logs:
[SuperMeatBoy.log](https://github.com/clementgallet/libTAS/files/3673311/SuperMeatBoy.log)

**Comment by chungy** [comment]
This looks like a Steam issue instead of a libTAS issue.

**Comment by ToonLucas22** [comment]
The issue pops up regardless of whether I enable the virtual Steam client or not, so I don't think so.

**Comment by noellekiq** [comment]
does the issue occur when launching games directly from steam?

**Comment by ToonLucas22** [comment]
Launching the games directly from Steam works just fine as far as I'm concerned.

**Comment by ToonLucas22** [comment]
Just tried with a non-Steam game, still got the exact same error.
[openhexagon.x86_64.log](https://github.com/clementgallet/libTAS/files/3673871/openhexagon.x86_64.log)

**Comment by thomclx** [comment]
For my part still have a Ubuntu 16.04 host, i built libTAS inside a container (docker - official ubuntu 18.04 image) because my OS could not meet requirements/dependencies. 
You can try to build it from scratch, or try to use the .deb inside a container, or build inside a container, just ideas...

**Comment by ToonLucas22** [comment]
Downloading the master build and building it from there fixes the issue.
