### ISSUE TITLE
Issue with cross-compiling to i386

### ISSUE THREAD

**Issue by vidiot64** [clementgallet/libTAS#277]
`./build.sh --with-i386` produces the following output
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for g++... g++
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking for style of include used by make... GNU
> checking dependency style of g++... gcc3
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking whether make supports nested variables... (cached) yes
> checking for i386 cross-compiling... yes
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for gcc... gcc
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for QT5... yes
> checking for moc... moc
> checking xcb/xcb.h usability... yes
> checking xcb/xcb.h presence... yes
> checking for xcb/xcb.h... yes
> checking xcb/randr.h usability... yes
> checking xcb/randr.h presence... yes
> checking for xcb/randr.h... yes
> checking xcb/xcb_cursor.h usability... yes
> checking xcb/xcb_cursor.h presence... yes
> checking for xcb/xcb_cursor.h... yes
> checking xcb/xcb_keysyms.h usability... yes
> checking xcb/xcb_keysyms.h presence... yes
> checking for xcb/xcb_keysyms.h... yes
> checking xcb/xkb.h usability... yes
> checking xcb/xkb.h presence... yes
> checking for xcb/xkb.h... yes
> checking for xcb_connect in -lxcb... yes
> checking for xcb_xkb_use_extension in -lxcb-xkb... yes
> checking for xcb_cursor_context_new in -lxcb-cursor... yes
> checking for xcb_key_symbols_alloc in -lxcb-keysyms... yes
> checking for ffmpeg... no
> checking for library containing dlopen... -ldl
> checking X11/Xlib.h usability... yes
> checking X11/Xlib.h presence... yes
> checking for X11/Xlib.h... yes
> checking X11/Xlib-xcb.h usability... yes
> checking X11/Xlib-xcb.h presence... yes
> checking for X11/Xlib-xcb.h... yes
> checking for XOpenDisplay in -lX11... yes
> checking for XGetXCBConnection in -lX11-xcb... yes
> checking SDL2/SDL.h usability... yes
> checking SDL2/SDL.h presence... yes
> checking for SDL2/SDL.h... yes
> checking libudev.h usability... yes
> checking libudev.h presence... yes
> checking for libudev.h... yes
> checking for X11/extensions/xf86vmode.h... yes
> checking X11/extensions/Xrandr.h usability... yes
> checking X11/extensions/Xrandr.h presence... yes
> checking for X11/extensions/Xrandr.h... yes
> checking X11/extensions/XInput2.h usability... yes
> checking X11/extensions/XInput2.h presence... yes
> checking for X11/extensions/XInput2.h... yes
> checking X11/extensions/Xinerama.h usability... yes
> checking X11/extensions/Xinerama.h presence... yes
> checking for X11/extensions/Xinerama.h... yes
> checking pthread.h usability... yes
> checking pthread.h presence... yes
> checking for pthread.h... yes
> checking for pthread_create in -lpthread... yes
> checking alsa/asoundlib.h usability... yes
> checking alsa/asoundlib.h presence... yes
> checking for alsa/asoundlib.h... yes
> checking for snd_pcm_open in -lasound... yes
> checking libswresample/swresample.h usability... yes
> checking libswresample/swresample.h presence... yes
> checking for libswresample/swresample.h... yes
> checking libavutil/avutil.h usability... yes
> checking libavutil/avutil.h presence... yes
> checking for libavutil/avutil.h... yes
> checking for swr_init in -lswresample... yes
> checking for av_opt_set_sample_fmt in -lavutil... yes
> checking fontconfig/fontconfig.h usability... yes
> checking fontconfig/fontconfig.h presence... yes
> checking for fontconfig/fontconfig.h... yes
> checking ft2build.h usability... yes
> checking ft2build.h presence... yes
> checking for ft2build.h... yes
> checking for FcInitLoadConfigAndFonts in -lfontconfig... yes
> checking for FT_Open_Face in -lfreetype... yes
> configure: HUD is enabled
> configure: git commit is 59fde6d
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/program/Makefile
> config.status: creating src/library/Makefile
> config.status: creating config.h
> config.status: config.h is unchanged
> config.status: executing depfiles commands
> make  all-recursive
> make[1]: Entering directory '/home/vd/libTAS'
> Making all in src/library
> make[2]: Entering directory '/home/vd/libTAS/src/library'
>   CXX      libtas32_so-DeterministicTimer.o
>   CXX      libtas32_so-openglwrappers.o
>   CXX      libtas32_so-NonDeterministicTimer.o
>   CXX      libtas32_so-main.o
> In file included from audio/AudioContext.h:28:0,
>                  from main.cpp:34:
> audio/AudioSource.h:27:10: fatal error: libswresample/swresample.h: No such file or directory
>  #include <libswresample/swresample.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:3101: recipe for target 'libtas32_so-main.o' failed
> make[2]: *** [libtas32_so-main.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> In file included from audio/AudioContext.h:28:0,
>                  from NonDeterministicTimer.cpp:27:
> audio/AudioSource.h:27:10: fatal error: libswresample/swresample.h: No such file or directory
>  #include <libswresample/swresample.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:3129: recipe for target 'libtas32_so-NonDeterministicTimer.o' failed
> make[2]: *** [libtas32_so-NonDeterministicTimer.o] Error 1
> In file included from audio/AudioContext.h:28:0,
>                  from DeterministicTimer.cpp:27:
> audio/AudioSource.h:27:10: fatal error: libswresample/swresample.h: No such file or directory
>  #include <libswresample/swresample.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:2975: recipe for target 'libtas32_so-DeterministicTimer.o' failed
> make[2]: *** [libtas32_so-DeterministicTimer.o] Error 1
> make[2]: Leaving directory '/home/vd/libTAS/src/library'
> Makefile:455: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/vd/libTAS'
> Makefile:354: recipe for target 'all' failed
> make: *** [all] Error 2`  
It might be worth mentioning that `./build.sh` works as intended.
Apologies if this is a simple error, I'm not exactly linux-fluent yet

**Comment by clementgallet** [comment]
For libswresample and libavutil, you need the 32-bit version of the dev package also, because the headers are arch-specific (don't know why). So, assuming you are on Ubuntu or another Debian-based distro, you need packages `libswresample-dev:i386` and `libavutil-dev:i386`

**Comment by clementgallet** [comment]
Added this in the Readme
