### ISSUE TITLE
i may sound dumb but when will something like this be out for windows? i want to TAS some steam games but i cant find any program for windows to do it

### ISSUE THREAD

**Issue by thegithubuser1** [clementgallet/libTAS#279]

**Comment by InfamousKnight** [comment]
Linux can run windows programs through wine, and wine currently has lots of
issue that still need addressing. An abandoned project called hourglass was
less fuctional as far as I know.

**Comment by chungy** [comment]
It's unlikely that any tool will come out for current Windows versions. There was a project called Hourglass with a hard dependency on Windows XP, but even in the confines of XP, it was impossible for a TAS tool to have the control over program execution it needs for it to be deterministic across different Windows XP installations or even runs. There is a [postmortem](http://tasvideos.org/forum/viewtopic.php?t=20210) with more details about it.

Windows Vista and later versions introduced new memory protection features like [ALSR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) that really make it quite impossible to run programs deterministically, and totally lock out the possibility of TASing games on Windows that don't run on Windows XP.

Wine in LibTAS is an alternative that might alleviate some issues, while raising new ones. Wine is very multithreaded and very hard to deterministically run too, even different versions of Wine have different behavior in programs/games. (I'm not an authority, but...) it's unlikely that TASVideos will accept libTAS+Wine submissions.

**Comment by InfamousKnight** [comment]
There is still hope, maybe certain versions will only work for certain games. Much like with minecraft how certain mods work with certain versions.

**Comment by chungy** [comment]
Nobody's going to work on it, sorry.

The remotest possibilities include either modifying ReactOS (which is still in alpha status and probably will never reach the potential of running many games), or get Wine working better.

**Comment by clementgallet** [comment]
There is tentative support for wine, but there's a lot of work for it to be stable.
