### ISSUE TITLE
LibTAS freezes entire computer

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#282]
Ways to reproduce:

When playing back input and making and encode, if the game window is focused on, it will shortly freeze the entire machine. To get around this is to not have the game window focused and just on the libtas window.

Another way: lets say youre fixing a crash or a mistake by replaying an input file up to said point and you go back to the libtas window to switch to recording and back to the game window to make a save state and load it. And this will also freeze the entire machine forcing you to hold down the power button to shut it down. And no work around for this.

Running ubuntu 19.04

**Comment by clementgallet** [comment]
Could you reproduce this with any game, even non-wine games?

**Comment by InfamousKnight** [comment]
I didnt test it on wine. I tested it on citra. Wine is too instable. I
could test it on other simple games too like bsu chromium(I think thats how
its spelled)

**Comment by InfamousKnight** [comment]
Ill test more tomorrow or tonight

**Comment by InfamousKnight** [comment]
Thanks, now they both were fixed. I can now click in and out the window, and append the movie by switching to recording and making a save state and then loading it. Funny how this is more severe than my last issue was!
