### ISSUE TITLE
Some builds of Super Win the Game do not output sound

### ISSUE THREAD

**Issue by ToonLucas22** [clementgallet/libTAS#284]
On the newest interim versions of libTAS, any Linux builds of Super Win the Game from June 4th, 2015 or older do not output sound in libTAS even with Sound > Mute unchecked. This carries over to any encoding attempts as well, with an invalid stream error being printed out in the console. Sound works fine in these builds when ran by themselves. All builds newer than that work fine in libTAS.

I once even got a random crash on startup too, which in turn prompted up an Ubuntu internal error message. Here's the extract from the console log:

> [libTAS f:0] Thread 13911 (main) ERROR:   Cannot open default audio device
SuperGame_NFML: pcm_params.c:2290: snd_pcm_hw_refine: Assertion `pcm && params' failed.
Got unknown message!!!

Side note: I am downloading the builds using this webpage: [https://steamdb.info/depot/310702/manifests/](url) and inputting the manifest ids into the Steam console. I had to copy libsteam_api.so to one of my local shared library folders by using sudo in the terminal to get permissions to write to the folders to get the game to run outside of the Steam launcher (both by itself and in libTAS), otherwise it'd spit a "no such file or directory" error. This is not related to libTAS but just an FYI for people attempting to reproduce this or otherwise boot up the game in libTAS.

**Comment by ToonLucas22** [comment]
Apparently this is caused by the game using Pulseaudio on the older builds. https://steamcommunity.com/app/310700/discussions/0/615086038667559976/

Note that the date ALSA support was said to be added to the main branch (according to the game creator's last comment on the thread) is the same as that of the first build with working audio in libTAS.

**Comment by ToonLucas22** [comment]
Another update regarding what might possibly be the root problem:
I was having trouble getting the game audio to work when ran by itself on my new-ish computer I got ever since I opened this report until I installed libasound2-plugins:i386.
Sound still does not work when letting the game run in libTAS. Running the game with gdb attached yields the following warning:

> aviso: Error reading shared library list entry at 0x7b80
> aviso: Error reading shared library list entry at 0x7b80

I presume whatever is causing the error has to do between libasound2-plugins:i386 and libTAS.

**Comment by clementgallet** [comment]
As you said it yourself, older builds are using PulseAudio, which is not supported by libTAS.

**Comment by ToonLucas22** [comment]
Is pulseaudio support planned in the future or is it a no-go?

**Comment by clementgallet** [comment]
Pulseaudio has a very complicated API. I once implemented a part of it (pulseaudio simple mainly), but it interfered with the actual audio output. I'm not sure I will implement it, as it is very rarely directly used by a game. Most games will use an intermediate audio library that outputs using one of the available audio drivers of the system.

**Comment by clementgallet** [comment]
As I read again the linked post from Steam forum, it appears the game uses SDL whose audio should be supported.
