### ISSUE TITLE
Old LD_PRELOAD is not preserved by libTAS

### ISSUE THREAD

**Issue by clementgallet** [clementgallet/libTAS#286]
We should support users wanting to launch a game with a custom LD_PRELOAD (in addition to our libtas.so preload)

**Comment by clementgallet** [comment]
Fixed in 4ead08c8654638cf3f71ce48b57c553f6991aef3

**Comment by InfamousKnight** [comment]
I don't really understand this feature. Could you elaborate?

**Comment by clementgallet** [comment]
If a user wants to launch a game with a preloaded library in libTAS, they can now. Users may want to preload a library to fix a crash in a game, to add a feature, or to increase performance.
