### ISSUE TITLE
Could not import symbol swr_alloc with Citra

### ISSUE THREAD

**Issue by eadmaster** [clementgallet/libTAS#287]
when running libTAS with Citra from [this repo](https://launchpad.net/~samoilov-lex/+archive/ubuntu/retrogames) i get this error:
````
[   0.000000] Audio.DSP <Warning> audio_core/hle/hle.cpp:Impl:95: No decoder found, this could lead to missing audio
[libTAS f:0] Thread 11260 (main) ERROR: Could not import symbol swr_alloc
Got unknown message!!!
````

**Comment by availableRadu** [comment]
I got this error too, the geme is starting loading and then...
![error](https://user-images.githubusercontent.com/58659697/70390585-927e6080-19cc-11ea-9b75-e7289e9835cb.png)

**Comment by clementgallet** [comment]
Assuming you have libswresample installed, could you look into your lib folder (`/usr/lib/x86_64-linux-gnu` for me) for the `libswresample.so` file? If you only have the full name library (`libswresample.so.3.3.100` for me) and the sym link with the major version (`libswresample.so.3` for me), could you try creating the `libswresample.so` sym link file (for me it would be `sudo ln -s libswresample.so.3 libswresample.so`) and tell me if it is fixing the issue?

**Comment by availableRadu** [comment]
I installed libswresample.so , .so.2 , so.2.9.100 , so.3 , so.3.3.100 and when I try to do the symbolic link but it says "failed to create symbolic link './libswresample.so': File exists" and even if I remove libswresample and I retry "sudo ln -s libswresample.so.3 libswresample.so" it reinstall the library and does the same error again. Of course, the game (Undertale) still crashes a few seconds after it opens with the same error message.

**Comment by clementgallet** [comment]
Sorry, if it's for Undertale, it's a 32-bit game, so you should do the same in the lib32 directory (`/usr/lib/i386-linux-gnu` for me).

**Comment by Depa31** [comment]
Thanks! I had the same problem to launch Undertale.
Now it works fine :)

**Comment by eadmaster** [comment]
i've tried that again with citra and now the error is:
````
[   0.000000] Loader <Error> core/loader/loader.cpp:GetLoader:126: Failed to load file "/r/witch.3ds"
[   0.000000] Core <Critical> core/core.cpp:Load:98: Failed to obtain loader for "/r/witch.3ds"!
Got unknown message!!!
Attempt 1: Connected.
````
