### ISSUE TITLE
The tool fails to start any steam game

### ISSUE THREAD

**Issue by lebel-louisjacob** [clementgallet/libTAS#289]
I made a `Dockerfile` to automatically setup libTAS (x64 & x86) for me:

```dockerfile
FROM archlinux/base
# libtas
  # dependencies
    # main
      RUN pacman -Sy --noconfirm git
      RUN pacman -Sy --noconfirm base-devel
      RUN pacman -Sy --noconfirm automake
      RUN pacman -Sy --noconfirm pkgconf
      RUN pacman -Sy --noconfirm qt5-base
      RUN pacman -Sy --noconfirm xcb-util-cursor
      RUN pacman -Sy --noconfirm alsa-lib
      RUN pacman -Sy --noconfirm ffmpeg

    # HUD
      RUN pacman -Sy --noconfirm fontconfig
      RUN pacman -Sy --noconfirm freetype2

    # fonts
      RUN pacman -Sy --noconfirm gnu-free-fonts

    # wine
      RUN printf '%s\n' $'[multilib]\n\
Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
      RUN pacman -Sy --noconfirm wine
      
    # i386
      # lib32-alsa-lib
        RUN pacman -Sy --noconfirm lib32-alsa-lib

  # install
    RUN mkdir /root/src
    RUN cd /root/src && git clone https://github.com/clementgallet/libTAS.git
    RUN cd /root/src/libTAS && ./build.sh --with-i386
    RUN cd /root/src/libTAS && make install

  # run
    CMD libTAS
```

I built the image with this command:
```sh
docker build -t libtas path/to/libtas/docker
```

I then start a container using this command:
```sh
docker run --net=host --env="DISPLAY" -v "$HOME/.steam/steam:/root/steam" -v "$HOME/bin/steam:/root/bin/steam" -v "$HOME/.Xauthority:/root/.Xauthority:rw" libtas
```

My problem is that I couldn't succeed to start `libTAS` with any `Steam` game so far. I tried to launch `NieR:Automata`, `Geometry Dash`, `Rocket League`, `Cross Code` and `Portal 2`. I also tried to launch `Steam` itself.

Where did I go wrong?

**Comment by lebel-louisjacob** [comment]
Also -- just an idea: would it be a good idea to add this `Dockerfile` (or a working one) to the master branch? I think it might help people to build `libTAS` when their operating system prevents them to build (I had a hard time with unsatisfied dependencies). I bet people on Windows would also really benefit from this.

**Comment by lebel-louisjacob** [comment]
I realize I forgot to share log information. Currently, `Steam` never launches. Here is the log of trying to start `Geometry Dash`:

```log
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
[libTAS f:0] Thread 459 (main) ERROR: We didn't find any regular TTF font !
0009:err:module:load_so_dll failed to load .so lib "/usr/bin/../lib32/wine/wldap32.dll.so": libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
0009:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"Z:\\root\\bin\\steam\\steamapps\\common\\Geometry Dash\\libcurl.dll") failed (error c000007a).
0009:err:module:import_dll Library libcurl.dll (which is needed by L"Z:\\root\\bin\\steam\\steamapps\\common\\Geometry Dash\\libExtensions.dll") not found
0009:err:module:import_dll Library libExtensions.dll (which is needed by L"Z:\\root\\bin\\steam\\steamapps\\common\\Geometry Dash\\GeometryDash.exe") not found
0009:err:module:LdrInitializeThunk Importing dlls for L"Z:\\root\\bin\\steam\\steamapps\\common\\Geometry Dash\\GeometryDash.exe" failed, status c0000135
Got unknown message!!!
```

As far as I'm concerned, fonts should be installed... Or is the log message referring to `wine`'s fonts?

**Comment by lebel-louisjacob** [comment]
After a glance at the docs, I realized I was missing some settings. However, with the "Virtual Steam client" option checked and the executable and library path setup, I still get the same error as before. Should I understand `Geometry Dash` is not currently supported by the tool?

**Comment by lebel-louisjacob** [comment]
I tried to fix the missing `WLDAP32.dll` (5th line of the log) by setting the library path to `/root/bin/steam/steamapps/common/Proton 4.11/dist/lib/wine` (where an instance of `wldap32.dll` can be found with my setup). Weirdly enough, the dll is still reported as missing.

**Comment by lebel-louisjacob** [comment]
I fixed the missing font by adding this line in the `Dockerfile`:

```dockerfile
    # fonts
      RUN pacman -Sy --noconfirm ttf-ubuntu-font-family
```

So I understand there are no fonts that can be used with the HUD by default with `FROM archlinux/base`.

**Comment by clementgallet** [comment]
Steam wine games are not currently supported (see #264), so "Virtual Steam client" won't do anything. I could add a Dockerfile in the repo, I'm not familiar with this technology to be honest.

I'll look at the fonts issue. libTAS is querying fonts using fontconfig, and picks any .ttf font that is regular and supports en-US.

**Comment by lebel-louisjacob** [comment]
Woops, I completely missed that issue. Thanks for the pointer.

I'm not sure about this, but my guess is that the fonts shiped with `fontconfig` are not `ttf` but `otf` (since they were the only kind of fonts I could find with that setup). What I'm unsure about is if they're not in fact shiped by default with `base/archlinux` or with `freetype2`.

Checking this when I have time.

**Comment by clementgallet** [comment]
I added a Dockerfile and instructions to use it on Windows (096d03de5bd9a4efe0ecf632426516d7f69c19c5). Now I have issues with using OpenGL in games. It doesn't use Mesa even if I installed it, and has so little OpenGL extensions available that games cannot launch
