### ISSUE TITLE
Sometimes the game window doesn't reopen after a restart

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#293]
This makes it so you can't frame advance
[any%v1-sl.zip](https://github.com/clementgallet/libTAS/files/4015405/any.v1-sl.zip)
Here is an input file for meatboy where it happens (frame 6702)

**Comment by Matte27** [comment]
Same happens if the auto-restart game is unchecked.

**Comment by clementgallet** [comment]
Could you check if it is fixed by fixing #294 ?

**Comment by Matte27** [comment]
Seems to be.
