### ISSUE TITLE
libTAS sometimes leaves the game running on the background after stopping it

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#294]
Happens frequently with Super Meat Boy.

**Comment by clementgallet** [comment]
Does this happen when you stop the game in a specific way (stop button, or closing the game window, or exiting the game via menu)?

**Comment by Matte27** [comment]
When using the stop button. Also the stop button sometimes turns into the kill button after pressing it. This didn't happen in the previous version I used. Maybe it is related.

**Comment by clementgallet** [comment]
When the stop button turns into the kill button, it means that libTAS didn't manage to close the game nicely, so that you need to press "kill" to force close it.

**Comment by clementgallet** [comment]
94e821678ad7412e661151db6f10350c0f40c3c6 should fix the game softlocking on exiting.

**Comment by Matte27** [comment]
Haven't had this issue anymore so I think this can be closed
