### ISSUE TITLE
libTAS crashes when making a new ram search in Super Meat Boy

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#300]
Happens every time I try to make a new ram search. 

Message to the command line:
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
Aborted (core dumped)

Version: Interim commit 03e9488 built on 2020-01-07

Duplicate of https://github.com/clementgallet/libTAS/issues/46

**Comment by clementgallet** [comment]
Does it happen whatever the search parameters you are setting?
Could you try an empty search (no memory region), or a search with few results (such as RW Data alone)?

**Comment by Matte27** [comment]
Looks like heap is the problem, the other regions seem to work fine.

**Comment by clementgallet** [comment]
RAM Search will be rewritten (#268)
