### ISSUE TITLE
Escape Goat crashes when audio starts

### ISSUE THREAD

**Issue by danflapjax** [clementgallet/libTAS#305]
I'm trying to run the DRM-free version of Escape Goat from Humble Bundle with libTAS v1.3.5 on Ubuntu, and it crashes every single time after frame 103, right when audio starts during the developer logo intro.

[Logs](https://gist.github.com/danflapjax/8abdcce9b36bb15f116a57721f98689f)

**Comment by clementgallet** [comment]
Hey,

Thanks for the logs, it should be fixed in the current master version, you could try it easily using the automated build linked in the Readme.

**Comment by danflapjax** [comment]
Yep, that fixed it. Thanks for the help!
