### ISSUE TITLE
Input Editor nearly unreadable with dark themes.

### ISSUE THREAD

**Issue by Lyle-Tafoya** [clementgallet/libTAS#308]
When using a dark Qt theme ("Materia Dark" in my case), the Input Editor text becomes very difficult to read. What I am seeing is a light grey text on a various light colored backgrounds (ie. light green for past frames, light blue for current frame, and light tan for future frames). It would be much more readable with black text or darker colored background colors.

**Comment by lexikiq** [comment]
![image](https://user-images.githubusercontent.com/13265322/76156296-791dab00-60c6-11ea-888e-d916b12504c8.png)

**Comment by clementgallet** [comment]
Input editor colors are now adapted from the theme background. It's not very pretty though (ce51970)

**Comment by Lyle-Tafoya** [comment]
That is a huge improvement. Thank you.
