### ISSUE TITLE
Blocking on /dev/urandom

### ISSUE THREAD

**Issue by clementgallet** [clementgallet/libTAS#310]
Seen on Dead Cells, but other games will be affected. We need to hook when the game is reading into /dev/urandom, for now we create a file on memory and fill it with deterministic stuff (using system time so we can manipulate its content). However, /dev/urandom is supposed to be non-blocking, so we must feed enough bytes to the game, which is not the case for Dead Cells.

**Comment by kitlith** [comment]
so, there's fopencookie, which allows us to create our own FILE* stream defined with callbacks -- we could probably emulate urandom with that. However, i don't think that helps with the posix side of things. Perhaps we could emulate it with pipe/socketpair, since those give us fds?

**Comment by clementgallet** [comment]
For posix functions, looking at fcntl man page, I can see two possibilities:
- use a pipe with a small buffer, set O_ASYNC on the fd and F_SETOWN, so that the kernel will send  a SIGIO signal to the process when data can be written to the pipe.
- use F_NOTIFY on a file with DN_ACCESS, which will send a SIGIO signal when the file is accessed.

I feel the first solution is better.

**Comment by clementgallet** [comment]
Implemented the first solution.
