### ISSUE TITLE
Undertale 1.08 Linux Version Crash

### ISSUE THREAD

**Issue by ShiroParadox** [clementgallet/libTAS#312]
I downloaded linux version Undertale 1.08 from gog. Undertale crashes when I use file "runner" with LibTAS 1.3.5.

**Comment by clementgallet** [comment]
Are you getting any error message? (You need to open libTAS through a terminal to see these messages. Open a terminal and type `libTAS`).

Also, Undertale is a GameMaker Studio game, and if you downloaded it through Steam, you need extra steps described in the [following page](http://tasvideos.org/EmulatorResources/libTAS/GameCompatibility.html) under GameMaker Studio.

**Comment by ShiroParadox** [comment]
I already solved. I just used libs 'sudo apt-get install libxxf86vm1:i386 libglu1-mesa:i386 libopenal1:i386 libssl1.0.0:i386 libxrandr2:i386' and libtas 1.3.4 i386. But thanks.
