### ISSUE TITLE
[Wine] A Hat in Time crashing libTAS

### ISSUE THREAD

**Issue by doesthisusername** [clementgallet/libTAS#313]
I'm trying to get [A Hat in Time](https://store.steampowered.com/app/253230/A_Hat_in_Time/) to work with libTAS, however there are some issues. I've tried to understand what's going on, but I'm not very familiar with how libTAS achieves what it does.
I've verified that the game will launch under Wine normally (`wine HatinTimeGame.exe`), even without Steam running.

### Choosing game exe directly
If I run
`$ libTAS $HOME/apps/hat/dlc2.1/Binaries/Win64/HatinTimeGame.exe`
then just start the game once libTAS has launched, it crashes less than a second after hitting Start, with the following log:
```
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Interim commit 99ca68f built on 2020-03-14
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
```

the RDRND warning is probably because I'm using a Zen 2 CPU; most QT applications emit that warning.

If I click "Start and attach gdb" instead, I don't get much more than
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a3ca05 in ?? ()
```
at the end (I don't know if this is libTAS or the game crashing).

I've tried tweaking settings as well, with no discernible effect (Uncontrolled time, Native events, Keep main thread, in particular).

If I include every print category, this is the log:
```
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Interim commit 99ca68f built on 2020-03-14
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
[libTAS f:0] Thread 37894 (main) Imported symbol clock_gettime function : 0x7ffff7c44180
[libTAS f:0] Thread 37894 (main) time call.
[libTAS f:0] Thread 37894 (main)   returning 1584216833
[libTAS f:0] Thread 37894 (main) Imported symbol access function : 0x7ffff7c6d620
```

Ticking `clock_gettime()` does not seem to have an effect.

## Choosing wine64 with game exe as argument
If I run
`$ libTAS /usr/bin/wine64`
then the game will show its splash screen for about five seconds, before also crashing and closing libTAS (the libTAS closing seems to be explicitly done in libTAS. If I comment it out, it will spam the console _very_ quickly with that same unknown socket message, splash screen never going away).

Here is the log:
```
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Interim commit 99ca68f built on 2020-03-14
Attempt 1: Connected.
[libTAS f:0] Thread 38664 (main) ERROR: Unknown socket message -154878781
000f:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 1053
0009:err:module:load_so_dll failed to load .so lib "/usr/bin/../lib/wine/l3codeca.acm.so": libmpg123.so.0: cannot open shared object file: No such file or directory
0009:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
003a:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000620FDA0
0009:fixme:gameux:GameExplorerImpl_VerifyAccess (00000000009F2EA0, L"Z:\\home\\dtu\\apps\\hat\\dlc2.1\\Binaries\\Win64\\HatinTimeGame.exe", 00000000005FEE40)
[libTAS f:0] Thread 38629 (main) ERROR: Unknown socket message -134432288
```

Looking at similar issues, #241 might be similar, (the loading `load_so_dll` line), but I'm not seeing any audio stuff in the backtrace.
Hopefully this is legible, thanks!

**Comment by clementgallet** [comment]
Wine is at unsupported state, due to how difficult it is to debug, as well as to maintain through updates.
