### ISSUE TITLE
configure: error: Some xcb headers are missing!

### ISSUE THREAD

**Issue by EV3R4** [clementgallet/libTAS#318]
Hi, when i run `./build.sh` i get the error `configure: error: Some xcb headers are missing!` altough xcb is installed.
I searched for a long time but i couldn't find a solution.

Here is the output of the program:
[configure error.txt](https://github.com/clementgallet/libTAS/files/4528974/configure.error.txt)

OS: Raspbian Desktop
Thanks in advance!

**Comment by clementgallet** [comment]
You need `libxcb-randr0-dev` package, and I forgot to add it to the readme apparently.

**Comment by EV3R4** [comment]
Thanks for the reply!
But now it says `configure: error: Some X11 headers are missing!`.
The libx11-dev is installed.
Did you forgot more packages?

**Comment by clementgallet** [comment]
Could you post the last lines of the configuration?

**Comment by EV3R4** [comment]
```
checking for ffmpeg... no
checking for library containing dlopen... -ldl
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
checking X11/Xlib-xcb.h usability... no
checking X11/Xlib-xcb.h presence... no
checking for X11/Xlib-xcb.h... no
configure: error: Some X11 headers are missing!
```

**Comment by clementgallet** [comment]
You need also package `libx11-xcb-dev`, sorry about that.

**Comment by EV3R4** [comment]
I think it would build with this packages on other systems but it says `"Unsupported arch"`.
But thanks for the reply!
