### ISSUE TITLE
Garbage appended to path detected by game running under libTAS

### ISSUE THREAD

**Issue by NarryG** [clementgallet/libTAS#32]
I'm attempting to use a Gamemaker based game (Undertale) and at launch, the console prints out some info. One of the things printed out is the "ExeName" parameter, 

When running the game by itself, it's fine

```
***************************************
*     YoYo Games Linux Runner V1.3    *
***************************************	 
CommandLine: -game game.unx
ExeName= /home/daniel/Downloads/depot_391544/runner
MemoryManager allocated: 1723148
INI DisplayName=UNDERTALE
SavePrePend /home/daniel/.config/UNDERTALE/ 
```

When running the game under libTAS, there's a large amount of garbage appended to the path.

```***************************************
*     YoYo Games Linux Runner V1.3    *
***************************************	 
CommandLine:  -game game.unx
ExeName= /home/daniel/Downloads/depot_391544/runner#��������&S6#��������&T6#��������&T6#��������&T6 #��������&T6"#��������&T6$#��������&T6&#��������&T6(#��������&U6*#��������&U6,#��������&U6.#��������&U60#��������&U62#��������&U64#��������&V66#��������&V68#��������&V6:#��������&V6<#��������&V6>#��������&V6?#��������&V6A#��������&W6C#��������&W6E#��������&W6G#��������&W6I#��������&W6K#��������&W6M#��������&W6O#��������&W6Q#��������&X6S#��������&X6U#��������&X6W#��������&X6Y#��������&X6[#��������&X6\#��������&X6^#��������&Y6`#��������&Y6b#��������&Y6d#��������&Y6f#��������&Y6h#��������&Y6j#�������&Y6l#�������}&Y6n#�������{&Z6p#�������y&Z6r#�������w&Z6t#�������v&Z6v#�������t&Z6x#�������r&Z6y#�������p&Z6{#�������n&Z6}#�������l&[6#�������k&[6�#�������i&[6�#�������g&[6�#�������e&[6�#������c&[6�#�������a&[6�#�������_&[6�#�������^&[6�#�������\&\6�#�������Z&\6�#������X&\6�V&\6�#�������
            T&\6�#�������
R&\6�#�����Q&\6�#������O&\6�#������M&\6�#�������K&]6�#�������I&]6�#�������
MemoryManager allocated: 1723572
INI DisplayName=UNDERTALE
SavePrePend /home/daniel/.config/UNDERTALE/
```  

The game proceeds to get through the splash screen then hangs indefinitely when the main thread is launched. I'm unsure if the crash is related to this issue. Do you want game and engine specific crashes as issues at this point in development?

**Comment by clementgallet** [comment]
GameMaker games are not supported right now. The main reason is that the way the engine sleeps at each frame to get the correct framerate is by looping and getting the system time until it reaches a certain value. However, the tool only advances the time on frame boudaries (when the game draws on screen), so the game softlock.

You should be able to make the game running by checking in menu "Time tracking>Main thread>clock_gettime" or other items in "Main thread". When this hack is enabled, the tool will advance time by 1 ms for every hundred calls of the corresponding function by the main thread, to prevent the game from freezing in this particular scenario.

**Comment by clementgallet** [comment]
The ExeName now prints correctly, maybe by changing the exec* function used and how arguments are passed. Also, the game runs correctly by setting "Time tracking>Main thread>clock_gettime"
