### ISSUE TITLE
libTAS does not hook ruffle properly

### ISSUE THREAD

**Issue by Futurama39** [clementgallet/libTAS#321]
Running on VM 64-bit linux any flash files launched using [ruffle ](https://github.com/ruffle-rs/ruffle) and libTAS do not appear to have any control in libTAS like pausing or frame advance

**Comment by lexikiq** [comment]
> when i launch the file and all throughout
> libTAS says it's still on frame 0
> and frame advance, pause and such do not seem to be working

**Comment by clementgallet** [comment]
ruffle main thread is softlocking on `epoll_wait()`. It is possible that this function is used for sleeping (and timeout is 33 ms, which is possible the frame length).

**Comment by clementgallet** [comment]
I could run a game after commits d6cbdcda10bc51a269330e03337ce473b0f2f70e and ca123416dea4db25c08ffd46e003f2e8ca749c70, with `Runtime > time tracking > clock_gettime`. 

Still a few issues to look at:
- no HUD
- Doesn't work with software opengl rendering: `Received multiple errors. Errors: [NoAvailablePixelFormat, NoAvailablePixelFormat]`
- audio still not working: `ERROR ruffle_desktop] Unable to create audio device: Unable to create audio stream`

**Comment by Futurama39** [comment]
I have managed to make openGL work via ruffle's [issue #384](https://github.com/ruffle-rs/ruffle/issues/384) that instructed to comment out a line and compile from there

the audio not working is an ongoing thing [with ruffle on it's own](https://github.com/ruffle-rs/ruffle/issues/10)

**Comment by vadosnaprimer** [comment]
Can this be closed?
