### ISSUE TITLE
Pause checkbox is inconsistant at a game startup

### ISSUE THREAD

**Issue by clementgallet** [clementgallet/libTAS#325]
Some games can start paused even if pause is unchecked. Also (often after a crash), games can run for several frames before pausing when checkbox is checked.

**Comment by YaLTeR** [comment]
What I'm currently seeing with HL is that if I uncheck pause, start HL, (it starts unpaused as it should), then stop and kill it, (pause checkbox is still not checked), then start HL again, the pause checkbox gets checked automatically and it gets paused.

**Comment by clementgallet** [comment]
Should be fixed now. Hotkeys that were not processed (on a frozen game for example) were kept for the next game execution. Now we clear the event queue at the beginning of the game execution.
