### ISSUE TITLE
Cannot put spaces in arguments to game

### ISSUE THREAD

**Issue by InfoTeddy** [clementgallet/libTAS#333]
Looks like shlexing in libTAS command-line arguments is non-existent, and thus you cannot put spaces in arguments to games, because libTAS splits the "Command-line options" string by spaces with no regard for shlexing.

**Comment by leo60228** [comment]
Shlexing is a deceptively difficult problem (Python's `shlex` is a few hundred lines). The following process should allow it to be sidestepped entirely:
1. Make an argument array
2. Put `exec` at the beginning
3. Add arguments from libTAS the same as today (https://github.com/clementgallet/libTAS/blob/42573cf0fdc391fda7426d6624758844f7e1ad48/src/program/GameLoop.cpp#L141-L250)
4. Escape it by replacing `'` with `'\''` in each element, surrounding them with `'`, and concatenate them with spaces. This is inefficient, but it's very simple and will always work.
5. Append the user-provided argument string to the end
6. Execute it with something like `execlp("sh", "sh", "-c", arg_str, nullptr)`. Note that POSIX specifically says that applications should use PATH to locate sh.

**Comment by clementgallet** [comment]
I've read about using sh? Is it safe with using LD_PRELOAD? Does it spawn an intermediate process before the game executable?

**Comment by leo60228** [comment]
It does. You could either have the .so ignore `sh` (I'm not sure why anyone would want to TAS it), or set the variable within `sh` by prepending `LD_PRELOAD=value`.

**Comment by InfoTeddy** [comment]
2ef00d295886883724013e9409829add28f48ee1 fixes this for me. (Btw @clementgallet you can type something like "Fixes #333" or "Closes #333" in a commit message to automatically close an issue with a commit.)

**Comment by clementgallet** [comment]
Ok, thanks!
