### ISSUE TITLE
Input editor should not be always on-top

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#334]
The input editor window is always on-top of the libTAS main window which is annoying.

**Comment by clementgallet** [comment]
Fixed, but now closing the main window won't close the input editor window.

**Comment by YaLTeR** [comment]
The input editor and the controller inputs windows are still always on-top of the main window for me on 337fc9c6cd1248f9830a38d8174b48a7fb3ee613.

**Comment by clementgallet** [comment]
Now the input editor is derived from `QMainWindow` (c1fd2728e07d6f6f819f99e515fd79b0ca376f67), so you can put either window on top of the other one.
