### ISSUE TITLE
Half-Life 1 initial map load is not deterministic

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#341]
The load after initially typing `map something<Return>` in the console varies in length for me, so far I saw 1 frame longer and 1 frame shorter than the "usual" time at 250 FPS.

**Comment by clementgallet** [comment]
There is loading done in a separate thread using the Steam API, I should implement some of the Steam API features.

**Comment by clementgallet** [comment]
Implemented SteamGameServer in b6cd434f7d10cbaa8a9f8e23d75c34850ecec2d5. Now the level loading does not spawn any additional thread, which may fix the issue.
