### ISSUE TITLE
0,0 FPS gets saved as T0:0 and interpreted as 0 / 0

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#343]
It should be interpreted as no FPS set. Right now there's no way to reset the FPS if you entered it.

**Comment by clementgallet** [comment]
Not exactly sure what you mean by your second sentence. Now a 0/0 framerate (written in the input editor) will be read as default framerate, and won't be saved in movie (as it is equivalent to default framerate).

**Comment by YaLTeR** [comment]
Not sure which sentence you mean with "second sentence". :) Anyway this sounds like what I would expect from a fix.
