### ISSUE TITLE
The UI should update every displayed frame

### ISSUE THREAD

**Issue by YaLTeR** [clementgallet/libTAS#346]
A recent commit made it update every 100 ms for performance, but that looks pretty bad and is actually inconvenient for diagnosing issues by looking at the input display and the game at the same time. It should rather update every displayed frame (that would be 60 FPS on 60 Hz monitor and 144 FPS on 144 Hz monitors, etc.).

Wayland offers frame callbacks ("please draw right now") for this purpose, X might have a similar functionality, so I imagine Qt likely exposes it in some way which should be used for this.

**Comment by clementgallet** [comment]
Yeah, this was a test. I'm a bit confused about the performance hit for this. I noticed that Half-Life is running slowly, and it drops from 70 fps to 50 fps with just the input editor opened.
After that update, I'm getting about 65 fps with the input editor opened. All this done with the nouveau Nvidia driver (so much slower than the proprietary driver, but still hardware accelerated).

However, if I take another game like Shovel Knight, without the refresh change above, I can hit about 1000 fps with input editor opened. So Qt can handle fine a very fast refresh rate.

**Comment by YaLTeR** [comment]
For me (AMD RX 580, but HL running through llvmpipe with "Force software rendering") it went from like 35 FPS to like 45 FPS after this change, so not really worth it for such a drastic visual change.

**Comment by clementgallet** [comment]
If I run the game natively, enforces a host_frametime of 0.001, the real fps is about 250-350, so there's some slowdown caused by libtas somewhere.

**Comment by clementgallet** [comment]
I changed this again due to MacOS UI refresh being very slow. Now it updates every frame but not faster than X ms (e649b77a8e352be27450ee622961b50062159feb)
