### ISSUE TITLE
Game crashes unless you run it with Sound->mute on

### ISSUE THREAD

**Issue by MuoDoo** [clementgallet/libTAS#348]
OS:5.3.0-3-amd64 #1 SMP deepin 5.3.15-6apricot (2020-04-13) x86_64 GNU/Linux
libTAS version : 1.3.5
If you uncheck Sound->mute , game(Undertale for me) crashes when the sound is played.
libTAS echo this : 

> [libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:183] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[New Thread 0xaba5b40 (LWP 18400)]
Texture #3 1024,2048
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18374 (main) ERROR: Could not import symbol av_opt_set_sample_fmt

And if I use Tools->Start encode it will crash at f:184 (same as above) 
but it gives different echo as:
> [libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_int
[libTAS f:184] Thread 18578 (main) ERROR: Could not import symbol av_opt_set_sample_fmt
Thread 1 "runner" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) q
A debugging session is active.
	Inferior 1 [process 18578] will be killed.
Quit anyway? (y or n) y
[rawvideo @ 0x5555555dcf40] Invalid buffer size, packet size 1225126 < expected frame_size 1228800
Error while decoding stream #0:0: Invalid argument
frame=  183 fps= 13 q=-1.0 Lsize=    2830kB time=00:00:06.13 bitrate=3779.7kbits/s speed=0.429x    
video:1755kB audio:1057kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.656155%
[libx264rgb @ 0x5555555e83c0] frame I:183   Avg QP: 0.00  size:  9820
[libx264rgb @ 0x5555555e83c0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264rgb @ 0x5555555e83c0] coded y,u,v intra: 2.3% 2.3% 2.3%
[libx264rgb @ 0x5555555e83c0] i16 v,h,dc,p: 90%  7%  3%  0%
[libx264rgb @ 0x5555555e83c0] kb/s:2356.68
Got unknown message!!!

**Comment by clementgallet** [comment]
Open a console: `cd /usr/lib/i386-gnu-linux/` then try `ln -s libavutil.so.56 libavutil.so`. If it gives an error message, replace 56 with 55.

**Comment by LukeSaward1** [comment]
It crashes for me as well, but doesn't throw the error, and don't mind TASing with sound off anyways.

**Comment by MuoDoo** [comment]
The problem solved with `ln -s libavutil.so.56 libavutil.so`
Also find this.May be helpful to others.
[http://tasvideos.org/forum/viewtopic.php?p=490172#490172](http://tasvideos.org/forum/viewtopic.php?p=490172#490172)
