### ISSUE TITLE
The tool adds an extra frame to the end of the input file when closing the game

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#35]

**Comment by clementgallet** [comment]
This was fixed for when the game is closed using the "Stop" button (f13d037bb9e418b1371c0e61dd39eb1380c8ba41)

**Comment by Matte27** [comment]
The movie length increases by 0.02s after starting the game, probably not the intended behaviour

**Comment by clementgallet** [comment]
It is intended. Already one frame has passed from game startup to the first screen draw, so the movie length is 0.016s (rounded to 0.02s on the GUI).

**Comment by Matte27** [comment]
I mean the total length of the movie file

**Comment by clementgallet** [comment]
Remove the movie length parameter from movies and rely on framecount and framerate to compute the actual movie length (ff8f6db2e8ccad3a1293510770d170d1db379a8a)
