### ISSUE TITLE
Stuck on Unity Configuration screen

### ISSUE THREAD

**Issue by JAcamp1** [clementgallet/libTAS#356]
Most in development Unity games, indie or other, have a splash screen that allows you to change settings before booting into game. After booting libTAS and starting up the game, Karlson for those interested, it doesn't allow me to progress frames or access the menus on the splash screen. I need a way to either bypass this screen without bothering the programmer, or the ability to interact with this splash screen.

**Comment by clementgallet** [comment]
You can remove/rename the ScreenSelector.so file, then the game should proceed without showing the splash screen.

**Comment by JAcamp1** [comment]
Great! That fixed the issue. Thanks again for making such a nice program.
