### ISSUE TITLE
Super Meat Boy Doesn't Launch When Pressing Start 

### ISSUE THREAD

**Issue by ACrowIAm** [clementgallet/libTAS#36]
For some reason when i press Start on libTAS it doesn't launch Super Meat Boy And I Have Selected The Game In The "Game executable" box Please help i have Ubuntu 17.10

**Comment by ACrowIAm** [comment]
This is what it said on the terminal after trying to click the start button on LibTAS

acrowiamgaming@ubuntu:~$ '/home/acrowiamgaming/Desktop/linTAS' 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/home/acrowiamgaming/supermeatboy/SuperMeatBoy-amd64: symbol lookup error: /home/acrowiamgaming/Desktop/libTAS.so: undefined symbol: XGetXCBConnection
Attempt 1: Couldn't connect to socket.
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Couldn't connect to socket.
Attempt 5: Couldn't connect to socket.
Attempt 6: Couldn't connect to socket.
Attempt 7: Couldn't connect to socket.
Attempt 8: Couldn't connect to socket.
Attempt 9: Couldn't connect to socket.
Attempt 10: Couldn't connect to socket.
Got unknown message!!!

**Comment by clementgallet** [comment]
Try installing the package `libx11-xcb1`

**Comment by ACrowIAm** [comment]
Oh i didn't see the mandatory dependencies at the bottom of the Code Page Ill try to install them and ill edit this post if it worked or didn't work

**Comment by ACrowIAm** [comment]
now i can't install any packages it just says --fix-missing so tried to run apt-get install --fix-missing and it didn't fix anything

**Comment by ACrowIAm** [comment]
bump

**Comment by ACrowIAm** [comment]
anyone????

**Comment by ACrowIAm** [comment]
Can't get it to work even tried to install Ubuntu on my actual computer still got the XGetXCBConnection error. am i supposed to install XGetXCBConnection or something? i also tried VVVVVV again and it said i'm missing a library but i'm not. Sorry i'm replying so much its just that its taking a while for you to respond.

**Comment by clementgallet** [comment]
I removed the use of XGetXCBConnection. You should be able to run the game by compiling from the latest version.

**Comment by ACrowIAm** [comment]
YES! that fixed the problem but now it just says "couldn't connect to socket." when trying to start it up /home/acrowiam/Pictures/Screenshot from 2018-04-21 20-42-22.png

**Comment by clementgallet** [comment]
You can buy a drm-free version of Meat Boy on the Humble Store. Also, I think Meat Boy is one of the games that you can launch with Steam closed and it will work (and won't launch Steam). At least it works that way for the Windows version.

**Comment by ACrowIAm** [comment]
Sorry that i keep saying issues but there is another issue with VVVVVV where when you load a save state it freezes the game but again it might just be my version of it.
