### ISSUE TITLE
(Recent) Godot games fail to load

### ISSUE THREAD

**Issue by lexikiq** [clementgallet/libTAS#361]
commit: 5471b777fdd41087281fe6f9c7d60f36255e4d83

games tested:
- https://geegaz.itch.io/out-of-controls (godot v3.2.1)
- https://fedevgd.itch.io/the-maze (v3.2.2)
- [other random free games](https://itch.io/games/last-30-days/platform-linux/tag-godot)

```
Attempt 1: Connected.
Godot Engine v3.2.1.stable.official - https://godotengine.org
[libTAS f:0] Thread 420534 (main) OpenGL vendor: NVIDIA Corporation
[libTAS f:0] Thread 420534 (main) OpenGL renderer: GeForce GTX 1660 SUPER/PCIe/SSE2
XIO:  fatal IO error 17 (File exists) on X server ":0"
      after 28 requests (28 known processed) with 0 events remaining.
[libTAS f:0] Thread 0 (main) ERROR: send() returns -1 with error Broken pipe
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 28 requests (28 known processed) with 0 events remaining.
[libTAS f:0] Thread 0 (main) ERROR: send() returns -1 with error Broken pipe
```

no window ever opens

a [much older game](https://ourealabs.itch.io/godot-jam-dungeon-run) from jan. 2017 appears to load and run fine, though i didn't extensively test

**Comment by clementgallet** [comment]
Looking into gdb and at Godot's code, the engine uses forked processes (without exec) as part of execution (see https://github.com/godotengine/godot/blob/master/platform/linuxbsd/detect_prime_x11.cpp), and libtas does not like this (at least for socket communication between game and program).

**Comment by InfoTeddy** [comment]
Does the latest commit 499fd07a44d35aabe7ff02275bd9907bab93893a improve behavior with these games?

**Comment by lexikiq** [comment]
unfortunately not, same error(s) as before
```
Interim commit 499fd07 built on 2020-08-13
Icon theme "deepin" not found.
Attempt 1: Connected.
Godot Engine v3.2.1.stable.official - https://godotengine.org
[libTAS f:0] Thread 500645 (fork) OpenGL vendor: NVIDIA Corporation
[libTAS f:0] Thread 500645 (fork) OpenGL renderer: GeForce GTX 1660 SUPER/PCIe/SSE2
XIO:  fatal IO error 17 (File exists) on X server ":0"
      after 28 requests (28 known processed) with 0 events remaining.
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 28 requests (28 known processed) with 0 events remaining.
```

**Comment by clementgallet** [comment]
`out-of-controls` working with the last two commits (fd46d4f4ef711fbd41964cc27b0e3e36eb05283d and fe7b8ddbdba76bdf99afbdb776745447ef88ee11). Default audio driver seems to be pulseaudio, so by default audio is not hooked. The engine also implements ALSA audio driver, so there should be a setting or command-line option to use ALSA instead.

**Comment by lexikiq** [comment]
running the game with `--help` shows all the options which includes `--audio-driver ALSA`, though it seems to cause the game to freeze on frame 0 when used in libTAS

loading savestates seems to cause stack smashing, though that could also be because i'm running unsupported graphics drivers?
```
*** stack smashing detected ***: terminated
recv() 0 bytes instead of 4
Got wrong message after state loading
```

thanks for working on this by the way ^^

**Comment by InfoTeddy** [comment]
No, the stack smashing when loading savestates is probably #359. As a workaround, just disable savestate compression for now.

**Comment by lexikiq** [comment]
Ah, correct guess! That fixes it. Won't close this issue yet though as the ALSA hang remains.

**Comment by clementgallet** [comment]
Commit 3904615 should fix the alsa driver output.

**Comment by lexikiq** [comment]
awesome, can confirm it works as expected! only issue left is there's still savestate smashing with compressed savestates enabled, but i'm guessing that's not related to godot in any way

**Comment by InfoTeddy** [comment]
Yes, that's unrelated, and #359 has been fixed anyways if you're on the latest commit.

**Comment by lexikiq** [comment]
i'm on latest commit and still experiencing the issue.

**Comment by InfoTeddy** [comment]
Weird - could you try VVVVVV? That's the game I tried it with, and it works fine for me.
