### ISSUE TITLE
Getting movie length mismatch warning

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#362]
Seems to happen fairly often when editing inputs in the middle of a movie and then going past the last frame of the movie. Also there might be a rounding error related to this as sometimes their difference is some very small number.

![mismatch](https://user-images.githubusercontent.com/14953641/89473635-13743e80-d78c-11ea-8835-3f83e75c0453.png)

**Comment by clementgallet** [comment]
Now the movie length is updated on last frame, and it does not print a popup window
