### ISSUE TITLE
Midtown Madness Open1560 No time Control

### ISSUE THREAD

**Issue by firebingo** [clementgallet/libTAS#366]
I am attempting to run Midtown Madness on wine using the Open1560 project since it has more modern support and allows OpenGL and 32bit color. The game starts and libTAS seems to hook into it but it is not able to control its time at all to pause or allow any input so the game just runs at its menu regardless of pause state etc. The OSD also does not draw over the window. However slow motion and fast forward modes do actually work.

The only errors the logs put out are `ERROR: Could not load QueryPerformanceFrequency` and `ERROR: Could not load QueryPerformanceCounter`. My understanding from the Open1560 dev is that the game does use these but it should fall back to other sys time calls if these don't work. Time tracing in libTAS indicates that clock_gettime and GetTickCount are used at the menu but checking the Time Tracking settings for either of these doesn't change behavior at all.

I have attached a log file with Error, Warning, Info, and Hook turned on. Let me know if you need any more info or logs.
[Open1560.exe.log.zip](https://github.com/clementgallet/libTAS/files/5115533/Open1560.exe.log.zip)

**Comment by clementgallet** [comment]
Wine is at unsupported state, due to how difficult it is to debug, as well as to maintain through updates.
