### ISSUE TITLE
Encoding broke

### ISSUE THREAD

**Issue by lexikiq** [clementgallet/libTAS#368]
`git bisect` shows it broke in ae7bd23e2c19a1f3894c36777bfba94155ec204d and still affects the latest commit of 3904615dda5876ed616b722c86452031b7e4e822

starting an encode just hangs the game. there is no way to stop the encode (menu option doesn't do anything). starting the encode before launching the game shows that it hangs after the window is created but before it can draw frames. tested with love (mari0) and godot (a key(s) path) with an output mp4 file, framerate 60, and arguments `-c:v libx264 -c:a aac -crf 18`

edit: additionally, if you start the encode before launching the game, then ffmpeg prints the following upon killing the game
```
[nut @ 0x5555555e2500] No main startcode found.
pipe:: Invalid data found when processing input
```
and libtas prints
```
recv() returns -1 with error Connection reset by peer
The connection to the game was lost. Exiting
```

**Comment by clementgallet** [comment]
Fixed by c22b7b3.
