### ISSUE TITLE
sdl-gnash built on Arch Linux fails to hook

### ISSUE THREAD

**Issue by lexikiq** [clementgallet/libTAS#369]
Using a build of `sdl-gnash` from [this custom `PKGBUILD`](https://aur.archlinux.org/packages/gnash-git/#comment-730991) for `gnash-git` (fixes annoying/long dependencies + errors in the actual package)

libTAS attempts and fails to connect to socket. [libTAS output/gdb backtrace](https://github.com/clementgallet/libTAS/files/5133233/sdl-gnash-error.txt) -- warning: it's.. long

I noticed various clock_gettime calls and thought it might be a timing issue, but tweaking with timing settings along with all other (debug) options hasn't provided any different results

**Comment by clementgallet** [comment]
There's a recursive call here caused by jemalloc:
`je_malloc()`
 -> `libtas::clock_gettime()` (for some arena profiling)
 -> `dlsym()` (to fetch the real `clock_gettime()` function pointer)
 -> `calloc()` (`dlsym()` allocates the `dlerror()` string buffer on first call)
 -> `je_malloc()`.

**Comment by clementgallet** [comment]
It took me some time to figure out where to break the recursive call. Working on `calloc()` was a deadend, so worked on `dlsym()`. When a recursive `dlsym()` call is detected, we don't call the original function, but the internal implementation-dependant `_dl_sym()`, which bypasses all side effects of the API function, avoiding further recursive calls. It's far from perfect, but it works. Also, if `_dl_sym()` trick breaks, we have bigger problems than this :/
