### ISSUE TITLE
Encoding does not record Myst III Exile window when running via ResidualVM

### ISSUE THREAD

**Issue by cheslinga** [clementgallet/libTAS#370]
Recently noticed this while programming a TAS for Myst III Exile. Any time that I start an encode, the game window never actually shows up in the video. If I start it on frame 1 when launching from ResidualVM, the rest of the video sticks on the last frame from ResidualVM just before launching the game. If I start it while in-game, it simply displays a black screen.

Not sure if this could have something to do with DRM in the game itself. I'd be happy to run a few test cases to figure things out if necessary.

**Comment by clementgallet** [comment]
Commit 20efa76 fix video encode on Grim demo, so it should work on Myst III as well.

**Comment by cheslinga** [comment]
Worked like a charm! Thank you very much!
