### ISSUE TITLE
Broken pipe (and abrupt close) when closing GDB-attached game the wrong way

### ISSUE THREAD

**Issue by InfoTeddy** [clementgallet/libTAS#374]
Whenever you launch a game with GDB attached, you have to close the game in a *very* specific way, else libTAS will simply flat-up close.

Here's how you do it *without* closing libTAS:

1. Launch game with GDB attached.
2. Press "Stop" in libTAS. After this, the button changes into "Kill", but pressing "Kill" will do nothing.
3. Ctrl-D in GDB, agree to the confirmation prompt.

This way works fine, and nothing bad will happen.

But if you do it like this:

1. Launch game with GDB attached.
2. Ctrl-C in GDB, Ctrl-D, agree to the confirmation prompt.
3. Press "Stop" in libTAS.

Then libTAS abruptly closes.

To investigate, I opened libTAS in GDB (and yes, this is getting recursive - I was wondering which GDB I would be in after opening the game with GDB attached, and luckily enough it was the GDB that was attached to the game, not to libTAS itself), and it says that libTAS received SIGPIPE, the signal for a broken pipe. Which makes sense, but I feel like libTAS should handle a broken pipe gracefully, and not just abruptly close...

**Comment by clementgallet** [comment]
From my testings, this case works correctly. When I confirm gdb exit, libTAS shows "Game was closed" and stops. [This line](https://github.com/clementgallet/libTAS/blob/master/src/program/GameLoop.cpp#L89) is supposed to check for the game process exiting, but maybe in specific cases it doesn't work.

**Comment by jacobly0** [comment]
Whether this actually causes a crash depends on what part of the game loop libTAS is in when the program is killed (e.g. by exiting gdb).  I was going to try to make a consistent repro, but it was easier to just fix the issue instead.  In theory, could probably be reproduced by calling `closeSocket()` in the child at some point after initialization, causing `recv()` to signal a `SIGPIPE` and terminate libTAS, but not causing `waitpid()` to return that the child terminated, which would avoid further `recv()` calls.
