### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by ACrowIAm** [clementgallet/libTAS#38]
Ok. so basically i have been trying to get LibTAS to work for about 1 month now but it just simply wont work for me. I tried everything and i mean EVERYTHING i even tried submitting an issue no luck. so i was wondering if some kind sir who is reading this could send me there Virtual Machine of LibTAS working on it. It would mean so much to me because right now i'm stuck with using Cheat Engine to slow down the game to TAS it without save states or anything.

My Email To Send It To: acrowiamgaming@gmail.com

Thanks in advance!

**Comment by ACrowIAm** [comment]
hold up im going try ubuntu 18 instead of 17 because im legit desperate to get this to work like i dont even care about punctuation at this point

**Comment by clementgallet** [comment]
I sent you a VM on your mail.
