### ISSUE TITLE
Can't TAS with audio on?

### ISSUE THREAD

**Issue by Sonia-7** [clementgallet/libTAS#393]
I got an alternate SSD for my machine and installed Linux Mint in it, now I can choose between Windows and Linux upon boot. This was mainly to work with MAME on libTAS natively (without a virtual machine).

So, I followed the instructions in the "Running MAME in libTAS" thread from tasvideos and got it to work. But the problem is that while recording a movie, I have to mute the game otherwise loading a state up crashes the program. libTAS does say "Savestates will likely not work unless you check [Sound > Mute]", but do I really have to record without audio? That makes things harder in some games since sometimes I don't know if I'm really hitting an enemy or not, or things like that.

Is there no way to have audio during record and make it so the program won't crash upon state loading?

**Comment by InfoTeddy** [comment]
> but do I really have to record without audio?

> Is there no way to have audio during record 

You can record with audio. Then you can close the game, save the movie, and re-open it. You just can't load savestates with audio. Recording isn't the same thing as loading savestates.

**Comment by Sonia-7** [comment]
I thought I was clear enough. Yes, I know it's possible to record with audio. But what I meant is recording with audio _and_ loading savestates at the same time. Should have written the first sentence you quoted as "do I really have to TAS without audio?". Also, the second sentence in your quote is longer than that.

Anyway, if it's really not possible to record _and_ load savestates during the process, then I guess nothing can be done about it. Thanks for clearing it up.

**Comment by clementgallet** [comment]
If your system is using pulseaudio for outputting audio, it creates a specific thread for audio, which messes up savestate feature. Can you try uninstalling pulseaudio (`sudo apt uninstall pulseaudio`), and try again? It should use plain ALSA now, which doesn't spawn an extra thread.

**Comment by Sonia-7** [comment]
> Can you try uninstalling pulseaudio (`sudo apt uninstall pulseaudio`), and try again?

That command didn't work, however, what did work was "sudo apt-get autoremove pulseaudio".

Thanks a lot for pointing out a solution! It was simple and worked perfectly.

**Comment by InfoTeddy** [comment]
Is there no other way to prevent creating the PulseAudio thread other than uninstalling PulseAudio?

**Comment by clementgallet** [comment]
The `pasuspender ` is supposed to be the correct way to do that, but it's not working.

We could also choose a specific device in `snc_pcm_open()` instead of the `"default"` value, which is overriden by pulseaudio to redirect to pulse device. However, which device should we use, if the user has multiple output devices?

**Comment by Sonia-7** [comment]
By the way, here's an update. I thought that had fixed the problem but it ended up destroying the OS after reboot. I got an error saying: **Xsession: unable to launch "cinnamon-session-cinnamon" X session --- "cinnamon-session-cinnamon" not found; falling back to default session.**

So, what I did to recover the OS was following the instructions in this post:
https://forums.linuxmint.com/viewtopic.php?p=1498782&sid=25d643d6e52496abce7b10a92e9234ed#p1498782

Then the libTAS solution that worked for real was simply disabling pulseaudio temporarily (without uninstalling it). In order to do so, first I followed the instructions here:
https://learn.foundry.com/nuke/content/timeline_environment/managetimelines/audio_pulse.html

But that's not enough. Afterwards, open the terminal and apply the following commands:
```
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
```
And to start it again, you can do:
```
systemctl --user start pulseaudio.socket
systemctl --user start pulseaudio.service
```
Now savestates can be loaded with audio without crashing the program, and the OS doesn't get destroyed that way.
