### ISSUE TITLE
How to dump a game at its native resolution?

### ISSUE THREAD

**Issue by Sonia-7** [clementgallet/libTAS#396]
This may sound like a stupid question but I can't figure it out. So, I'm trying to dump a mame game here with a resolution of 384x224. I went to [Tools > Configure encode], set the Video codec to "raw video" and Audio codec to "PCM". But when I click [Start encode > start], the game is dumped at an automatically upscaled resolution of 1376x1016. Why is that?

I'd just like to dump it at its native resolution of 384x224, like actual mame. How to do that?

**Comment by InfoTeddy** [comment]
Normally, I would recommend using the Video -> "Virtual screen resolution" option, but it seems like 384x224 isn't in the predefined list of video resolutions. (The video resolution ought to be more customizable than this...)

However, this is what I do for VVVVVV (I set it to 640x480), because I use the toggle fullscreen shortcut to be able to flip during cutscenes. So you could try that, and see if dumping with a specified virtual screen resolution will actually dump at that resolution.

**Comment by clementgallet** [comment]
What is the resolution of the mame window? libTAS encodes at the resolution of the window, so if mame is doing some upscaling, libTAS uses that resolution.

**Comment by Sonia-7** [comment]
> What is the resolution of the mame window? libTAS encodes at the resolution of the window, so if mame is doing some upscaling, libTAS uses that resolution.

Oh. I had mame configured to "Start Out Maximized" so that's why.

I changed it to "Off" and the game supposedly shows at native resolution, but it's still not right. libTAS is dumping it at 384x288 for some reason.

I had an idea but not sure if it'd be possible. Mame has a built-in .avi dumping feature. You just run in the command line [mame "gamename" -aviwrite "aviname.avi"]. It always dumps the game in question at native resolution. So if you could incorporate that feature in libtas, the wrong resolution issue would be solved. It'd look something like this:

![aviwrite](https://user-images.githubusercontent.com/24638400/107885058-c4dff380-6ed6-11eb-88d6-5bcaf4dd7ad4.png)

I tried that during movie playback but no video was created. Would it be possible to make that a feature?

**Comment by vadosnaprimer** [comment]
Do you have aspect ratio correction enabled in mame?

**Comment by clementgallet** [comment]
> I changed it to "Off" and the game supposedly shows at native resolution, but it's still not right. libTAS is dumping it at 384x288 for some reason.

Mame shows by default the game in the intended aspect ratio. This game as a resolution of 384x224 (12:7) but is meant to be displayed on a 4:3 monitor, hence the final resolution of 384x288. If you want to show/dump with its internal resolution (with square pixels), then you can uncheck "Enforce aspect ratio" in mame. 

> I tried that during movie playback but no video was created. Would it be possible to make that a feature?

Did you uncheck `Runtime > Prevent writing to disk`? Also, you may want to specify an absolute path for the video file

**Comment by Sonia-7** [comment]
> Mame shows by default the game in the intended aspect ratio. This game as a resolution of 384x224 (12:7) but is meant to be displayed on a 4:3 monitor, hence the final resolution of 384x288. If you want to show/dump with its internal resolution (with square pixels), then you can uncheck "Enforce aspect ratio" in mame.

> Did you uncheck `Runtime > Prevent writing to disk`? Also, you may want to specify an absolute path for the video file

Both solutions worked perfectly. Thank you so much!
