### ISSUE TITLE
Not detecting Unity Engine

### ISSUE THREAD

**Issue by marcelopio** [clementgallet/libTAS#398]
Dandara is a game made in Unity, but it does not call mono_unity_liveness_allocate_struct, and so does not call setUnity()

I think this maybe causing some inconsistencies with some RNG mismatch.

[Dandara.x86_64.log](https://github.com/clementgallet/libTAS/files/6024694/Dandara.x86_64.log)

**Comment by InfoTeddy** [comment]
Is there a more reliable way of detecting Unity games?

**Comment by marcelopio** [comment]
Checking any call to mono_unity_liveness_* instead of specifically _allocate_struct?
