### ISSUE TITLE
dlopen hook breaks objects that attempt to open dynamic libraries from their runpaths

### ISSUE THREAD

**Issue by jakobrs** [clementgallet/libTAS#399]
### What

The `dlopen` function is hooked by libTAS in such a way that it breaks executables that open dynamic libraries from their runpaths.

### Why

`dlopen` normally uses the return address to figure out who called `dlopen`, whose runpath is used to search for libraries. Because of the hook, however, the return address is in `libtas.so` instead, so `dlopen` gets the runpath of `libtas.so` instead of the whatever object originally called `dlopen`.

**Comment by clementgallet** [comment]
Do you have a real-world example of a game having this issue? Does it concern calling `dlopen()` with a relative path? I thought `dlopen()` was using the current working directory, not the caller directory?

**Comment by jacobly0** [comment]
@jakobrs Any reason why you can't just copy the executable's runpath to `Executable Options` &rightarrow; `Library path`?
@clementgallet In this context, runpath is probably referring to the list of search paths (absolute or relative to the executable location) that can be stored in an executable at link time.

**Comment by jakobrs** [comment]
I've only ever had issues with this with binaries built using Nix (so anything from my package manager), which makes very heavy use of runpaths (I literally do not have a `/lib` or `/usr/lib` for this reason, for example), so this makes it more difficult to use libTAS with e.g. Love2D (which is a package). I *can* use `Library Path` as a workaround (I have a small Rust script to generate a string to use here), but this hook is the main thing preventing me from being able to package libTAS for Nixpkgs.

`dlopen()` searches by relative or absolute pathname exactly if the `path` argument contains a slash, otherwise it searches in the same order as `ld.so` does for standard dynamic dependencies: (from the dlopen man page)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/10761079/109011051-cf597480-76b0-11eb-9055-48d2aebc5203.png">

Note that a program may have a different runpath than any of its dependencies.

**Comment by jacobly0** [comment]
I see three different potential ways of implementing this, can work on it later.

**Comment by jacobly0** [comment]
@jakobrs Can you test if #400 solves your issue.

**Comment by jakobrs** [comment]
@jacobly0 I just tested it, it seems to work perfectly.
