### ISSUE TITLE
Loading a savestate doesn't update the screen properly after fast forwarding

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#40]
If a savestate is made during fast forwarding and then loaded afterwards the game doesn't show the correct frame.

**Comment by clementgallet** [comment]
Yeah, fast-forward disables rendering except on periodic frames for performance, so the savestate stores the last rendered image and displays it when loading. This is confusing I agree, but the correct image cannot be recovered. Would you prefer to display a blank image ?

**Comment by Matte27** [comment]
Why not render the next frame and use that instead. The one frame accuracy isn't important when pausing during ff.

**Comment by clementgallet** [comment]
I think it would make this workaround too confusing (code-wise), sorry. If accuracy is not important, you can still advance one frame after loading to get the proper image.
