### ISSUE TITLE
How to deal with games with random content?

### ISSUE THREAD

**Issue by creeper121386** [clementgallet/libTAS#404]
If I want to record MOVIE file for a game with random content (like some Roguelike games), is it possible to quit the game halfway and continue recording next time? Although I can load from my saved MOVIE file, the runtime content of the game has changed and the operation of MOVIE file and the game content is mismatched. 

In this case, I have to save the system snapshot before quitting the game halfway to continue recording next time. However, the system snapshot is not resource-friendly.  Is there any way to solve this problem? Is it possible to save the runtime snapshot for the game to make sure whenever I record, The content of the game is the same?

**Comment by InfoTeddy** [comment]
RNG should stay the same across closing a game, restarting it, and replaying it back with the same inputs. It sounds like your game does not behave deterministically, which could be for any number of reasons - either way, this is a bug with libTAS.

Please tell us what game you're trying to TAS, so this bug can be fixed.

**Comment by creeper121386** [comment]
> RNG should stay the same across closing a game, restarting it, and replaying it back with the same inputs. It sounds like your game does not behave deterministically, which could be for any number of reasons - either way, this is a bug with libTAS.
> 
> Please tell us what game you're trying to TAS, so this bug can be fixed.

The game is Hollow Knight with mods loaded. It seems that libTAS works well with the Hollow Knight without mods. Maybe the problem is the mod.

**Comment by clementgallet** [comment]
I don't think mods matter. While people have succeeded making small TASes of HK, as a Unity game, it is not fully desync-proof and will desync if you don't go frame by frame at certain points (transitions mostly). You should talk to those people to see how they managed to do their TAS.

**Comment by creeper121386** [comment]
> I don't think mods matter. While people have succeeded making small TASes of HK, as a Unity game, it is not fully desync-proof and will desync if you don't go frame by frame at certain points (transitions mostly). You should talk to those people to see how they managed to do their TAS.

Thanks for your reply, I'll talk to those people for help.
