### ISSUE TITLE
MAME doesn't get inputs

### ISSUE THREAD

**Issue by gterras** [clementgallet/libTAS#409]
_Debian Sid, KDE/Openbox, Nvidia non-free, MAME 0.230_ 

Hi sorry this is most certainly a setup specific issue as many people seem to have it working but after hours of trying I have no solution, feel free to close and thanks for your awesome work!

Mame does not seem to get inputs from libTAS on my setup (even with movie disabled). I have followed instructions here http://tasvideos.org/forum/viewtopic.php?t=20554. Some people say Mame should be configured when launched from libTAS but even arrow keys in MAME UI won't work when launched from libTAS. Note that non-MAME games work fine, so does MAME when launched by itself. 

I have tried building latest commit `a86e907` and somehow got inputs (coin button) working one time only (on a fresh reboot) otherwise same behavior. I make sure to erase configuration files when switching versions. I can't find anything useful in logs. 

Is there any chance it could be related to video somehow? I get the `Software rendering was enabled, but the OpenGL renderer currently used does not match.` message if I check `enable software rendering`, does libTAS call MAME with `LIBGL_ALWAYS_SOFTWARE=1`? I've tried pretty much every video settings in MAME too. 

If you could point me towards more advanced debugging it would be nice, thanks!

**Comment by clementgallet** [comment]
There was a problem with the focus window not being identified correctly. It should be fixed now.
