### ISSUE TITLE
If the close button is pressed on the first frame the game doesn't close properly

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#42]

**Comment by clementgallet** [comment]
I guess this is for Super Meat Boy. It looks like the game is doing some benchmarking on startup, waiting for the next screen draw. If closing at the first frame, the game appears to ignore the close event and still waits for the next draw, which results in a softlock.

**Comment by clementgallet** [comment]
I think this is more like a bug of the game, I don't see how I could avoid this behavior in a generic way.

**Comment by Matte27** [comment]
Is it too specific to draw one extra frame before closing if the game is closed on the first frame?

**Comment by clementgallet** [comment]
I think it is too arbitrary, yes. Meat boy may even require drawing several frames not to softlock, I didn't check.
