### ISSUE TITLE
SlimeRancher does not work with libTAS and nouveau drivers

### ISSUE THREAD

**Issue by feuerball11** [clementgallet/libTAS#429]
SlimeRancher works fine with Nvidia drivers, though savestates cannot be used, and it desyncs (other issue) 
but with nouveau drivers, it freezes during start-up. 
With Software Rendering it freezes within 2 frames,
With Hardware Rendering within the first few hundred frames. 
The terminal shows these errors, which are not present with Nvidia Drivers:
```
[libTAS f:0] Thread 3200  ERROR: Opened file descriptor 450 was already registered!
[libTAS f:0] Thread 3198  ERROR: Opened file descriptor 618 was already registered!
[libTAS f:0] Thread 3198  ERROR: Opened file descriptor 985 was already registered!
```

**Comment by clementgallet** [comment]
That's a lot of file descriptors! Can you try uncheck `Runtime > Prevent writing to disk`?
