### ISSUE TITLE
libTAS segfaults if audio is disabled on some games

### ISSUE THREAD

**Issue by InfoTeddy** [clementgallet/libTAS#432]
Some games (such as VVVVVV) will result in libTAS segfaulting when attempting to launch if the audio is completely disabled via Sound > Disable.

Launching the game with GDB will reveal that the segfault is here:

https://github.com/clementgallet/libTAS/blob/d2c3eb07474acca9da759bbfde7396227e30c971/src/library/audio/sdl/sdlaudio.cpp#L316

It seems that `libtas::SDL_PauseAudioDevice()` is being passed an invalid `dev` and is indexing `sourcesSDL` out of bounds.

I'm unsure of how to fix this. It would be as simple as doing

```cpp
if (dev - 1 >= SDL_arraysize(sourcesSDL))
    retrun;
```

and indeed, putting the above at the start of the function fixes the segfault. But I am not sure if this bounds check should be applied to other functions. Additionally, at the top of the file, there is

https://github.com/clementgallet/libTAS/blob/d2c3eb07474acca9da759bbfde7396227e30c971/src/library/audio/sdl/sdlaudio.cpp#L109-L110

so should we explicitly check for `shared_config.audio_disabled` everywhere instead?

**Comment by clementgallet** [comment]
Games may call SDL audio functions with invalid `dev`, so we better handle that.
