### ISSUE TITLE
Save files don't write to disk until the game is reloaded and then write garbage and duplicate data, causing desyncs

### ISSUE THREAD

**Issue by OceanBagel** [clementgallet/libTAS#433]
I'm using version 1.4.2 with Undertale version 1.001 and the "Prevent writing to disk" option disabled, although the same thing happens with "Prevent writing to disk" enabled as well because it seems that the "Prevent writing to disk" feature is always on regardless of whether or not the check box is actually checked in version 1.4.2.

When Undertale saves at a save point with no existing save data, the expected behavior is that three files are created in the folder `~/.config/UNDERTALE_linux_steamver` (or for later versions the folder `~/.config/UNDERTALE`): file0, file9, and undertale.ini. These files are created properly when the game is running outside of libTAS.

However, when the game is run from within libTAS, these save files are not created until the game is restarted. Then once the game is restarted, the save files contain extra duplicate data, such as the contents of file0 being written to undertale.ini and vice versa, as well as what appears to be garbage data that does not normally appear in any Undertale save files.

I also tested this on version 1.3.4 where this issue is reproduced only when "Prevent writing to disk" is enabled. On 1.3.4 with "Prevent writing to disk" disabled, the expected save file data is saved to the disk at the expected times.

This issue creates a desync where the garbage data written to the save file prevents the game from properly reading back the save data. My TAS desyncs on 1.4.2 regardless of the "Prevent writing to disk" option selection and syncs on 1.3.4 only if the "Prevent writing to disk" option is disabled.

**Comment by clementgallet** [comment]
Can you try if commit f8bc96e fixed the issue?

**Comment by OceanBagel** [comment]
I tested it and the issue of corrupted save data does seem to be resolved. The save files are still written to the disk when the game is restarted even if "Prevent writing to disk" is enabled, but it seems like this is the intended behavior.

As for the comments on the "Prevent writing to disk" checkbox not actually toggling the behavior, I haven't been able to reproduce this again. I'm not sure what originally caused it but it's only tangentially related to this issue anyway.

**Comment by clementgallet** [comment]
> The save files are still written to the disk when the game is restarted even if "Prevent writing to disk" is enabled, but it seems like this is the intended behavior.

Yes, this is intended. Because the game process stops, all file contents in memory are lost unless saved on disk. I know it defeats the purpose of "Prevent writing to disk", but that's the easiest solution I found so far to make TASes with restarts to work.
