### ISSUE TITLE
Data returned by SDL_GetKeyboardState only updates when it gets called

### ISSUE THREAD

**Issue by khang06** [clementgallet/libTAS#440]
https://github.com/Wohlstand/TheXTech calls SDL_GetKeyboardState once at initialization and stores the returned value. it directly accesses this stored pointer for checking input instead of calling the function over and over again, so libTAS keyboard input doesn't work with this game

**Comment by InfoTeddy** [comment]
You're implying that libTAS is written assuming that the game will call `SDL_GetKeyboardState()` over and over again. However, if you actually look in the source:

https://github.com/clementgallet/libTAS/blob/5deef26fb55a9636ea1dc2b968ee3bbcf3dbf53f/src/library/inputs/sdlkeyboard.cpp#L30-L43

You can see that libTAS has its own always-existing array that it returns to the caller. It acts identically to SDL in this regard.

So, are you sure that your description is correct?
