### ISSUE TITLE
Ruffle: Keyboard inputs unresponsive

### ISSUE THREAD

**Issue by slamotas** [clementgallet/libTAS#443]
Ruffle version: nightly-2021-10-26
libTAS version: 1.4.2 interim c83a69f

Tested with this SWF: https://dagobah.net/flash/the_worlds_hardest_game.swf

Command-line options are `-g gl /path/to/dagobah_the_worlds_hardest_game.swf`. Time tracking with `clock_gettime()` is required.

Get into the first level and try to move around with the arrow keys (you are the red square). You usually don't move around, but sometimes the player will start moving in a direction and continue to move without any inputs. The game works properly outside of libTAS.

**Comment by MyNameIsTrez** [comment]
I'm getting exactly the same console output as slamotas is getting:
```
[libTAS f:1823] Thread 39782 (main) Generate XEvent KeyPress with keycode 116
[libTAS f:1823] Thread 39782 (main) Generate XIEvent RawKeyPress with keycode 116
[libTAS f:1823] Thread 39782 (main) XKeycodeToKeysym called with keycode 116
[libTAS f:1823] Thread 39782 (main)    returning 65364
[libTAS f:1958] Thread 39782 (main) Generate XEvent KeyRelease with keycode 116
[libTAS f:1958] Thread 39782 (main) Generate XIEvent RawKeyRelease with keycode 116
[libTAS f:1958] Thread 39782 (main) XKeycodeToKeysym called with keycode 116
[libTAS f:1958] Thread 39782 (main)    returning 65364
[libTAS f:1958] Thread 39782 (main) XLookupString called with keycode 116
```

**Comment by MyNameIsTrez** [comment]
The console does seem to print every time the down arrow key is being pressed, even though the game doesn't register the key press. I'm thinking the dropped inputs may only be happening when the game is laggy, which mine definitely is. The top of the window reports it's 30 FPS, but I think that's wrong as it has a lot of small lag spikes.

**Comment by MyNameIsTrez** [comment]
In this video you can see me mashing the up/down/left/right arrow keys like a madman and how the game rarely registers any of those key presses:
https://user-images.githubusercontent.com/32989873/139593632-e21cd69b-cc2a-4fe9-a9cc-ad253d3a9210.mp4

**Comment by clementgallet** [comment]
There's one thing I'm concerned in the video: there's no updated mouse coordinates in the OSD. Can you confirm that mouse inputs always show 0,0 ?

**Comment by MyNameIsTrez** [comment]
@clementgallet I'll try to reproduce it with the latest version of libTAS + Ruffle + OpenGL once I get home.

**Comment by MyNameIsTrez** [comment]
@clementgallet This video showcases two things:
1. Moving the mouse freezes the game, and the faster the mouse moves the more it freezes.
2. The WASD controls still don't work, cause at the end of the video I'm furiously pressing the A and S keys to no avail.

https://user-images.githubusercontent.com/32989873/143083594-26b26b9e-f219-4b3c-b102-d2064c5887d4.mp4

**Comment by jakobhellermann** [comment]
I can confirm that https://github.com/clementgallet/libTAS/commit/c15b9c8ac301fb5ddf193bd82900033db8bcf58a fixes the issue for me

**Comment by MyNameIsTrez** [comment]
I can confirm that the game in question works for me now, thank you @clementgallet! :+1:
