### ISSUE TITLE
The libTAS overlay with Ruffle turns black with `-g gl` and isn't present with `-g vulkan`

### ISSUE THREAD

**Issue by MyNameIsTrez** [clementgallet/libTAS#444]
# Setup information

libTAS version: `libtas_1.4.2_c83a69f_amd64`
Ruffle version: `ruffle-nightly-2021_10_26-linux-x86_64`
Here's the SWF file I'm trying to play (inside of a .zip because GitHub doesn't allow uploading a .swf directly): [plazma_burst_fttp.zip](https://github.com/clementgallet/libTAS/files/7392855/plazma_burst_fttp.zip)

# With Ruffle option `-g gl`

By checking the `Pause` box in libTAS it shows the first frame with the libTAS overlay, and when I move the mouse around it updates the X and Y coordinates:
![Screenshot from 2021-10-26 19-24-03](https://user-images.githubusercontent.com/32989873/138929663-b748a060-9cf5-477b-b5c8-c52bdf2b178c.png)

When I press the `v` key to advance a frame libTAS says that the game's on frame 2, but the frame counter in the top-left corner doesn't update from 1 -> 2, and the mouse coordinates don't update anymore when I move the mouse.

When I press `v` again, libTAS says that the game's on frame 3, but the libTAS overlay has turned to black boxes and stays that way for the rest of the game:
![Screenshot from 2021-10-26 19-22-37](https://user-images.githubusercontent.com/32989873/138929534-f11239c5-cbcd-4af8-8735-83728d7f4bb0.png)

# With Ruffle option `-g vulkan`

No libTAS overlay at all:
![image](https://user-images.githubusercontent.com/32989873/138928892-68836a3d-e45d-44b0-aca7-ae49a5289d4b.png)

**Comment by clementgallet** [comment]
GL OSD is fixed by 852f740. There is currently no OSD for Vulkan, and given how verbose Vulkan is, I won't work on it for now.

**Comment by clementgallet** [comment]
Closing for now. Vulkan is not very useful because software rendering is still early
