### ISSUE TITLE
Library error when compiling with library already installed

### ISSUE THREAD

**Issue by Kiffolisk** [clementgallet/libTAS#449]
When trying to compile dual-arch libTAS, I keep getting the error "configure: error: The x11 library is required!". I already installed the correct one from the instructions on the README.

Trying to re-install just shows they're already installed:
![image](https://user-images.githubusercontent.com/45130240/140657230-9f8b1ad8-424b-40b5-b9ac-f94a73c436b8.png)

**Comment by InfoTeddy** [comment]
What's the full `apt-get` command? Your screenshot cuts off some of it. Did you install the 64-bit version of said library? You *do* say you are trying to compile a dual-arch libTAS; you'll need the 64-bit versions of all libraries as well.

**Comment by Kiffolisk** [comment]
I compiled on 64-bit and it works fine. I'll try getting a better screenshot.

**Comment by Kiffolisk** [comment]
![image](https://user-images.githubusercontent.com/45130240/141098937-54a5c6be-d052-47cb-a542-f5be17c3d9d6.png)

**Comment by Kiffolisk** [comment]
![image](https://user-images.githubusercontent.com/45130240/141098988-e654dbf5-2caa-4c79-bd9e-0bcced092a21.png)
Command from this

**Comment by InfoTeddy** [comment]
> I compiled on 64-bit and it works fine.

So... is it working now?

**Comment by Kiffolisk** [comment]
Can't compile dual-arch but only 64-bit

**Comment by InfoTeddy** [comment]
Oh, right.

I'm not sure what the issue is then, but it's probably a problem with libTAS.

**Comment by clementgallet** [comment]
Can you paste what is the configure script error?

**Comment by Kiffolisk** [comment]
Looks like it works now? Don't know what I did but it sure did work.

**Comment by Kiffolisk** [comment]
Nevermind, I thought it was working because it took longer for some reason. Here's the full error:
`checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make supports nested variables... (cached) yes
checking for i386 cross-compiling... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for QT5... yes
checking for moc... moc
checking for ffmpeg... no
checking xcb/xcb.h usability... yes
checking xcb/xcb.h presence... yes
checking for xcb/xcb.h... yes
checking xcb/randr.h usability... yes
checking xcb/randr.h presence... yes
checking for xcb/randr.h... yes
checking xcb/xcb_keysyms.h usability... yes
checking xcb/xcb_keysyms.h presence... yes
checking for xcb/xcb_keysyms.h... yes
checking xcb/xkb.h usability... yes
checking xcb/xkb.h presence... yes
checking for xcb/xkb.h... yes
checking for library containing XKeysymToString... -lX11
checking for library containing xcb_connect... -lxcb
checking for library containing xcb_xkb_use_extension... -lxcb-xkb
checking for library containing xcb_key_symbols_alloc... -lxcb-keysyms
checking for library containing pthread_create... -lpthread
checking for LIBLUA... yes
checking for library containing dlopen... -ldl
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
checking X11/Xlib-xcb.h usability... yes
checking X11/Xlib-xcb.h presence... yes
checking for X11/Xlib-xcb.h... yes
checking for library containing XOpenDisplay... -lX11
checking for library containing XGetXCBConnection... -lX11-xcb
checking SDL2/SDL.h usability... yes
checking SDL2/SDL.h presence... yes
checking for SDL2/SDL.h... yes
checking libudev.h usability... yes
checking libudev.h presence... yes
checking for libudev.h... yes
checking for xcb/randr.h... (cached) yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for library containing pthread_join... -lpthread
checking alsa/asoundlib.h usability... yes
checking alsa/asoundlib.h presence... yes
checking for alsa/asoundlib.h... yes
checking for library containing snd_pcm_open... -lasound
checking for LIBSWRESAMPLE... yes
checking fontconfig/fontconfig.h usability... yes
checking fontconfig/fontconfig.h presence... yes
checking for fontconfig/fontconfig.h... yes
checking ft2build.h usability... yes
checking ft2build.h presence... yes
checking for ft2build.h... yes
checking for library containing FcInitLoadConfigAndFonts... -lfontconfig
checking for library containing FT_Open_Face... -lfreetype
checking for library containing dlclose... -ldl
checking for library containing XCloseDisplay... no
configure: error: The x11 library is required!`

**Comment by clementgallet** [comment]
Can you paste the output of `ls -l /usr/lib/i386-linux-gnu/libX11.so*` ?
