### ISSUE TITLE
You can lose work if you accidentally quit the application

### ISSUE THREAD

**Issue by Hurricane996** [clementgallet/libTAS#452]
This has happened to me at least twice, where I accidentally quit the application and it just sends all my changes to the shadow realm. #451 fixes this.

**Comment by InfoTeddy** [comment]
Doesn't closing the game prompt you to save the movie?

**Comment by Hurricane996** [comment]
Yes, but closing libTAS does not.

**Comment by clementgallet** [comment]
Fixed in c256995993346906d155d0483b6dd837c93cd5de and 3c4bf746f9c23a5b01338d8af9ecfc8cee85eef3
