### ISSUE TITLE
Clickteam Fusion game crashes on start

### ISSUE THREAD

**Issue by Kiffolisk** [clementgallet/libTAS#456]
Been trying to run this game:
https://gamejolt.com/games/funnymanreturns/529473

After pressing "Start" in libTAS the game does not start.
I tried everything with time tracking too.

**Comment by InfoTeddy** [comment]
What gets printed to the terminal?

**Comment by Kiffolisk** [comment]
`Interim commit f13d2908 built on 2021-10-23
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
[libTAS f:0] Thread 0 (main) Skipping libtas init
Attempt 1: Connected.
0024:err:environ:run_wineboot boot event wait timed out
0064:fixme:ntoskrnl:MmQuerySystemSize stub
0064:fixme:ntoskrnl:IoRegisterFileSystem (000000000002AC20): stub
0064:fixme:ntoskrnl:FsRtlRegisterUncProvider (0000000000EBF7E0 0000000000EBF7F8 0): stub
0064:fixme:ntoskrnl:IoUnregisterFileSystem (000000000002AC20): stub
0064:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\adfs": c0000002
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"adfs" failed to start: 1
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow The explorer process failed to start.
0024:fixme:msvcrt:__clean_type_info_names_internal (02684420) stub
0024:fixme:heap:RtlCompactHeap (00500000, 0x0) stub
0024:fixme:ver:GetCurrentPackageId (0032FE94 00000000): stub`

**Comment by InfoTeddy** [comment]
First off, multiline code blocks are done with triple-backticks like so:

`` ``` ``
`this`
`` ``` ``

Secondly, does the game run fine outside of libTAS?

**Comment by Kiffolisk** [comment]
Yes. Works perfectly fine when not using libTAS

**Comment by clementgallet** [comment]
You are getting this case: #401

**Comment by Kiffolisk** [comment]
I can't seem to find any 5.0 downloads for Wine.
