### ISSUE TITLE
[Wine] Game doesn't run properly

### ISSUE THREAD

**Issue by EdensStudio** [clementgallet/libTAS#460]
soft/hardware versions: libTAS v1.4.1 wine 4.0 debian 10
im trying to tas a .exe game but whenever i execute it in libTAS the application screen is just transparent, but if i only run it via wine from terminal, it can run properly.
edit 1: also i had clock_gettime() on.
edit 2: i read #262 and it doesnt seem to be the issue ehre as the window is still transparent after moving it/making it the top/was default as top
edit 3: only games that work in 60fps can't run properly, but the games in 30 fps freezes whenever i press a button
i tried googling a solution but i dont seem to find someone else who had a similar issue
here is a screenshot: https://ibb.co/1fsCzj0

**Comment by LukeSaward1** [comment]
I ported OversaveTale to Linux, it can be found [here](https://drive.google.com/file/d/1-NTzxk0rgjDCT0-CINw-2DHW7UmcCFxR/view?usp=sharing).

**Comment by EdensStudio** [comment]
> I ported OversaveTale to Linux (OS:T version 28.6), it can be found [here](https://drive.google.com/file/d/1-NTzxk0rgjDCT0-CINw-2DHW7UmcCFxR/view?usp=sharing).
> 
> Although I can make a port for the version you're running, assuming it's using GameMaker: Studio

I tried this method before, taught by another TASer, but it says i need to install libcurl to open it, but i have no idea how to install one in debian, i tried to use ubuntu but i have no idea how to set up one lol

**Comment by InfoTeddy** [comment]
It should be as simple as `sudo apt install libcurl` or `sudo apt install libcurl3`, although I don't use Ubuntu/Debian so I can't easily check if that's exactly correct, but it's definitely close enough.

**Comment by EdensStudio** [comment]
for `sudo apt install libcurl` it shows:
dpkg was interrupted. you must manually run 'sudo dpkg --configure -a' to correct the problem
then i inputed `sudo dpkg --configure -a`
then i reinputed `sudo apt install libcurl`
and it shows Unable to locate package libcurl

for sudo apt install libcurl3, it says that it can be replaced by libcurl4, so i inputed `sudo apt install libcurl4`

Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or have been moved out of Incoming.

**Comment by clementgallet** [comment]
GameMaker Studio uses old libraries. You can get them from Steam runtime libraries, or from other GameMaker Studio games.

**Comment by XYisLucky** [comment]
I want to know how can I port game to Linux system
I did it as in the video [https://www.youtube.com/watch?v=EFCnTeTdD2k](url) but it didn't worked
When I use directives `./edgetale/runner` (There is an assets folder in the edgetale folder which I created myself,runner file is from OversaveTale LINUX.zip, the zip file is from LukeSaward1) it just output error code like`Collision Event time(microsecs)=171   unknown Chunk FEDS:1396983110   Failed to load the game   Attempting to set gamepadcount to 0   Not shutting down steam as it is not initialised   Script_Free called   段错误 (核心已转储)
`
But if I input `./OverSave\ Tale\ LINUX/runner` (this folder also comes from LukeSaward1) it can work,I don't understand how it works
