### ISSUE TITLE
Add UtVideo dumping option

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#467]
It's a great lossless codec after all, probably the easiest to set up these days, super fast, and not very big files.

Arguments we need for it: `-c:v utvideo -pred median -pix_fmt gbrp`

**Comment by InfoTeddy** [comment]
So you're just asking for it to be an option in the dropdown, right? Because as far as I can tell, you can just change the arguments directly.

**Comment by clementgallet** [comment]
If you have in mind default additional options for other codecs (like x264), now is the good time :)

**Comment by vadosnaprimer** [comment]
ffv1 args we use are `-pix_fmt bgr0 -level 1`, that results in the most compatible video. I also think for lossless codecs (and raw?) bitrate should not be passed to prevent user confusion.

**Comment by vadosnaprimer** [comment]
Thanks!
