### ISSUE TITLE
Caps lock input does not work

### ISSUE THREAD

**Issue by roblox8192** [clementgallet/libTAS#469]
I am TASing a flash game named This is the Only Level via Ruffle. In Stage 24, the player is required to hold the caps lock key in order to open the door to advance to the next stage. However, when I tried holding caps lock, the door wouldn't open. I have tried rebinding the caps lock key, which didn't work, and I have confirmed that caps lock is showing up in the input editor. I don't think this is a Ruffle issue, as I as well as others can beat stage 24 in Ruffle outside of libTAS with no issue.

The only way I could fix it was by modifying the game to have a different key open the door. In JPEXS, I went to DoAction under frame 6 in the Scripts folder and modified this block of code:

```as
if(level == 23)
{
    if(Key.isDown(20)) // I changed 20 (caps lock) to 85 (u)
    {
        doorOpen = true;
    }
    else
    {
        doorOpen = false;
    }
}
```
Only after this modification could I open the door, though by pressing u and not caps lock. I think this might be a problem with the way libTAS handles the caps lock key.

**Comment by clementgallet** [comment]
I should be able to fix this, but in fact I cannot complete stage 24 natively in Ruffle, holding the caps lock key does nothing. Tested with both 1.0 and 1.1 versions of the game, and latest nightly build of Ruffle. Am I missing something?

**Comment by roblox8192** [comment]
Apparently, it is in fact a ruffle issue specifically for linux and not for libtas: https://github.com/ruffle-rs/ruffle/issues/7002
Since there's no issue here with regards to libTAS, I'm going to close this issue.
