### ISSUE TITLE
ScummVM regression - crashes on frame 2

### ISSUE THREAD

**Issue by coolkirby2000** [clementgallet/libTAS#473]
ScummVM games, for example, [Backyard Baseball](https://tasvideos.org/7068S), run well in libTAS 1.4.1. However, in 1.4.2 and the latest interim, the window will open, get to frame 1, then crash with a "Game was closed" message. Frame 2 is normally when the ScummVM logo appears, maybe something important is supposed to be loaded there but fatally fails due to a change/regression.

Tested on a Xubuntu 20.04 liveUSB.

**Comment by InfoTeddy** [comment]
Is it a segfault/abort? What does running it with GDB say? What's the backtrace?

**Comment by slamotas** [comment]
It works fine for me. IIRC for ScummVM you have to have all OSD off or else it crashes like you've described.

**Comment by clementgallet** [comment]
Between frames 1 and 2, the SDL2 renderer is destroyed and a new one is created. The OSD texture is not recreated so it becomes invalid. Until I fix this, you can change scummvm graphics renderer into OpenGL, which seems to work fine.
