### ISSUE TITLE
Can't start VVVVVV

### ISSUE THREAD

**Issue by Azrez2** [clementgallet/libTAS#48]
when i press start in the program i get the error:
undefined symbol XGetXCBConnection:
then it can't connect to socket on all the attempts
i tried updating xlib and the other dependencies but they were all up to date

**Comment by clementgallet** [comment]
Could you try installing the packages `libx11-xcb1` and `libx11-xcb-dev` ?

**Comment by Azrez2** [comment]
i did

**Comment by clementgallet** [comment]
Commit 6bf2dbd7b6ce9794618b085e981b92697019e781 should fix this issue.

**Comment by Azrez2** [comment]
how do i do that, I'm not very good at linux

**Comment by clementgallet** [comment]
I've released a new version with this fix, so you can update it more easily.
