### ISSUE TITLE
Permanently disable fast-forward when using Input Editor

### ISSUE THREAD

**Issue by Spikestuff** [clementgallet/libTAS#491]
Basically there are titles where the load from save with fast-forward automatically turning on in the editor can actually cause either the game to crash, fake lag (which drops input) or refuse to allow any new input to be added.

**Comment by clementgallet** [comment]
I can make this an option of the input editor. I also planned on adding an option to disable rendering skipping on fast forward. But disabling that entirely would be a mistake, on most games, input editor rewind would become unusable.

However, this is probably not about a fast forward issue, but about games that intrinsically run undeterministically, which is revealed by fast forwarding. Could you open another issue on the specific game or games where this happens ?
