### ISSUE TITLE
[Ruffle] Red Beard on Gold Hunt hangs when using the Input Editor and Fast-Forward becomes enabled

### ISSUE THREAD

**Issue by Spikestuff** [clementgallet/libTAS#492]
Opening the issue related to #491.
Pre-Made input to this one [can be found here](https://github.com/clementgallet/libTAS/files/8879927/redbeard.zip).

**Comment by clementgallet** [comment]
Is it the case only for vulkan backend, or also with opengl backend?

**Comment by Spikestuff** [comment]
I have had issues with OpenGL and have made all my Ruffle TASes through Vulkan.
Just finally got OpenGL to somewhat work (I still get GL issues with literally everything else), but I can confirm that this is a Vulkan error.

**Comment by clementgallet** [comment]
In the meantime, you can set `Tools > Fast-forward mode > Skipping no rendering`. This will prevent softlocks while fast-forwarding in Vulkan.

**Comment by clementgallet** [comment]
Fast-forward has been fixed in 0f3a233
