### ISSUE TITLE
[os request]  fire os

### ISSUE THREAD

**Issue by dananothername** [clementgallet/libTAS#495]
will it work on fire os the linux distro 
if yes it will allow us to tas android games

**Comment by LukeSaward1** [comment]
If it doesn't have any of the dependencies needed, then no.

**Comment by LukeSaward1** [comment]
No.

**Comment by dananothername** [comment]
did you try it
i can't install it

**Comment by LukeSaward1** [comment]
No, I haven't. FireOS has (pretty much) none of the dependencies needed for libTAS to even install.
If there's no terminal or .deb install utility, good luck even trying to.

Basically it's impossible unless you install a supported distro of Linux.
