### ISSUE TITLE
please i dont have a debian computer for the love of god

### ISSUE THREAD

**Issue by juanroman74454811** [clementgallet/libTAS#497]
please make an EXE for it because i wanna make my tas on SRB2, please :(

**Comment by InfoTeddy** [comment]
No can do. libTAS is Linux-specific and Windows is hostile to TAS tools.

You can, however, install Windows Subsystem for Linux to use libTAS. The official guide is [here](https://clementgallet.github.io/libTAS/guides/wsl/).

**Comment by LukeSaward1** [comment]
libTAS will never, at least with current plans, get a Windows version.

**Comment by juanroman74454811** [comment]
> No can do. libTAS is Linux-specific and Windows is hostile to TAS tools.
> 
> You can, however, install Windows Subsystem for Linux to use libTAS. The official guide is [here](https://clementgallet.github.io/libTAS/guides/wsl/).

Alright! Im gonna use a VM just to make my TAS.

**Comment by p0008874** [comment]
> please make an EXE for it because i wanna make my tas on SRB2, please :(

I'm pretty sure SRB2 has linux applications
From now days, It's really hard to see TAS tool act like this.

**Comment by juanroman74454811** [comment]
> > please make an EXE for it because i wanna make my tas on SRB2, please :(
> 
> I'm pretty sure SRB2 has linux applications From now days, It's really hard to see TAS tool act like this.

Probably,

**Comment by juanroman74454811** [comment]
> > please make an EXE for it because i wanna make my tas on SRB2, please :(
> 
> I'm pretty sure SRB2 has linux applications From now days, It's really hard to see TAS tool act like this.

i already got WSL, and Ubuntu, what do i do next????
