### ISSUE TITLE
Ruffle: Can't encode the tas with `-g gl` argument

### ISSUE THREAD

**Issue by DemoJameson** [clementgallet/libTAS#505]
Kubuntu 22.04.1 + libTAS v1.4.4 + Ruffle 2022-10-14 + The Binding of Isaac Demo

At the beginning it works fine, but after selecting the character, libTAS reports errors:
```
[libTAS f:394] Thread 15795 (main) ERROR: glReadPixels failed with error 1282
[libTAS f:395] Thread 15795 (main) ERROR: glReadPixels failed with error 1282
[libTAS f:396] Thread 15795 (main) ERROR: glReadPixels failed with error 1282
```
If I delete `-g gl`, the tas can playback and encode normally

https://user-images.githubusercontent.com/181192/198995303-48fb7aeb-d9db-4480-8ebe-c112a48f28de.mp4

[game+movie.zip](https://github.com/clementgallet/libTAS/files/9900575/game%2Bmovie.zip)

**Comment by LukeSaward1** [comment]
I can't seem to load the game with `-g gl` on that nightly build, at least on Windows.
Was that build after the OpenGL breakage?

**Comment by DemoJameson** [comment]
you need this version https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2022-10-14

> Also, I think you mean -g gl and not g -gl

fixed :)

**Comment by LukeSaward1** [comment]
![image](https://user-images.githubusercontent.com/55454721/199439833-3dc9f678-2154-4175-b462-3907d2b840eb.png)
I'm using the same nightly build. (shortcut is to load it with `-g gl`)

**Comment by DemoJameson** [comment]
yeah it's not work for me too on Windows
