### ISSUE TITLE
VVVVVV crashes on end of cutscene in Final Level

### ISSUE THREAD

**Issue by Vince7778** [clementgallet/libTAS#51]
When I get to the final level of VVVVVV, right after the cutscene finishes, I can't frame advance and when I try to load a savestate it crashes and prints the message:
``*** stack smashing detected ***: <unknown> terminated``
``Got wrong message after state loading``

Any help?

**Comment by Vince7778** [comment]
I found out that if I add 10 frames or so in the Frame Editor, the game starts working when it gets there.

**Comment by clementgallet** [comment]
I guess you add the 10 frames at the beginning of the game ? That is really weird. If it is inconsistant, then would it be possible to have the movie (if you don't mind) ?

**Comment by Vince7778** [comment]
Sorry about the late reply, but I found out that the pausing happens whenever you play the game, using libTAS or not. Thanks!
