### ISSUE TITLE
Draw crosshair according to mouse coordinates in the movie

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#510]
Draw the "+" overlay on the game client area.

Extremely useful when figuring out which coordinate corresponds to which visible spot, requires recording mode and actual mouse movement to see it otherwise. With the crosshair, you'd be able to instantly tell whether you are in the desired spot and how to move the mouse.

**Comment by clementgallet** [comment]
To understand correctly, you want to draw a crosshair on the position of the cursor of the previous frame?

**Comment by vadosnaprimer** [comment]
Of the current frame, matching values recorded in the movie for that frame.

**Comment by clementgallet** [comment]
Added. You need to enable this in the settings: `Video > On-screen display > Crosshair`. It is enabled by default for new games.

**Comment by vadosnaprimer** [comment]
Works great, thanks!
