### ISSUE TITLE
TMNT: Shredder's Revenge fails to launch on libTAS due to ISteamRemoteStorage error

### ISSUE THREAD

**Issue by TheAmazingAladdin** [clementgallet/libTAS#514]
![image](https://user-images.githubusercontent.com/108961061/208490838-226b4930-8a54-4512-8df8-a4f9e803439f.png)

Time Tracking with clock_gettime() realtime and clock_gettime() monotonic enabled, prevent writing to disk enabled and Virtual Steam client enabled.

Log:
```
theamazingaladdin@theamazingaladdin-G3-3500:~/Downloads$ libTAS
Attempt 1: Connected.
[libTAS f:100] Thread 14865 (main) OpenGL vendor: Mesa/X.org
[libTAS f:100] Thread 14865 (main) OpenGL renderer: llvmpipe (LLVM 13.0.1, 256 bits)
[libTAS f:103] Thread 14865 (main) ISteamRemoteStorage: No version specified, defaulting to STEAMREMOTESTORAGE_INTERFACE_VERSION014
Shutdown handler: initalize.
```

System Specs:
i7-10750H
RTX 2060 mobile (working with nvidia-smi)
16 GB RAM
37 GB Storage on "/"
37 GB Swap Partition
Ubuntu 22.04.1 LTS (lsb_release -a)

**Comment by clementgallet** [comment]
Fixed in 288d7f5796d136548044310c54e732a4acd754fd
