### ISSUE TITLE
Build failure due to C++17 use / lack of explicit standard setting

### ISSUE THREAD

**Issue by CasualPokePlayer** [clementgallet/libTAS#516]
OS: Debian 11
Compiler: gcc/g++ (Debian 10.2.1-6) 10.2.1 20210110

std::optional is used in a few places, which is a C++17 feature. This results in a build failure for me with the `build.sh`, as the gcc shipped by Debian defaults to C++14.

Issue is likely resolvable by simply explicitly having an `-std=c++17` flag? Maybe also useful: https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_17.html

**Comment by clementgallet** [comment]
Thanks, the code is written to support c++11, but apparently when I switched to autoconf, I didn't add the flag during compilation.
