### ISSUE TITLE
Update loaded lua script on every run

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#519]
If you've loaded a script once, editing the file won't take any effect until you pick that same file again through the menu.

When writing a script it's very often that you have to edit and reload it **a lot** of times, and there's no intuitive benefit in it _not_ updating in libtas memory after you've edited the script and saved the changes.

Ideally there'd also be an indication of which script is currently loaded, to make it obvious that there is one, and which exactly (makes sense when juggling several scripts).

**Comment by clementgallet** [comment]
Not what you asked (yet), but in d050a1acf298d9101ea76e4947459eb27e2cd8fe lua `print()` output is redirected to its own console in a Qt window
