### ISSUE TITLE
Games written in the love 11.1 framework hang when love.audio.stop() is called

### ISSUE THREAD

**Issue by dwangoac** [clementgallet/libTAS#52]
Steps: Play a game that uses the love 11.1 framework (https://bitbucket.org/rude/love/) and trigger an action that causes love.audio.stop() to be called, such as going down a pipe while playing mari0 (https://github.com/Stabyourself/mari0).

Result: Whenever love.audio.stop() is called, frames stop advancing and the game appears to hang. There are no obvious debug logs that point to a problem when the hang appears.

Additional information: I do not yet know what other scenarios cause this issue. Disabling all calls to love.audio.stop() is sufficient to allow a full TAS of mari0 to be completed. We have assistance from the mari0 developers as needed, but this appears to be an issue with the interaction between libTAS and the love framework itself.

**Comment by clementgallet** [comment]
Thanks for the precise comment! I was indeed a bug where the same mutex was locked twice when a game calls `alSourceStopv`. Fixed in 652278b61d88f863ba197c72afa19400bc7aa2cf
