### ISSUE TITLE
Make Settings its own menu

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#521]
...instead of putting it under File menu, which means you have to click an extra time each time you need to tweak a setting.

**Comment by clementgallet** [comment]
Upon use, this feels indeed less practical. Would you:
* keep the settings with tabs, and in the settings menu, points each menu item to the same settings window, with the associated tab opened?
* separate each settings tab in its own window, and points each menu item to this window?

**Comment by vadosnaprimer** [comment]
If it's possible to open the desired tab right away, having them all in the same dialog with tabs, individual menus opening their respective tabs, that'd be ideal. Dolphin works that way.
