### ISSUE TITLE
[Feature Request] Input Editor: [Button / Auto] seek to current frame

### ISSUE THREAD

**Issue by Semnodime** [clementgallet/libTAS#528]
Currently, there is no option to seek to the current frame, even upon advancing one frame.

I'd request 
- a button to immediately seek to the current frame
- an (toggable) option to seek to the current frame upon advancing a frame

One issue triggering the request is the fact that changing a mouse button field withinin the past input sequence loads the nearest savestate before that change and reruns up to the changed frame.
Pausing during this rerun (e.g. by pressing <kbd>v</kbd>) will break the auto scrolling feature.

**Comment by clementgallet** [comment]
I'm not sure I understand "current frame". You can seek to any frame by clicking on the first column of the desired frame in the input editor.

I agree that pausing during the rewind process does mess up the autoscroll.
