### ISSUE TITLE
Videos don't start dumping from the first frame

### ISSUE THREAD

**Issue by fsvgm777** [clementgallet/libTAS#55]
This is a pretty critical bug from TASVideos's point of view, since the first frame is missing entirely from any AVI dumps created with libTAS (not to mention more frames can go missing if the movie was started unpaused). I'm pretty sure this is due to the ffmpeg process only starting *after* unpausing the game, rather than while the game is still paused.

To properly replicate this bug, here's a LTM of dwangoAC's attempt at TASing Mari0 (1144 frames long): [mari0-1AttemptFirstLevel.zip](https://github.com/clementgallet/libTAS/files/2298236/mari0-1AttemptFirstLevel.zip)

Now, configure the encode and start the encode *before* clicking Start (and ensure the game starts up paused). Then, when it auto-pauses when the movie reaches its last frame, click on Stop. Then, drag the encode to VirtualDub (if it's an AVI) or Avidemux (if it's any other format). Either should report 1143 frames instead of 1144 frames, with the first frame missing entirely.

This was tested on the latest revision (ef5e0ced0d5d40ab9c4a0cf9e91cda7c9e553a9a as of this writing)

**Comment by fsvgm777** [comment]
All right, thanks for the fix. I mainly noticed it in Mari0, since the first frame that's displayed here is actually non-black (and conveniently corresponds to the first frame of the movie file).

As for games that don't open their windows immediately, I think the saner way would be to encode black frames at the beginning for each non-drawn frame happening at game startup.

**Comment by clementgallet** [comment]
Encoding back frames when game window has opened but no rendering has been done yet (6c375b2db8be039579641d788987e6ecca63fb3c)

**Comment by clementgallet** [comment]
If frames must be encoded without the game window opened, delay the encoding until game window opens (to get screen parameters) and write extra blank frames as needed. Also write the actual delayed audio samples for the case when the game outputs audio before opening the game window (fe9fed4c3a505eaa1ab9798a44d67d99a60ed091)

**Comment by clementgallet** [comment]
Yes, it is possible for games to change their resolution. Currently I restart the encoding process if screen coordinates have changed. I just need to change the filename (right now it overwrites the previous one).

Framerate is something we enforce, so the game cannot do anything about it. If it decides to change its internal framerate, it will just result in duplicate/skipped frames, or maybe broken physics, but the output will always be at the same framerate.

**Comment by clementgallet** [comment]
Now encode filename is added a `_dd` before the extension starting the second segment, with `dd` starting at `01`, in case you would want to add `_00` to the first file on your scripts (83a6b8e8c1718e251590acde067994c6dab66663).

**Comment by vadosnaprimer** [comment]
It might be nice to make 0 padding optional, also limiting it to 2 digits, while common sense, may be problematic if a game is way too crazy about resolution changes. In our processing scripts, we can handle both zero-padded and non-zero-padded naming, so I'm even unsure padding is needed at all.

**Comment by clementgallet** [comment]
Alright, I removed zero-padding (ab9e3daecd2d59c133278c405ec7480a5258471c).
