### ISSUE TITLE
Requires liblua 5.3-0

### ISSUE THREAD

**Issue by CRD716** [clementgallet/libTAS#589]
Currently the Readme says that you can use either liblua5.4-0 or liblua5.3-0, however libTAS will not run unless liblua5.3-0 is installed.
If you attempt to run with just 5.4-0, the following error will be thrown: `libTAS: error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory`

**Comment by CasualPokePlayer** [comment]
The library which is required depends on the build environment. The latest .deb will end up requiring liblua5.3 due to how it was built. If you end up using a (recent?) CI build, it will require liblua5.4. You can also build it yourself and to have liblua5.4 used.
