### ISSUE TITLE
OpenAL device list error with game "Osmos" - No sound

### ISSUE THREAD

**Issue by Masterjun3** [clementgallet/libTAS#60]
The issue occurs when starting the [free demo of Osmos](https://www.hemispheregames.com/demos/OsmosDemo_1.6.0.deb) in libTAS with the option `Runtime > Time tracking > Main thread > gettimeofday()` enabled, and the run path set to `/opt/OsmosDemo/` to make the game (`/opt/OsmosDemo/OsmosDemo.bin64`) even start up.

The console error message (from the game) says:

```Initializing OpenAL
Getting OpenAL device list
ERR: Cannot enumerate OpenAL devices
Found no devices
WARNING: Failed to initialize OpenAL
```

Otherwise the game works, just there is no sound.

**Comment by Masterjun3** [comment]
It seems like the game checks if enumeration is possible by using something similar to the example shown on [this page](https://ffainelli.github.io/openal-example/#_device_enumeration), so I edited Line 150 in alc.cpp to say `return ALC_TRUE;`, which is clearly a wrong fix, but it solves the issue in this particular case. https://github.com/clementgallet/libTAS/blob/1756d953c272a2c65d971ab5a5c26fedf722145b/src/libTAS/audio/openal/alc.cpp#L141-L151
```Initializing OpenAL
Getting OpenAL device list
Found 1 devices:
  Device 0: OpenAL Soft (3: OPENAL DEFAULT)
Pass 1: no valid device was specified (-1)
Pass 2: no valid device was specified (-1)
Pass 3: attempting device 0: "OpenAL Soft"...
Creating OpenAL context
Opened device "OpenAL Soft"
Device supports maximum 256 sources
Streaming music
```

I guess you can tag this as _enhancement_, since it's not a bug per se. It's simply not an implemented feature yet.

**Comment by clementgallet** [comment]
Thanks for the digging! Indeed it seems the game was checking on `ALC_ENUMERATE_ALL_EXT` extension. I added a couple of extension support and default the return value to true like you did (with a warning), because it is not the first game to expect an extension to be supported without any fallback (e03cd5e89161a138f92f94fefaa0730d79fec4b3).
