### ISSUE TITLE
Option to hide marker view

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#603]
Jumping around markers and having them all visible is not always needed, but marker view takes away unpredictable amount of overall input editor space (because there's no way to resize it to be smaller), so it'd be really helpful if there was an option to hide it for future sessions. Not sure what the default should be tho.

**Comment by clementgallet** [comment]
Implemented in 6e6b7ce4084b35cce76e5cb4b33d52a9ebc04496
