### ISSUE TITLE
Add `Platform: Flash` to annotations automatically for Ruffle

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#614]
Only needed for tasvideos submissions, but people forget to do it all the time. Ruffle is a Flash-only emulator, so should at least be safe to hardcode.

**Comment by Randomno** [comment]
Related to #551 but doesn't look like that's going anywhere, so this is a better option

**Comment by vadosnaprimer** [comment]
Hmm, actually including the executable name would be neater since we could deduce the platform directly that way.

**Comment by vadosnaprimer** [comment]
I found out it's already there and we should be using it
https://github.com/clementgallet/libTAS/blob/c890635d47748b3d5e480b2a552ef2724fbdaf87/src/program/movie/MovieFileHeader.cpp#L133
