### ISSUE TITLE
X-Moto doesn't get any input

### ISSUE THREAD

**Issue by D-prog-55** [clementgallet/libTAS#69]
- OS: Kubuntu 18.04 (both host and VirtualBox guest)
- libTAS version: [master/e263c73](https://github.com/clementgallet/libTAS/commit/e263c7328b91edbbbe324ca28fd6ee4290197132)

When using libTAS with the game X-Moto, it appears that no input (neither keyboard nor mouse) seem to work. Only the mouse position correctly works, even if the display shows I'm pressing a mouse button or key.

Also, when clicking the "Stop" or "Kill" button, the game doesn't close (and is still active, but the mouse gets stuck in the top left corner). Even running a `kill` command doesn't get rid of the window (unless `-s SIGKILL` is used). The only other way to close the window is to close libTAS, which causes the following to be printed in the console:
```
Game is not responding, killing it
Got unknown message!!!
```
Nothing else that seems relevant appears in the console (just some `Attempt X: Couldn't connect to socket/Connected.`)

**Comment by clementgallet** [comment]
X-moto works fine for me. It may a problem of the wrong version of SDL being detected. Could you check the following: `Runtime > Debug > Print Categores > SDL` and `Runtime > Debug > Exclude Categores > Time Get` and `Sleep`.

Then you check `Pause` and launch the game. You should see in the terminal the following (except maybe the second line depending on your config)
```
[libTAS f:0] Thread 3152 (main) SDL_CreateMutex call.
[libTAS f:0] Thread 3152 (main) ERROR: Both SDL versions were detected! Taking SDL1 in priority
[libTAS f:0] Thread 3152 (main) Detected SDL 1.2.15
[libTAS f:0] Thread 3152 (main) SDL_CreateMutex call.
[libTAS f:0] Thread 3152 (main) SDL_Init call.
[libTAS f:0] Thread 3152 (main) SDL_InitSubSystem call.
[libTAS f:0] Thread 3152 (main)     SDL_TIMER enabled.
[libTAS f:0] Thread 3152 (main)     SDL_VIDEO enabled.
...
```

About the `Kill` button, it sends a SIGTERM signal but in most cases it is not enough to close the game, so I guess I'll change to SIGKILL.

**Comment by D-prog-55** [comment]
I have the save SDL version (1.2.15) detected. Here is a pastebin of the debug log: https://pastebin.com/VAK06CAM

**Comment by clementgallet** [comment]
Thanks ! I think I know what is going on. Could you try the last commit (9d20953ee3b03141e7b332481377268219225634). In some versions of SDL1 library, we don't hook `SDL_InitSubSystem` call from `SDL_Init`, so some parameters are not initialized.

**Comment by D-prog-55** [comment]
It works now, thanks ^^
