### ISSUE TITLE
Not using the custom allocator is broken

### ISSUE THREAD

**Issue by viroulep** [clementgallet/libTAS#7]
While rebasing my changes for thread synchronization, I found out I just couldn't run anything using the current master.
It looks like turning off the custom allocator has some weird behavior, when I activated logging I found something like this:
> [...]
[libTAS f:0] malloc call with size 21
[libTAS f:0]   returns addr 0x106e1d0
[libTAS f:0] free call with ptr 0x108aa70
[libTAS f:0]   returns
[libTAS f:0] free call with ptr 0x108aa70
[libTAS f:0]   returns
[libTAS f:0] malloc call with size 120
[libTAS f:0]   returns addr 0x108aa70
[libTAS f:0] allocate call with length 41 and sizeof 1
[libTAS f:0] init call
[libTAS f:0] allocateUnprotected call with size 41
[libTAS f:0] allocateInExistingBlock call with bytes 41
[libTAS f:0] newBlock call with size 82
[libTAS f:0] Create new MOD of address 0x7faab52c3000 and size 4064
[libTAS f:0] allocateInExistingBlock call with bytes 41
./build/linTAS  -l /home/fifi/dev/libTAS/../../fez/lib64/libmono-2.0.so.1 -l /lib/x86_64-linux-gnu/libm.so.6 -l /lib/x86_64-linux-gnu/librt.so.1 -l /lib/x86_64-linux-gnu/libdl.so.2 -l /lib/x86_64-linux-gnu/libpthread.so.0 -l /lib/x86_64-linux-gnu/libc.so.6 -l /home/fifi/local/lib64/libstdc++.so.6 -l /home/fifi/local/lib64/libgcc_s.so.1  
Connecting to libTAS...
Couldn’t connect to socket.

The beginning of the log looks good, however at some point "allocate" gets called, and it's in the custom allocator.
Simply removing `malloc.*` makes the game running ok: I don't know well the interaction between libTAS and malloc, but is there anything that forces us to use the hooks even if the custom allocator is turned off?

If not we could just make this a cmake option, and simply encapsulate the malloc functions in an `#ifdef CUSTOM` or something. That way the name would not be exported in the library and there would be no hook issue.
Note that this solution involves reconfiguring the project when you want to activate the allocator, but you could just have two build directories, one with the custom allocator activated, and the other without.

**Comment by clementgallet** [comment]
I forgot to add the custom allocator option in ManagedAllocator.h that defines a custom allocator class for std containers. I'm not sure it is necessary to replace the allocator with a custom one though.

**Comment by viroulep** [comment]
So do you want to add the option or just remove the thing? :p

**Comment by clementgallet** [comment]
Well, add the option for now, in the safe::* definitions if possible

**Comment by clementgallet** [comment]
Fixed in 7cbef383536902c32813983c4649e37055cfb777 together with making custom allocator a cmake option.
