### ISSUE TITLE
Tool won’t start because qt-5.11 is not found

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#71]
And yes, I did install qt-5.11.1 but it still comes with the error. Now I DID disable android in the installation, but that shouldn’t affect the program.

**Comment by clementgallet** [comment]
Could you please tell me which OS do you use, which version of libTAS (32 or 64 bits), and did you install the deb package or just the binaries ?

**Comment by InfamousKnight** [comment]
Ubuntu 18.04 64-bit installed latest Debian package. 1.3.0 worked fine, 1.3.1 doesn’t work.

**Comment by clementgallet** [comment]
Ok I'm having the same error on my Ubuntu VM. Somehow Qt takes my installed version for the minimal version requirement :/ Working on it.

**Comment by clementgallet** [comment]
Ok could you try again with the replaced deb package ?

**Comment by InfamousKnight** [comment]
I will later today. I don’t really have internet at home, and am relying on free WiFi and friends for that. Just saving money.

**Comment by InfamousKnight** [comment]
Yep, its fixed.
