### ISSUE TITLE
Movie verification

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#73]
Upon loading a movie, is it possible for libTAS to report all mismatches between any data read from the movie and its counterparts in the actual game? Framerate and framecount come to mind as the most obvious ones, for example, how do we make sure they're not hacked (needed for the site movie parser). Also I haven't checked if any hashes are also stored, they are usually verified upon movie load. Maybe other stuff like that is also present in movies?

**Comment by clementgallet** [comment]
Framerate cannot be hacked, as it's not an informative parameter but it tied with frame occurrences during the game. If you hack the framerate in the movie file, it should desync. It it doesn't desync, then the resulting movie is legitimate.

Framecount can be hacked, yes. I suggest you compute the framecount from the actual number of frames in the inputs file, and not from the movie metadata. There is a warning on the console when the framecount movie parameter and the actual frame count differ. I could make it a GUI message box for more visibility.

I thought about storing a hash of the game executable, yes. It would be useful to detect game version mismatch.

**Comment by clementgallet** [comment]
Added md5 hash in movie parameters, and display a message box if hash mismatch between movie and executable (d8b083224f6076d224a7237e3870abccc9e9001d).
