### ISSUE TITLE
The game window goes inactive if no inputs are given for some time

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#77]
This causes the window to go grey and it is hard the features in the game during it.

**Comment by clementgallet** [comment]
I implemented the answer to ping messages from the window manager, which should fix this issue (3c13555be76befb141351deb1fef10750af57e53). I didn't test it, because I don't have a Ubuntu Unity yet.

**Comment by Matte27** [comment]
This still exists.

**Comment by clementgallet** [comment]
It seems to be fixed by fa6493ef99386d1932b8b15bbdb2aa75da67439f
