### ISSUE TITLE
Is there any way to TAS flash games?

### ISSUE THREAD

**Issue by Thestickman391** [clementgallet/libTAS#78]
I'd like to tas a flash game with this but everything I've tried doesn't seem to work. I've tried a browser, the flash player projector some other flash program, nothing. Does anyone know of a way to do so? (Sorry if this is the wrong place to post this, couldn't find anywhere else)

**Comment by clementgallet** [comment]
It is not possible for now, as standard windows (non SDL or OpenGL) are not supported.

**Comment by vadosnaprimer** [comment]
There is now. Properly installing sdl-gnash is the key, Flash games do work. This can be closed.

**Comment by nlburgin** [comment]
What about Flash games that don't work in Gnash, though?

Like Offspring Fling, for example.

**Comment by noellekiq** [comment]
the official flash player uses qt which is not supported in libTAS

**Comment by clementgallet** [comment]
You can check on [Lightspark](http://lightspark.github.io/), it should be possible to make it to work with libTAS.

**Comment by nlburgin** [comment]
Lightspark sounds like a cool replacement for the clearly stagnated Gnash project. 

It also looks like it's not complete yet, though. I hope they're able to finish it.

As far as getting original flash player to work... If the official standalone player is out of the question, I wonder if it would be feasible to create some sort of shim that could run NPAPI plugins in a quasi-standalone fashion from inside an SDL window? 

(Of course that's outside the scope of *this* project, but I do wonder how feasible it would be.)

**Comment by vadosnaprimer** [comment]
There is such a thing but I forgot the name. @Asnivor might remember.
