### ISSUE TITLE
Savestates can't be loaded after recording

### ISSUE THREAD

**Issue by Matte27** [clementgallet/libTAS#79]
Steps to reproduce:
1. Save a savestate
2. Advance some frames and start recording
3. Record for some time and stop recording
4. The savestate can no longer be loaded

**Comment by clementgallet** [comment]
What is happening when you load the savestate ? Can you check which commit are you working with, because the encode feature has changed completely (now using a pipe to a ffmpeg process), so it should not spawn any thread now. It is working fine for me.

**Comment by Matte27** [comment]
I haven't updated for a while so it is some old version.

**Comment by clementgallet** [comment]
Should be fixed already.
