### ISSUE TITLE
Desktop shortcut for libTAS

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#81]
It'd be really useful to have a simple icon that launches libTAS on the desktop, since we don't have to run it from the terminal too often for regular use. When installing from the ювуи package, is it possible to create such an shortcut, and also to register in main OS menu?

**Comment by vadosnaprimer** [comment]
You're not launching it frequently enough if you prefer typing it every time. Bash script can be made, just as a shortcut can be made manually. But explain to me how creating it automatically upon installation is worse than manually.

**Comment by InfamousKnight** [comment]
I never said it was worse. It just doesn’t bother me that much. I have to type in my password just to log in. No big deal. I open up web browser to go to tasvideos.org. I open terminal to open lintas.

**Comment by Noahkiq** [comment]
hasn't this been added?

**Comment by vadosnaprimer** [comment]
Yeah.
