### ISSUE TITLE
Loadstate across Recording and Playback modes

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#88]
When one prefers manual input editing over old-style rerecording of every frame, libtas most of the time hangs in the Playback mode, while user is setting inputs. States are loaded in Playback mode in order to rewind and update input.

Then, every once in a while one needs to reload the state of the entire movie. TASEditor and TAStudio call such states branches, and they can be loaded in Playback mode, restoring all input to what it was for that branch. In libtas, this functionality requires switching to Rec mode, loading the needed state, and then switching back to Playback mode to resume editing.

This might be the usual routine for traditional rerecording, but for heavy mouse editing, repeating this very often just loses a lot of time and attention.

Would it be possible to add a way to tell the UI in which mode I want to load a savestate, so that mode would be used for loading it, but without switching the entire tool to that mode afterwards? Something like Shift + numkey for Read+Write load (load branch), and just numkey for Read-Only load (jump to frame)?

**Comment by clementgallet** [comment]
Here's what I have in mind: adding an OSD element with "1 2 3 ... 9" for each slot. Each number is gray for no savestate, white for normal savestate and colored for branch ? You could switch between savestate and branch using the corresponding numkey ?

**Comment by vadosnaprimer** [comment]
OSD or GUI? Also, branches are movie savestates in nature, just a little bit if extra info is stored. libTAS doesn't offer this extra info yet, so here it's all the same thing.

As long as I have a way to load movie data from a savestate without switching to rec mode, and as long as I can simply jump to the frame the state is at, it's all good. Extra hotkeys will probably work well because libTAS is closer to a normal rerecording tool than to anything more novel.

**Comment by clementgallet** [comment]
I'm trying to never force the user to look at the GUI window during actual TASing, because switching from one window to another is distracting, and also in some cases the game window must take the full screen (some games must be TASed with a specific resolution).

**Comment by vadosnaprimer** [comment]
Then what do you mean by "switch between savestate and branch"?

**Comment by clementgallet** [comment]
Exactly what you suggested: switching between mode where the savestate is loaded in read-only mode ("savestate") and where the savestate is loaded in read+write ("branch"). Then Fn to load savestate of slot n in that mode.

**Comment by vadosnaprimer** [comment]
Okay sounds good.

**Comment by clementgallet** [comment]
Oh, before implementing new stuff, there's a hotkey to switch between Playback and Recording modes. This saves you from using the mouse. Are you still needing the branch mode?

**Comment by vadosnaprimer** [comment]
Yes, because even with the mode hotkey, I'd constantly have to switch back and forth just to load the branch. Operations that are so overwhelmingly common ask for simplification.

**Comment by clementgallet** [comment]
Actually, I changed my mind and implemented another set of hotkeys to load a state in branch mode, using LAlt + Fn hotkeys (016fbf6ed18cf39480c0fc140d17280e99138b00). AltL is far enough from LShift so that the two shouldn't be mixed.

**Comment by vadosnaprimer** [comment]
Alt+Fn hotkeys spawn various OS menus instead.

**Comment by clementgallet** [comment]
Switch to LCtrl then (deb1fe93b1a1caf31a111b975cc3e98775c5e23a)
