### ISSUE TITLE
Input Editor and savestate slot indication

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#89]
Both TASEditor and TAStudio show which branch is present on any given frame. They use the leftmost column to put branch numbers there, for branches that were saved on those frames.

Please let input editor show the index of the savestate that exists on any displayed frame row in the input roll.

This allows to be fully aware where your savestates are saved at, and also lets to use them as markers for some key frames you want to compare to.

For instance, I exit a room at frame 1000. On that frame I save a state to slot 1. For all the attempts to improve this, as I exit the room at different times, I use other slots to save every input combination I care about. In the end, upon a mere glance on the inputroll, I instantly see which savestate stores the best attempt, the worst attempt, and what was my initial time. So I can just load the earliest one, and resume from there.

This also allows to distinguish the current segment I'm working on: where it starts, where it ends, how long it takes. How far back I need to go to fully redo this segment, and so on and so forth.

**Comment by vadosnaprimer** [comment]
I'll check it later, but the common solution is, when there are more states on that frame, only the most recently used one is displayed.

**Comment by clementgallet** [comment]
There should be a column before the frame column which contains the savestate slot number

**Comment by vadosnaprimer** [comment]
Okay I properly updated things and now I see it. What is a darker green used for in input roll? Maybe it should only be present where there is a savestate on that frame?

**Comment by clementgallet** [comment]
I added a darker colour to frames containing a savestate, and showed the last saved/loaded savestate in bold (b1d09406a212ab106aed8a0a1813575316eca96c)

**Comment by vadosnaprimer** [comment]
It's good now, than you!
