### ISSUE TITLE
Sub-platform

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#95]
This is no more just Linux! I congratulate everyone with this revolutionary fact!

And for the purposes of TASVideos submissions, we're going to need libTAS to tell us that something it's used to launch is a DOS game. Or a Flash game. For cases when proper Linux ports of DOS games are used, this is of course irrelevant. And I wonder how do we treat PrBoom?

But for Flash, as long as we're launching gnash, we know it's a Flash application. And for DOS we have DOSBox and its forks. It's so far very unclear what Windows versions one can run on DOSBox. But probably it can be resolved when Windows becomes a reality. For now Flash and DOS are probably the only ones explicitly needed.

**Comment by InfamousKnight** [comment]
Sweet! Maybe psp and ps3 will become acceptable in the near future too! But.. we need another release package to follow the rules.. I also can’t seem to compile it on my own too. Well, I CAN, just haven’t figured it out.

**Comment by vadosnaprimer** [comment]
Arcade is now reality via MAME.

**Comment by clementgallet** [comment]
The movie file stores the name of the game executable in its metadata. Do you want libTAS to output more than this ?

**Comment by vadosnaprimer** [comment]
Hmmm, now that I think of it, we can just parse the executable name and deduce the platform for things we're sure about. And when we need more, I'll reopen this issue.

**Comment by vadosnaprimer** [comment]
Alright so we've got a few submissions that run non-linux games in libTAS via different extra layers: ScummVM, FlashPlayer, and PCem. ScummVM and PCem can run different sub-platforms: DOS, Windows, Linux, and more. And it's impossible to deduce what PCem is emulating if you just launch it in libTAS, at least without a ton of hardcode.

So yeah, I guess it's time to let the user specify the platform the game is meant for, so that the tasvideos movie parser could pick that info up directly from the movie, similarly to how it works with bizhawk movies. Whenever we want to fix the platform, we edit the movie. This allows the user to set things up from the start, and we wouldn't need to manually change the platform in the submission form post-factum.

**Comment by InfoTeddy** [comment]
Is it possible to just use the annotations feature for this?

**Comment by vadosnaprimer** [comment]
Maybe. There should be some conventional way to store and parse it, while annotations are usually freestyle arbitrary text.

**Comment by InfoTeddy** [comment]
The convention could be implemented in the arbitrary text itself: Mandate, say, that the first like is something like `Platform: DOS`.

**Comment by vadosnaprimer** [comment]
If it's implemented as a separate thing, people would need to fill it in anyway, using the same kind of formatting that would pretty much work exactly the same as if it is in the annotations. Since regardless of where it is, the workflow would be identical for both sides, I can't think of good reasons to add a new entity to the LTM format just to hold this information. It can't be automatically filled so it can't go to config files, and since we need it to be explicitly set by the user, we can do it in the field the user has to fill anyway.

Thanks for ideas, I think this is resolved now.
