### ISSUE TITLE
MAME

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#96]
I couldn't resist. Tested with latest interim.

![5m06noz](https://user-images.githubusercontent.com/7092625/47180182-9cf11d00-d328-11e8-883a-cf2195131724.png)

http://sdlmame.wallyweek.org/download/
Install `mame-data_0.202+dfsg.1-0ubuntu1~ppa2~bionic1_all.deb` and then  `mame_0.202+dfsg.1-0ubuntu1~ppa2~bionic1_amd64.deb`

Launch mame with no game - configure options - video options - bgfx or opengl, window mode on. Back to previous - sound options - sound off.

Launch mame from libtas sending it a rom name as a parameter, have to configure the rom path (in configure directories) and put the file there. There should be other audio backends for mame, but it has to be rebuilt, which takes TONS of RAM.

When I launch btoads, I see the blue screen that normally can be skipped by any key. From libTAS, it can't. You have to expand the mame window to fullscreen using the dedicated button on the window itself, only then the game can process further.

Haven't tested actual tas functionality.

**Comment by vadosnaprimer** [comment]
I tested it a bit more. SDLMAME is not needed. Just install stable package `sudo apt get mame`.

When I enable sound in MAME, it can show the first frame, but dies after `SDL_GetCurrentAudioDriver call `with `Got unknown message!!!`.

Soft rendered in MAME dies after `SDL_PumpEvents call` with `Got unknown message!!!` too.

OpenGL renderer causes garbled libTAS OSD, but works fine.

BGFX renderer works the best.

The blue screen about machine specs can be skipped from libTAS like normally, if you enable Runtime - Debug - Native events.

**Comment by clementgallet** [comment]
Inputs are handled by mame after filling the SDL window id (7dd148d45e242ddd24c0de60c404f6f4e1d36186)

**Comment by clementgallet** [comment]
Fix the audio crash (098fb55457e0cdd40f8f71666e36aa89ce7cdf75)

**Comment by vadosnaprimer** [comment]
Wow... it's running perfectly!
Can you get the sound to actually play? When I enable it in mame I just hear tiny noises from time to time and that's all.
(Maybe you're actually working on that right now! :D)

**Comment by vadosnaprimer** [comment]
Yes... something bugged with my own sound I guess.
Thank you so much, tons of people have been waiting for mame tasing for years!
