### ISSUE TITLE
Recent files menu

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#99]
This would help a lot, since when having things installed, full paths are really hard to remember, as opposed to having everything in one place as a portable package. So something like a list of 10 recently ran executionals (with paths printed in their menu options, thankfully installed paths are usually short) would be awesome.

Judging by how libTAS remembers all the options I used for a given executional, this is already stored somewhere. So the only thing needed is having some easy access to it.

**Comment by clementgallet** [comment]
Yeah, the tool saves the configuration of each game in a file, based on the game file name. I added a general configuration file with the 10 most recent (existing) gamepaths, and changed the gamepath field to a combobox showing these paths (b2f12d2797f14ac7577e42e8f098877c1f2cbb5c)

**Comment by vadosnaprimer** [comment]
Seems to work, thanks.

**Comment by vadosnaprimer** [comment]
Actually, it doesn't seem to do anything before the first file is loaded. Picking the last used file is one of the main features of this thing.

**Comment by clementgallet** [comment]
Sorry, I didn't check when launching the tool without a gamepath. Fixed in 9134192acae8d80c9d664104757a0a2b1d44e8c4

**Comment by vadosnaprimer** [comment]
Yeah it works now.
